### ISSUE TITLE
Cannot change Default TeamspeakPort

### ISSUE THREAD

**Issue by BlueFreakLP** [flyth/ts3soundbot#1]
It´s impossible to change the Teamspeak Port in the Webinterface. It seems that nothing comes to the Server, in the console are no logs about the save, if i enter a non default port.

**Comment by flyth** [comment]
Should be fixed.

**Comment by dmham187** [comment]
Changing the Teamspeak port doesn't seam to work in the current version. The console says:
"Error in JSONjson: cannot unmarshal string into Go value of type int".

I think the quotation marks for the port are the reason for this. Removing them in the post request seems to fix the problem.

**Comment by flyth** [comment]
This has already been fixed. I'm sorry for the poor versioning right now, will change that as soon as possible. Try to upgrade to v0.8.5 manually (send me a mail if you don't know the link to that file) and run a `./ts3bot -update` afterwards. However, thanks for your detailed report and fix suggestion!
