### ISSUE TITLE
[Info/bug] youtube download not working?

### ISSUE THREAD

**Issue by Niggolo** [flyth/ts3soundbot#101]
i didnt use the bot for 1/2 week because i was busy but now im back and i was trying to download a music but i get "error"
i tryed to update youtube-dl but nothing changed

i missing some change to the bot?

**Comment by Khailz** [comment]
Update the bot http://frie.se/soundblog/many-things/

**Comment by Niggolo** [comment]
oh ok thank you

**Comment by flyth** [comment]
Youtube-dl handling hasn't changed. Please always try to use youtube-dl manually to see what the issue is. I've heard of problems regarding IPv4 vs IPv6. I will add better error handling for it in the next version.

**Comment by Niggolo** [comment]
for update without lost my setting/files i have to do something ? or i can just override everything?

**Comment by Khailz** [comment]
You will keep all your files and settings you just have to update the config.ini and copy the libsoundbot_plugin.so to the teamspeak plugin folder

**Comment by Niggolo** [comment]
ok thank you both again

**Comment by Niggolo** [comment]
about download, still error but it look like youtube-dl problem:

youtube-dl --extract-audio --audio-format mp3 -l https://www.youtube.com/watch?v=8EzfBYFU8Q0
[youtube] 8EzfBYFU8Q0: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by MrJoki007** [comment]
I think you cant download it because its locked from the GEMA

**Comment by Niggolo** [comment]
i downloaded many other files from this uploaded, or this dont matter?

**Comment by flyth** [comment]
Is there any chance your server is hosted by OVH?

**Comment by Niggolo** [comment]
it is why?

**Comment by flyth** [comment]
https://github.com/rg3/youtube-dl/issues/5138

**Comment by MrJoki007** [comment]
I dont know where you live, but if the server is hosted in germany you cant download gema protected songs and a lot of the uploads from this youtuber are locked from gema

**Comment by Niggolo** [comment]
weird, maybe it is with last versione of youtube-dl because i downloaded everything with no problem when i started using the bot

**Comment by Niggolo** [comment]
if you use -4 or --force-ipv4 parameter to the command it will download the file but it is m4a format (i dont know if it is normal, i never used youtube-dl)

youtube-dl -4 --extract-audio --audio-format mp3 -l https://www.youtube.com/watch?v=8EzfBYFU8Q0

**Comment by flyth** [comment]
Nope, it's because OVHs IPv6-Scope has been blocked. You need to force IPv4 - for which you'd need a wrapper to use it with the bot.

**Comment by Niggolo** [comment]
https://www.youtube.com/watch?v=BnigNbYVQJE
can someone try download this link and let me know if it work?

**Comment by JBou** [comment]
It's working fine for me.

**Comment by Niggolo** [comment]
you are using VPS/dedicated server?

**Comment by JBou** [comment]
Yes. I'm on Debian 7. It's hosted by https://contabo.com in Germany.

**Comment by Niggolo** [comment]
so the problem is OVH? it is confirmed?

**Comment by flyth** [comment]
Again: https://github.com/rg3/youtube-dl/issues/5138 has tests, workarounds and everything else

**Comment by comniemeer** [comment]
Doesn't works for me too as I have an OVH server.
But how to make a workaround for TS3SoundBoard?

**Comment by nrauschcom** [comment]
See #141
