### ISSUE TITLE
Cant open TS3

### ISSUE THREAD

**Issue by snikerfreak** [flyth/ts3soundbot#107]
Since i upgrade to the new version, i cant open the TS3.
Here's the log:
http://pastebin.com/53YRu1XX

What is going on?

**Comment by flyth** [comment]
Doesn't have to do with the update; try to remove the `LC_ALL="en_US.UTF-8"` or make it match your locale.

**Comment by snikerfreak** [comment]
Of course, i try without the LC_ALL, but still the same. :/

**Comment by flyth** [comment]
Still an issue with your locales. Google "locale::facet::_S_create_c_locale" - that's the error from the log.

**Comment by snikerfreak** [comment]
I reinstalled the VPS, install the whole again with the tutorial (https://github.com/flyth/ts3soundbot/wiki/Installation---Debian-&-Ubuntu)
on Ubuntu 12.04 64bit, but still the same. 

![screenshot at 12-43-35](https://cloud.githubusercontent.com/assets/11145356/6651552/c56f55dc-ca47-11e4-8caa-188a3f72a883.png)

Idea

**Comment by snikerfreak** [comment]
Thanks!
For the future, if somebody have this problem, try this:

sudo locale-gen en_US en_US.UTF-8
sudo dpkg-reconfigure locales

And then open the bot.
Thanks!

**Comment by flyth** [comment]
Did you google it? [Like this](http://stackoverflow.com/questions/19100708/mongodb-mongorestore-failure-localefacet-s-create-c-locale-name-not-valid)

**Comment by flyth** [comment]
Okay :)
