### ISSUE TITLE
Lumen Theme - Invisible Tag and Invisible Add to "Playlist"

### ISSUE THREAD

**Issue by UnwishingMoon** [flyth/ts3soundbot#108]
When I use the Lumen Theme the Tag Options and the "Add to Playlist" Options is Invisible, can you Fix it?? thanks you
I post an Image for help you to Fix
![Lumen No Tag Bug](https://cloud.githubusercontent.com/assets/11472973/6651368/5913efae-ca3f-11e4-8528-50e793f0dbd0.PNG)

**Comment by flyth** [comment]
It's rather difficult to fix single themes without ruining the others or editing the theme itself. I'm just using the raw original templates here - but I will look into it when I find some more time.

**Comment by flyth** [comment]
Fixed.
