### ISSUE TITLE
Whisper Group

### ISSUE THREAD

**Issue by dejred** [flyth/ts3soundbot#110]
Hi. Is it possible to BOT using whisper to the group? so that everyone who will handle the group could hear the music? no matter which channel they are

**Comment by flyth** [comment]
That's already on the todo-list but I haven't looked into it in depth. But I doubt it would be possible without introducing much complexity on the backend.

**Comment by mauzao9** [comment]
Well if we can like send a command to the bot or something in private chat and that will make us hear what's playing without being on the channel is already a win :)

**Comment by flyth** [comment]
Yeah, I know, but there's not really an API for me to implement that quickly.

**Comment by flyth** [comment]
This got implemented but is available in the hosting-version only for now. Will be a candidate for a premium version later on.
