### ISSUE TITLE
Autoplay on Start / Restart Play automatically

### ISSUE THREAD

**Issue by capsload** [flyth/ts3soundbot#111]
Hello,

i've already openend an issue, this feature should be set higher then "normal", since its really annoying restarting or clicking the stream again and again when its offline shortly. It should check or "recheck/replay" like every 60 minutes if the stream is offline or online again. Also; Autoplay Radio is one of the biggest wishes of me. Hopefully you can set this feature more on top of the "high" todo list.

Thank you!

**Comment by flyth** [comment]
Yup, you're right. I missed that thing from the multi-issue entry, sorry.

**Comment by capsload** [comment]
Thank you!

**Comment by flyth** [comment]
This seems to be tougher than I thought and I might need to postpone it a bit. However, there's a temporary workaround: you can create a playlist, add just the stream and set it to repeat.

**Comment by Niggolo** [comment]
if you didnd notice this issue is on 1.5 and 2.0 millistone :P

**Comment by flyth** [comment]
I'll add it to 3.0 as well, soon :)
This is sadly not _that_ trivial.

**Comment by capsload** [comment]
Buuuuuuuuuuuuuump!
:D, hopefully this will be included asap! :(

**Comment by flyth** [comment]
Made some progress here. Next version will include re-connects when streams got disconnected.

**Comment by capsload** [comment]
Sweet to hear! Looking forward to the update :)

**Comment by flyth** [comment]
Implemented.
