### ISSUE TITLE
[Feature Request] Identity manager

### ISSUE THREAD

**Issue by MrJoki007** [flyth/ts3soundbot#112]
It would be cool if you have a settings tab where you can add identities and then select one of them in the bot settings in a dropdown menu

**Comment by flyth** [comment]
Do you seriously need such a thing? For what exactly?

**Comment by MrJoki007** [comment]
Because i know a lot of teamspeaks where you can join with 1 client per identity and then it will get a mess with a lot of identities

**Comment by flyth** [comment]
I still don't get why. Just create a new unique id for each instance and you should be fine.

**Comment by MrJoki007** [comment]
ok
