### ISSUE TITLE
Client not found

### ISSUE THREAD

**Issue by ThyLeader** [flyth/ts3soundbot#114]
Hi! I am currently setting up the sound bot on a KVM emulated VPS running Windows 2008. Whenever I run the installer, I get an error saying It cannot find TS3. I have made sure I'm running 64-bit TS, and I've even tried setting the install folder to the TS3 directory. Has anyone had this problem and overcome it? Open to suggestions.

Thanks,
Colin

**Comment by flyth** [comment]
Don't set the install folder to your TS-folder. A proper installation should have a key in the windows registry pointing to your installation. If the installer can't find it, it won't install.
The key is `HKLM\Software\TeamSpeak 3 Client`. Make sure it's there and points to your TS-install-folder (64bit). You might need to install TS for `everyone`.

**Comment by ThyLeader** [comment]
Installing for all users fixed the problem. Thanks!
