### ISSUE TITLE
Can't control the bot via Teamspeak

### ISSUE THREAD

**Issue by GERIskillzZz** [flyth/ts3soundbot#115]
Hey,
I can't control the bot from inside Teamspeak. The music is playing, but when I type in !play or something else like !register .. nothing happens. I set up my Identity for the Client in the Webinterface, but it don't work.

PS: Darfst gere auf Deutsch antworten! :+1:

**Comment by GERIskillzZz** [comment]
I just tested it under windows. With the windows version it works, but under linux (where I need it), it doesnt :/ Im using Debian 7 64bit

**Comment by flyth** [comment]
There's no `!play` and `!register` will only work if you don't have your account bound, yet.

**Comment by GERIskillzZz** [comment]
Yeah but when I type !register on my Windowsbot, the bot writes to me that i'm already registred. The linux bot doesn't.

**Comment by mauzao9** [comment]
Uh one bug report, once i updated i broke my accounts, i can't create any account new account on the panel and !register will return one error that account may already exist, how can i fix this?

**Comment by flyth** [comment]
@GERIskillzZz : does the bot play music at all, then?

@mauzao9 : maybe you've just hit the user limit. Some error-messages are not that good right now, sorry.

**Comment by GERIskillzZz** [comment]
Yeah it plays music very well. But I can't control it via Teamspeak

**Comment by flyth** [comment]
What does it say in the log after you send a command, then?

**Comment by GERIskillzZz** [comment]
Nothing, that's the strange thing o.O

**Comment by flyth** [comment]
And you're using the 0.9.5 (and updated from that version) with the plugin from that version as well?

**Comment by GERIskillzZz** [comment]
I followed your tutorial, and copy-pasted the commands. So I think the versions are fine. I tried to run ./ts3bot --update, and it says that its up-to-date.

**Comment by flyth** [comment]
That's very odd, then. And you're the first person who reports something like that. :/

**Comment by GERIskillzZz** [comment]
Can you have a look at it? Would be very nice when it would work :/

**Comment by flyth** [comment]
Problem could not be identified, but had something to do with the server.
