### ISSUE TITLE
Youtube-Dl error

### ISSUE THREAD

**Issue by am4nr** [flyth/ts3soundbot#116]
Anyone get the same error?
![ss 2015-03-15 at 05 07 06](https://cloud.githubusercontent.com/assets/11098327/6656787/b4c37f3a-cb35-11e4-85d5-6e843bc0742d.png)
and yes i already updated it

**Comment by flyth** [comment]
OVH-customer? #101

**Comment by am4nr** [comment]
Nope

**Comment by flyth** [comment]
Then you've probably spammed Youtube too much ;) "Too Many Requests" is a limitation from YouTube itself.
