### ISSUE TITLE
Need more commands

### ISSUE THREAD

**Issue by SephLeague** [flyth/ts3soundbot#118]
Really nice work on the bot friend but i believe you should add some more commands like !quit !moveto --channel maybe other stuff

**Comment by DurtyFree** [comment]
I guess this isnt supposed to be a fully functioning Teamspeak Bot, its only meant to  be an music / soundbot for Teamspeak 3. 

But some commands would indeed be helpful, like !listplaylists, !pladd <part of name> <playlist> and more to manage playlists on the go.

**Comment by flyth** [comment]
I'll try to make most of the functionality accessible by commands as well - one after another. :)

**Comment by flyth** [comment]
More commands will follow as new features get added. Since this is not more specific I'll just try my best in adding things and close this :)
