### ISSUE TITLE
Enh: fix menu on a spot

### ISSUE THREAD

**Issue by am4nr** [flyth/ts3soundbot#119]
![ss 2015-03-16 at 09 20 01](https://cloud.githubusercontent.com/assets/11098327/6662596/9da824ee-cbbd-11e4-95fb-f72ac874b79e.png)

it would be pretty nice if this menu would stay at that spot i have about 300 songs uploaded and its pretty annoying if i want to do something on this menu i have to scroll back to the top of the page to use them. or maybe atleast a button which let me scroll all the way up with one click

**Comment by flyth** [comment]
I'm not sure about this one: if I let that menu stick, what about 30 playlists. They'd be have to squished into a small box, then. That "scroll-to-top"-thing is of course possible and I think I'll use the "logo" text for that.
