### ISSUE TITLE
[bug] instances debug console

### ISSUE THREAD

**Issue by zoxovsky** [flyth/ts3soundbot#12]
doesn't work if i have 2 or more instances, only showin ur first instance debug console

**Comment by bash89** [comment]
for overview would be good to sort every instance in an other "Tab" console wont get spammend and it will be easier to find a bug for an instance.

**Comment by flyth** [comment]
The debug console is something that will disappear soon as on-demand option for the server admin. Also I'm not sure if it is even possible to split instances there without creating another screen for each instance (which I guess would not be easy on resources). I'll look into that much later :)
