### ISSUE TITLE
Listing files & playlists and playing spcific files directly

### ISSUE THREAD

**Issue by shawly** [flyth/ts3soundbot#125]
Hi there, great Bot and it seems to be pretty stable even with 3 instances!

I would love to see a command like !playlists to show available playlists or similar, also it would be cool to use a !play <filename> command to play specific files that are already on the server instead of playlists only and a function to list the files that are available like the !playlists command I mentioned above.

Because I have multiple radio stations but I have to use one playlist for them and switch between the stations with !next and !prev, it's working but it would be much cooler if I could just say !play Radio/Jam (like !play <playlist>/<songname>) where Radio is the playlist and Jam is the url to the radiostream.

It would also be pretty cool, if the bot had the rights, that he could change the channel description, theme or his  own description to the current song playing.

I'm sorry if this is already on your todolist and I wasted your time...

**Comment by flyth** [comment]
I've seen installations that handled 60 instances pretty well :) So you're good even with a few more of them^^

The TS-commands definitely need to be extended in many ways and I've got quite a few ideas that are just not complete, yet. But I'll keep your suggestions in mind when implementing those commands :)

Channel description and such will also come sooner or later but has no high priority right now.

**Comment by shawly** [comment]
Sounds great!

I'm looking forward to the development of the bot, as soon as it is out of beta stage I might support it aswell! :>

**Comment by shawly** [comment]
Also it would be good if the instance could validate, if the user is in the current channel and if not he can't send commands to the bot except he has the permission.

Because the thing is, as soon as users in my Teamspeak find out, that you can change the other bots from another channel, the trolling will start.... this should be a high priority issue since you can pretty much mess the mood up when you start to Rickroll other channels for fun.

Also shouldn't be too hard to validate if the user is in the current channel right?

**Comment by flyth** [comment]
In the beta releases, the bot can be told to ignore commands from specific sources (private chat, server chat, channel chat).
