### ISSUE TITLE
Bot not joining server at all

### ISSUE THREAD

**Issue by recon88** [flyth/ts3soundbot#127]
Followed the install instructions but it doesn't want to join any server.

http://pastebin.com/yNwN25Xs

**Comment by flyth** [comment]
What's the exact command you're using to start the bot?

**Comment by recon88** [comment]
./ts3bot

**Comment by flyth** [comment]
That's what I thought. Then you didn't follow the instructions.

**Comment by recon88** [comment]
My bad. Got it.
