### ISSUE TITLE
Accounts per Instance?

### ISSUE THREAD

**Issue by mauzao9** [flyth/ts3soundbot#129]
Hello there.

I am wondering if it is possible something like that, in short, pretty much be able to assign X user account to X instance so the user wouldn't access both, only the one/ones it's assigned to.

This makes organization easier.

Also one issue report the youtube downloads history quite lags my browser a lot, there's a really huge history i can't clear there!

**Comment by Khailz** [comment]
Duplicate of #54

**Comment by mauzao9** [comment]
Okay
