### ISSUE TITLE
[enh] Music upload

### ISSUE THREAD

**Issue by bash89** [flyth/ts3soundbot#13]
would be nice beeing able to direct sort just uploaded tracks under "Uploaded Files" into playlists like in "all Music" (so you dont have to go to "all music" and start sorting from there, if u got 400+ tracks or more u have to scroll a lot :D )

**Comment by flyth** [comment]
I agree, this will be implemented sooner or later :)

**Comment by bash89** [comment]
awesome :)

**Comment by flyth** [comment]
This has been implemented slightly changed in the latest version; from now on it's possible to upload directly to playlists.
