### ISSUE TITLE
Disable commands from listening to server chat

### ISSUE THREAD

**Issue by Khailz** [flyth/ts3soundbot#130]
I've had instances of when an admin would accidentally  type in server chat and change all the bot's in the server at the same time. I thought it was a bit funny at first, but just to make it known, all commands in server chat apply to all bot instances in that server. Should be disabled or toggle-able if some people would like that.

(Should of made this issue last month. =_=-)

**Comment by flyth** [comment]
Oh :) I will fix that.

**Comment by Khailz** [comment]
great :D o/

**Comment by flyth** [comment]
Fixed.
