### ISSUE TITLE
Song List Responsiveness +

### ISSUE THREAD

**Issue by Khailz** [flyth/ts3soundbot#131]
Just want to point out that if your on the web interface and have a small resolution like 1366x768 then you can't see the entire right side of the song selection screen like so.

![qz1h317](https://cloud.githubusercontent.com/assets/6279013/6721893/aa610a9c-cda8-11e4-9817-a5756ba0b4e1.png)

Zoomed out:

![oy3i1lg](https://cloud.githubusercontent.com/assets/6279013/6721901/ca26e7ac-cda8-11e4-8091-e48470f36308.png)

Also I suggest adding another sort function like Date Added so you can see the newer songs at the top instead.

**Comment by flyth** [comment]
Thanks. I've just been to lazy to fix that before :) Fixed.

**Comment by Khailz** [comment]
Haha cool!
:D Some of them are so long that they push the duration timer out of the screen so I have to rename them >_<
