### ISSUE TITLE
Upload Page = RIP Browser

### ISSUE THREAD

**Issue by mauzao9** [flyth/ts3soundbot#133]
In a simply way that's the problem.

And i know why, the youtube upload history is too huge the page just lags out, and there is no way to clean it. Only way i'm uploading is via the command till some way to limit / clear the history of youtube-dl helps it.

Also, is it possible to get a new build of the bot? I got one other but i can't create accounts anymore so i believe i need to install it more clean again.

**Comment by flyth** [comment]
Fixed.

Next version will limit users to 100, you've probably just reached the current limit of 16.
