### ISSUE TITLE
TTS to quiet

### ISSUE THREAD

**Issue by MrJoki007** [flyth/ts3soundbot#134]
If you use Text to Speek (I used google) its to quit
It would be cool if the bot's music gets ducked or completly muted

**Comment by flyth** [comment]
As said via chat: use the "ducking" feature for now. There won't be a separate ducking setting for this anytime soon.

**Comment by am4nr** [comment]
Another question from me is how to use tts?

**Comment by mauzao9** [comment]
Something else i also ask, i put http://translate.google.com/translate_tts?tl=__LOCALE&q=__TEXT now how to make it actually work?

**Comment by mauzao9** [comment]
Oh i see !say command omg this is amazing, any recommendations of good ttl service?
