### ISSUE TITLE
!password not working

### ISSUE THREAD

**Issue by am4nr** [flyth/ts3soundbot#136]
it seems that !password doesn't work. if i create a new account and set the password i can't login in with the username/password it says unauthorized

**Comment by flyth** [comment]
Are you using the most recent version from yesterday? Should be working with that version.

**Comment by am4nr** [comment]
Now its working i think its just happening if you create a new account you have to set a password first then you can change it with the !password command

**Comment by am4nr** [comment]
well i'm retarded :D i just forgot that you have to set the right that you can log in to the webinterface
