### ISSUE TITLE
Webplayer

### ISSUE THREAD

**Issue by BlueFreakLP** [flyth/ts3soundbot#137]
Add Option to play or preview the music in the Browser

**Comment by flyth** [comment]
This probably won't happen as this would be essentially some kind of file-sharing where everyone accesses everyones files and listens to them individually.

**Comment by mauzao9** [comment]
Yeah, would be more likely a web-plugin to people listen to the bot on a website, but i think that's also going to a no-no the way everything is built.

**Comment by BlueFreakLP** [comment]
It's done and will be available in newer versions.
