### ISSUE TITLE
User registration not going well

### ISSUE THREAD

**Issue by Trantium** [flyth/ts3soundbot#140]
Hi again!

There seems to be an issue when a user registers for a username, it doesn't capture the password well and doesnt let the user in the panel, throws an unauthorised error.

If i change the user password manually on the admin panel he suddenly can.

Can you look into this issue?

**Comment by flyth** [comment]
See #136 
Are you using the most recent version from yesterday (linux)?

**Comment by Trantium** [comment]
Yes, used -update aswell

**Comment by Trantium** [comment]
http://puu.sh/gIyVT.png i've let another admin assign me the first 3 permissions. Still not working

**Comment by flyth** [comment]
That's strange, have tested it on my side and it's working. Will check again soon. Would be nice if others could check and report as well.

**Comment by Trantium** [comment]
root@musicbot:/home/Bot1# uname -a
Linux musicbot 2.6.32-042stab102.9 #1 SMP Fri Dec 19 20:34:40 MSK 2014 x86_64 x86_64 x86_64 GNU/Linux

chmod 777 on the whole folder

Can't really see what another issue could be. Workaround for now is just to update the password manually for each user who registered

**Comment by flyth** [comment]
You shouldn't change permissions at all. If the permissions were wrong, the bot would tell you that or crash :)

**Comment by Trantium** [comment]
I will see if i can setup the bot again from scratch. Which files do i have to copy to keep the music stuff intact?

**Comment by flyth** [comment]
You'd need to copy everything, then. So there's not really a from-scratch-option if you want to keep stuff.

**Comment by Trantium** [comment]
As for copying music, is copying the files inside the store folder enough? Would the files be recognized by the new bot?

**Comment by flyth** [comment]
Nope. It's a special indexing / deduplication system.

**Comment by flyth** [comment]
Please re-open if there's still an issue.
