### ISSUE TITLE
Give us an option to edit the Youtube-DL command

### ISSUE THREAD

**Issue by am4nr** [flyth/ts3soundbot#141]
This would be a solution for the problem of an OVH Server because if you use the simple command:

youtube-dl [youtube-link]

it doesn't work but if i use the forceipv4 command it works for me:

youtube-dl --force-ipv4 [youtube-link]

or is there a solution how i can change it for myself?

**Comment by flyth** [comment]
Build a small wrapper script. That should do it. Giving more freedom by default will just increase support cases for me :)

**Comment by am4nr** [comment]
yeah if i know how lol :D

**Comment by nrauschcom** [comment]
__Linux solution (by wrapper script):__
Create a script "my-youtube-dl" like the following:

    #!/bin/bash
    /path/to/your/youtube-dl --force-ipv4 "$@"

and use this script as youtube-dl location in your config.ini as
`YoutubeDLPath = "/path/to/your/script/my-youtube-dl"`

Make sure to give your script executing rights (`chmod u+x /path/to/your/script/my-youtube-dl`)
