### ISSUE TITLE
Profiles Table Error => TS3Client quit.

### ISSUE THREAD

**Issue by psadaic** [flyth/ts3soundbot#143]
`2015/03/21 17:54:16 b6a116b2 8a9e186c WARN   Could not insert into Profiles-Tableno such table: Profiles
2015/03/21 17:54:16 b6a116b2 8a9e186c WARN   Could not delete from Profilesno such table: Profiles
2015/03/21 17:54:16 b6a116b2 8a9e186c WARN   Could not insert into Profiles-Tableno such table: Profiles
2015/03/21 17:54:16 b6a116b2 8a9e186c WARN   Could not delete from Profilesno such table: Profiles
2015/03/21 17:54:16 b6a116b2 8a9e186c WARN   Could not insert into Profiles-Tableno such table: Profiles
2015/03/21 17:54:16 b6a116b2 8a9e186c INFO   Starting instance ts3server://5.196.190.119?port=9987&nickname=TEST&password=&cid=10825&channelpassword=
2015/03/21 17:54:17 b6a116b2 8a9e186c INFO   TSClient quit.`

From the web interface: http://i.imgur.com/bP1WzPN.png

Thanks in advance.

**Comment by nrauschcom** [comment]
Looks like a database problem.
I don't really know how this is handled by the bot, but you could try to (re-)install SQLite.

**Comment by flyth** [comment]
Seems like the TS-installation is messed up somehow (those tables are from the client, not the bot - the bot is just trying to clean up some stuff in there). However, closing this due to no further response.
