### ISSUE TITLE
Setting up youtubedl

### ISSUE THREAD

**Issue by teamoverdose** [flyth/ts3soundbot#145]
I know this isn't the right place to ask but can someone point me in the right direction of getting Youtube-DL set up? Whenever I type the code into the config it just says that it can read the config. Help is appreciated! Also, where is the music that I upload stored? Thanks!

**Comment by nrauschcom** [comment]
Please give me a look at your `config.ini` file and the output of `which youtube-dl`

**Comment by teamoverdose** [comment]
uh well right now I'm experiencing an issue where it states that it can't find the ts3 client although it was using it previously

**Comment by teamoverdose** [comment]
'TS3Path = "/opt/ts3soundboard/TeamSpeak3-Client-linux_amd64/ts3client_linux_amd64"
ListenHost = "0.0.0.0"
DataDir = ""
ListenPort = 8087
LocalPlayback = false
SecretKey = [119, 45, 91, 99, 55, 107, 220, 156, 76, 17, 5, 123, 135, 196, 46, 50, 208, 57, 79, 235, 158, 129, 168, 207, 38, 236, 115, 111, 88, 216, 99, 92]
Debug = false
LogLevel = 3
EnableProfiler = false
YoutubeDLPath = ""
EnableDebugConsole = false
UploadLimit = 83886080
RunAsUser = 0
RunAsGroup = 0
InstanceActionLimit = 6
UseSSL = false
SSLKeyFile = ""
SSLCertFile = ""
Hostname = ""
MTU = 1500
SampleInterval = 100
YoutubeDLPath = "/usr/local/bin/youtube-dl"

**Comment by nrauschcom** [comment]
Remove the `YoutubeDLPath = ""` in line 10, it will fix your bug.

**Comment by teamoverdose** [comment]
Wow, I'm such an idiot! Thank you very much!
