### ISSUE TITLE
How restart BOT?

### ISSUE THREAD

**Issue by dejred** [flyth/ts3soundbot#146]
http://prntscr.com/6k0s47

Hi. How to restart BOT?

**Comment by am4nr** [comment]
ps x | grep ts3bot

kill <PID> (the number on the left)

**Comment by nrauschcom** [comment]
You can also use

    pkill ts3bot
    ./ts3bot

**Comment by dejred** [comment]
To start again:

xinit / opt / ts3soundboard / ts3bot - / usr / bin / Xvfb: 1 -screen 0 800x600x16 -ac

??

**Comment by nrauschcom** [comment]
kill/pkill will end the bot, then start it again like for the first time.
I just made a script for starting the bot, so I don't have to type the screen command everytimes. That's the command:
`xinit /path/to/your/ts3bot -- /usr/bin/Xvfb :1 -screen 0 800x600x16 -ac`

**Comment by dejred** [comment]
Thanks :)
