### ISSUE TITLE
Accessing over reverse proxy or tunnel results in an error

### ISSUE THREAD

**Issue by shawly** [flyth/ts3soundbot#147]
I can't access the webinterface if I open a tunnel to the server where tsbot is running.
The same error occurs if I use Nginx as reverse proxy to forward the Webserver (running on server.example.com:8087) to another domain (musicbot.example.com on port 80) so I can close other ports for security reasons.

I can't run the bot on port 80 since the Nginx webserver also reserved that port, also tsbot would need root permissions to access ports below 1024 so that is no alternative..

Posted it to pastebin.com: http://pastebin.com/Xs1ZK64L

**Comment by flyth** [comment]
I just tested it and it works without problems.
