### ISSUE TITLE
YouTube Video are not Downloading :/

### ISSUE THREAD

**Issue by AddBrickDevs** [flyth/ts3soundbot#149]
Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by am4nr** [comment]
Is your server from ovh?

**Comment by am4nr** [comment]
If yes make a config file for youtube-dl which contains --force-ipv4 and its working like a charm

**Comment by flyth** [comment]
Could you please use the search function before posting here? Thanks.
