### ISSUE TITLE
[info] ts3soundbot on arch linux

### ISSUE THREAD

**Issue by Mawalu** [flyth/ts3soundbot#15]
I did some testing with the bot on arch linux. Everything is working fine, you only have to modify some settings.

1. Install the required packages: `pacman -S libev x11vnc xorg-xinit xorg-server-xvfb libxcursor teamspeak3 youtube-dl`
2. Download and unpack the soundbot.
3. Arch linux installs the teamspeak files to different locations (`/opt/teamspeak3` and `/usr/bin/teamspeak3`), but the soundbot seems to gues the teamspeak folder location from the binary path. 
To fix this problem, create a symlink: `ln -s /usr/bin/teamspeak3 /opt/teamspeak/teamspeak3`
4. In config.ini set `TS3Path` to `/opt/teamspeak/teamspeak3` and `YoutubeDLPath` to `/usr/bin/youtube-dl`
5. For some extra security I would create a new user for the bot: `useradd -d /opt/ts3soundbot -m -s /bin/false soundbot`
6. Sudo into the new user `sudo -u soundbot -s` and start the bot for the first time ` xinit /opt/ts3soundbot/ts3bot -- /usr/bin/Xvfb :0 -screen 0 800x600x16 -ac ` (I use `:0` because `:1` doesn't work for me)

With these steps you should get ts3soundbot running on arch linux. If I have some time I will try to create an aur package and a systemd unit file for the bot, so you don't have to run it manually.

**Comment by flyth** [comment]
Thank you very much for the tutorial, I'll add a link to to the beta-site :)

**Comment by Mawalu** [comment]
I now also created a systemd unit file:
```
[Unit]
Description=Musicbot for teamspeak 3 server
After=network.target

[Service]
User=soundbot
Group=soundbot
ExecStart=/usr/bin/xinit /opt/ts3soundbot/ts3bot -- /usr/bin/Xvfb :0 -screen 0 800x600x16 -ac

[Install]
WantedBy=multi-user.target
```

To use the service, just drop the file into `/etc/systemd/system/ts3musicbot.service`. You can now start the bot using `systemctl start ts3musicbot` and enable it for autostart using `systemctl enable ts3musicbot`

**Comment by bash89** [comment]
awesome work ! thanks

**Comment by BlueFreakLP** [comment]
It works ;)
