### ISSUE TITLE
Sound Distortion on Win7 x64

### ISSUE THREAD

**Issue by SomeDumbRedneck** [flyth/ts3soundbot#150]
i loved your soundboard, so i went a step further enclosed please find a zip with a .wav file of the bot playing multiple radio stations happens regardless if its a localy based mp3 or radio station
watched cpu/mem neither were the problem, tried on 2 different pc's to see if it was a audio driver issue
with no change server channel bot plays on is OPUS/MUSIC plays soundboard with no issue. as i stated i love the soundboard i think this would even be more of a blast

http://getspazzed.net84.net/upload/bot.rar

**Comment by Zent0** [comment]
I had a similary problem on one of my Windows Server. Did you have the possibility to use the linux version? 
The linux version needs less ressources.

**Comment by SomeDumbRedneck** [comment]
yes i do understand linux and its resources, but the pc i run it off of i use for some windows only applications. i wish linux and windows sometimes were reversed in demands, or atleast equal to all companys that develop pc software/games

**Comment by BlueFreakLP** [comment]
It should be fixed in the new releases, if not please open a new Ticket.
