### ISSUE TITLE
Start error

### ISSUE THREAD

**Issue by Theboss996** [flyth/ts3soundbot#153]
Mein Problem ist dass wennn ich ./ts3bot mache oder ./ts3bot -update mache eine fehlermeldung kommt die wie folg aussieht

musicbot@Navlis:~/ts3soundboard$ xinit /home/musicbot/ts3soundboard/ts3bot -- /usr/bin/Xvfb :1 -screen 0 800x600x16 -ac

[dix] Could not init font path element /usr/share/fonts/X11/cyrillic, removing from list!
[dix] Could not init font path element /var/lib/defoma/x-ttcidfont-conf.d/dirs/TrueType, removing from list!
xinit: XFree86_VT property unexpectedly has 0 items instead of 1
/home/musicbot/ts3soundboard/ts3bot: 1: /home/musicbot/ts3soundboard/ts3bot:ELF: not found
/home/musicbot/ts3soundboard/ts3bot: 2: /home/musicbot/ts3soundboard/ts3bot:@#@@▒?@▒?0Q▒t▒?▒?pp▒?p▒?P@@▒▒▒▒TT@T@DDPZPJ@PJ@P▒td,Ѕ,▒▒,▒▒D&D&▒І▒▒▒▒▒▒▒D▒▒І▒▒▒▒▒▒▒▒p
▒: not found

**Comment by Zent0** [comment]
Welche Distribution verwendest du?

**Comment by Theboss996** [comment]
Debian 32bit

**Comment by Theboss996** [comment]
Hallo wie öffne ich das wieder

**Comment by flyth** [comment]
64bit only. Steht eigentlich überall.
