### ISSUE TITLE
Send only if someone is in channel

### ISSUE THREAD

**Issue by Zent0** [flyth/ts3soundbot#154]
Wie wäre es mit einer Option, die den Bot nur dann Musik senden lässt, wenn jemand im Channel ist?
Das spart Traffic.

Whats about an option to let the bot only send music if someone is in the channel?
This will save Traffic.

**Comment by flyth** [comment]
Yup, planned and on the todo-list. However, the next couple of weeks I'll be pretty busy and unresponsive. I hope to get it done afterwards.

**Comment by flyth** [comment]
Implemented, in testing. Keep an eye open for "AloneMode".
