### ISSUE TITLE
Different users managing different instances

### ISSUE THREAD

**Issue by GoncaloRocha** [flyth/ts3soundbot#155]
Would it be possible to have a permission system inside each instance? I would like user X to have to bot Y, but not bot Z.
Thanks, great program overall. Great interface and super easy to set it up.

**Comment by mimichosting** [comment]
This is because the bot is free bot is designed to be used within a single organization. You're referring to features within the hosted version.

**Comment by flyth** [comment]
Yup, duplicate - please use the search function :)
