### ISSUE TITLE
Add .pls streaming

### ISSUE THREAD

**Issue by SephLeague** [flyth/ts3soundbot#156]
http://playerservices.streamtheworld.com/pls/CBC_R1_TOR_H.pls

like how can i stream that it dosen't work

**Comment by zoxovsky** [comment]
Just add this link

http://6093.live.streamtheworld.com:80/CBC_R1_TOR_H_SC

or

http://6093.live.streamtheworld.com:80

check :)

**Comment by SephLeague** [comment]
thanks first one worked

**Comment by am4nr** [comment]
open the file with a text editor

**Comment by flyth** [comment]
Implemented support for pls / m3u.
