### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by am4nr** [flyth/ts3soundbot#157]
I got one Musicbot working like a charm but the server only have 7gb off free space i decided to get a new vps and set it up there but everytime i get this error
![ss 2015-03-28 at 09 17 02](https://cloud.githubusercontent.com/assets/11098327/6880282/76ce2b6c-d52b-11e4-8256-978b35150947.png)

I am using Ubuntu 14.04 amd64 minimal

**Comment by nrauschcom** [comment]
Which command did you use to start the bot?

**Comment by am4nr** [comment]
screen xinit /opt/ts3soundboard/ts3bot -- /usr/bin/Xvfb :1 -screen 0 800x600x16 -ac

**Comment by nrauschcom** [comment]
Please try the following:
`screen "xinit /opt/ts3soundboard/ts3bot -- /usr/bin/Xvfb :1 -screen 0 800x600x16 -ac"`

**Comment by am4nr** [comment]
canno exec screen

**Comment by nrauschcom** [comment]
Just try the `xinit /opt/ts3soundboard/ts3bot -- /usr/bin/Xvfb :1 -screen 0 800x600x16 -ac` without calling screen.

**Comment by am4nr** [comment]
same error

**Comment by nrauschcom** [comment]
Are you sure you have all dependencies - named in wiki - installed?

**Comment by am4nr** [comment]
yes

**Comment by flyth** [comment]
Make sure permissions are correct:
`chmod 0755 /opt/ts3soundboard/ts3bot`

**Comment by am4nr** [comment]
same error and the permissions are correct

**Comment by flyth** [comment]
Error is still `ELF: not found`? And you're sure it's 64bit and the file is not corrupt? What does `ldd /opt/ts3soundboard/ts3bot` say?

**Comment by am4nr** [comment]
not a dynamic exectuable

**Comment by flyth** [comment]
What about `uname -a`?

**Comment by am4nr** [comment]
![ss 2015-03-28 at 04 56 50](https://cloud.githubusercontent.com/assets/11098327/6881705/768bdc9a-d56b-11e4-84e2-eb986bf52b14.png)

**Comment by flyth** [comment]
That's not 64bit.

**Comment by am4nr** [comment]
Well fuck, clicked the wrong button at the installation of the vps sry
i'm going to install ubuntu 64 and try it again
