### ISSUE TITLE
Wie benutze ich TTS ?

### ISSUE THREAD

**Issue by ElevenZz** [flyth/ts3soundbot#159]
Hallo,

kann mir jemand eine genaue anleitung geben wie dieses TTS funktioniert ?

**Comment by nrauschcom** [comment]
In den Einstellungen fügst du eine TTS-API ein, wie zum Beispiel 
`http://translate.google.com/translate_tts?tl=de&q=__TEXT`

Dann kann TTS im TeamSpeak-Chat via `!say <Text>` genutzt werden.

**Comment by ElevenZz** [comment]
danke
