### ISSUE TITLE
[Help] I moved the bot and now i have a problem

### ISSUE THREAD

**Issue by Niggolo** [flyth/ts3soundbot#162]
I moved the bot from one VPS to a Dedicated Server (i already did this many time) but now i got a problem and i dont undestand what it is, because the server startup and it connect/reproduce music but im unable to open the webpage: the mydomain.com:8087 is not showing up but it download a file

Logs: http://pastebin.com/BKj8PsVM
this is the error i get: 2015/04/01 14:05:35 Error: Index-File could not be served. open static/index.html: no such file or directory

**Comment by flyth** [comment]
I should probably hide the settings again. Please do **NOT** set
`Debug = true`
in your config.ini. Set it to
`Debug = false`
again, which is the default value.

**Comment by Niggolo** [comment]
o_O i didnt set it to TRUE....
but now it look ok...

**Comment by nrauschcom** [comment]
Just off-topic:
You moved the bot to a dedicated server, accessible through the WWW, so please don't run it as root.
This is a extremely big security issue.
