### ISSUE TITLE
Crashing when playing empty playlist in random mode

### ISSUE THREAD

**Issue by nrauschcom** [flyth/ts3soundbot#163]
The whole program crashes, if you try to use "!playlist" with a empty playlist and random play.
Error was something like "Error in random()", i'm pretty sure you're trying to create a random integer between zero and zero?
Sure, it's no usecase trying to play an empty playlist, but the program crashes and I have to ssh again to restart it :( :P

Just a bug report, priority near zero.

No need to fix this if you recreate random play (like we expect it to be :D) in next months

**Comment by flyth** [comment]
Thank you very much :) Just fixed it, will be deployed with the next version. And yup, better randomness is coming in a few weeks.

**Comment by flyth** [comment]
If someone really needs the fixed version before the next push: [Download for Linux 64bit](https://frie.se/ts3bot/ts3bot-bin-0.9.120.tar.bz2)
