### ISSUE TITLE
Cannot play songs longer than 60mins

### ISSUE THREAD

**Issue by am4nr** [flyth/ts3soundbot#168]
as the title says i can't listen to songs longer than 60mins 
"Error could not playback"

**Comment by Khailz** [comment]
Are you sure it isn't the songs fault, I have plenty well over an hour and they play just fine.

**Comment by am4nr** [comment]
maybe it's an error with youtube-dl but its in my song list

**Comment by Khailz** [comment]
It's a youtube song?

**Comment by am4nr** [comment]
its downloaded from youtube

**Comment by am4nr** [comment]
but its not only with one specific song it's with all songs longer than 60mins

**Comment by BlueFreakLP** [comment]
All songs from Youtube?

**Comment by am4nr** [comment]
don't have any songs longer than 60mins not downloaded from youtube so yea

**Comment by Jisagi** [comment]
youtube-dl itself works just fine with 60+ min videos, only the bot doesn't download them.
Maybe the bot uses the '--max-filesize' parameter from yt-dl to prevent you from overflowing your harddrive, but that's just a guess.
It would be good to know which parameters are used by the bot (Readme yt-dl: https://github.com/rg3/youtube-dl/blob/master/README.md).

**Comment by flyth** [comment]
See #72
Some of the parameters are configurable but still lacking the interface. This will hopefully be fixed in the next version. If until then you really need other parameters, create a small wrapper-script and use that instead of youtube-dl directly.

**Comment by am4nr** [comment]
Thanks!
