### ISSUE TITLE
ich kann nicht mehr als 6 instantzen auf machen

### ISSUE THREAD

**Issue by World-Hosting** [flyth/ts3soundbot#169]
Hallo

und zwar brauche ich mehr als 6 instanzen ich sponsore teamspeak server und music bots

bitte sagen sie wie ich mehr als 6 instanzen machen kann 

:dancer: 

MfG

World-Hosting

**Comment by am4nr** [comment]
ist das momentane instanzlimit

**Comment by am4nr** [comment]
warte auf die host version

**Comment by World-Hosting** [comment]
okay wie lange kann das ungefär dauern und wird die was kosten

**Comment by AddBrickDevs** [comment]
Huhu @World-Hosting, wenn du ein Paar Informationen möchtest schreib mich mal an:) til.wegener@add-brick.eu :)
