### ISSUE TITLE
Youtube Download

### ISSUE THREAD

**Issue by Dino957** [flyth/ts3soundbot#170]
I've probably made a stupid mistake but I cannot seem to get youtube-dl to work. It works fine when I run the command itself in ssh but the panel says "error, youtube-dl not available". I am using TS3Soundboard 0.9.5. Thanks for the help.

**Comment by am4nr** [comment]
is the youtube-dl path in the config.ini correct?

**Comment by nrauschcom** [comment]
Please give us the content of your config.ini and the output of the command `which youtube-dl`
