### ISSUE TITLE
[Bug?] Limit to how many songs you can add to a folder at a time

### ISSUE THREAD

**Issue by Khailz** [flyth/ts3soundbot#171]
I noticed that you can only move about 100 or so songs at a time to a folder. I tested with playlists and all songs were added just fine so it seems to be just a folder issue.

**Comment by flyth** [comment]
That's more of a security precaution (that's not configurable, yet) for now. I will change that behavior / make it configurable later on.

**Comment by Khailz** [comment]
Ah, I see. I knew it was something other than a bug.
