### ISSUE TITLE
Add radio sender

### ISSUE THREAD

**Issue by manasau** [flyth/ts3soundbot#172]
Hey,

how can i add my fav radio sender to the "Radio" list ?

mfg. manasau

**Comment by nrauschcom** [comment]
Which radio channel do you want to add? :)

**Comment by manasau** [comment]
e.g. MDR SPUTNIK (http://www.sputnik.de/m3u/live.hi.m3u)

**Comment by nrauschcom** [comment]
Just add `http://c22033-l.i.core.cdn.streamfarm.net/22005mdrsputnik/live/3087mdr_sputnik/live_de_128.mp3` via the **Add URL** Button in your "All Music" panel.
You can find the "addable" URLs by downloading the .pls file of your radio of choice and opening it with a text editor (e.g. Notepad)

**Comment by manasau** [comment]
Ah, okay, hab Dank mein Bester :) Noch ne evtl. eine Idee, villeicht könnt ihr eine Art "Spotify" System mit einbauen, es gab da mal so ein Dingens fürn PI (http://www.woutervanwijk.nl/pimusicbox/). Dort kannst du in ner Config File deine Einloggdaten und die Bitrate einstellen, dann siehst du im Webinterface deine Playlist. Dann evtl. passend dazu, das wiedergeben von Spotify "URI's" übern TS Chat! :) Aber sehr gute Arbeit bis jetzt! ;)

**Comment by nrauschcom** [comment]
Das Projekt wird allein von Michael Friese gepflegt, und ich versuche nur, ihm etwas Arbeit abzunehmen, indem ich Issues beantworte wenn ich eine Ahnung davon habe. Ich habe damit nichts zu tun ;)

In den Kommentaren hat er allerdings, soweit ich mich entsinne, einmal eine Spotify Integration ausgeschlossen (ich denke, die wird auch rechtlich nicht ganz in Ordnung sein)

**Comment by manasau** [comment]
Aber ich meine warum? Ob ich nun Musik von yt spiele, oder Spotify, die Gema hat doch so oder so zu meckern... Zudem musst du ja trotzdem für einen Spotify Account zahlen, um dort was streamen zu können ^^

**Comment by nrauschcom** [comment]
Für die Musik die du von YouTube herunterlädst wird natürlich keine Haftung übernommen. Du kannst dir dort selbstverständlich lizenzfreie Musik downloaden, alles andere ist dein Problem, wenn jemand danach frägt :o

**Comment by flyth** [comment]
@nrauschcom Vielen Dank ;)

Damit ist erst mal alles gesagt. Es wird vielleicht über Umwege möglich sein, Fremdquellen einzubinden - das werde ich mir bei Zeiten mal ansehen. Eine direkte Einbindung wird es vorerst nicht geben.
