### ISSUE TITLE
More Features

### ISSUE THREAD

**Issue by streamplayz** [flyth/ts3soundbot#174]
Hallo,

ich würde es cool finden wenn man mehr Instanzen haben kann und das man eigene Radiosender in die Liste hinzufügen kann und löschen. Das daraus der Befehl !radio folgen könnte. Cool wäre auch das man Logins Zugänge nur für bestimmte Bots geben könnte.

Ich hoffe eine der Funktionen wird wirklich gemacht. Dann würde ich auch mal einem Beitrag spenden

Ps: mach weiter so ;)

Gruß
StreamPlayz

**Comment by nrauschcom** [comment]
Welchen Sender möchtest du denn hinzufügen?

**Comment by streamplayz** [comment]
ILoveRadio derzeit habe ich den in meinen Musik mit "Add URL" drin aber noch besser wäre wenn man die Sender unter Radio ändern kann und dann mit !radio <radio-sender> starten kann

**Comment by flyth** [comment]
Für die meisten Punkte gibt es bereits Issues hier. Bitte schreibt künftig in englisch, damit genau diese Tickets hier von jedem gefunden werden können (also bitte auch die Suche verwenden). Ich habe momentan super wenig Zeit und jedes Mal, wenn ich mir kurz einen Überblick verschaffen will, gibt es 10 neue Tickets mit immer wieder denselben Themen. Ohne geduldige Leute wie @nrauschcom z.B. würde das ganze hier heute schon nicht mehr zu Benutzen sein ;)
In 1-2 Wochen wird es ein Forum geben, in dem es dann leichter wird, Hilfe zu finden - auch auf deutsch.
