### ISSUE TITLE
My Bot is muted

### ISSUE THREAD

**Issue by Scrumplex** [flyth/ts3soundbot#178]
My Bot is muted

**Comment by nrauschcom** [comment]
I can't really take this ticket serious.. I think it wouldn't be bad if you unmute your bot.
Maybe the bot has no talk power for your channel or you changed the volume to 0.

Without more information, nobody can help you.

**Comment by Scrumplex** [comment]
Ich geh mal aus dass du deutsch bist: 
der bot hat talkpower. nur da wo halt dieser blaue punkt sein sollte ist halt ein lautsprecher mit nem x. rechts wenn ich auf ihn kliche sit dann auch das mikrofon mit dem x

**Comment by nrauschcom** [comment]
Ich bin deutsch, aber der Bot-Programmierer wünscht sich, dass hier englisch geschrieben wird.
Kannst mir ja mal deine Serveradresse geben.

**Comment by Scrumplex** [comment]
Der Bot läuft inzwischen nicht mehr hatte die nase voll :|

**Comment by nrauschcom** [comment]
Please close your ticket then :)
