### ISSUE TITLE
[enhancement] Select multiple file to add to Playlist

### ISSUE THREAD

**Issue by Niggolo** [flyth/ts3soundbot#18]
There is something for select multiple file and add it to playlist?

**Comment by flyth** [comment]
This will come with the next version. :)

**Comment by Niggolo** [comment]
ok thank! there is an ETA?

**Comment by flyth** [comment]
I won't ever give an ETA :) However: soon.

**Comment by flyth** [comment]
Implemented.

**Comment by Niggolo** [comment]
Oh good, update is already out? Or it is just implemented?

**Comment by flyth** [comment]
Update is rolling out. You should get a notification within the next 30 minutes or update manually.

**Comment by Niggolo** [comment]
Ok! Thank you!
