### ISSUE TITLE
Radio is playing in the webinterface but not in the client

### ISSUE THREAD

**Issue by MrJoki007** [flyth/ts3soundbot#182]
In the webinterface the bot says, that he's playing musik but in the client he doesnt
Webinterface: 
![webinterface](https://cloud.githubusercontent.com/assets/8217564/7093945/9b72f85c-dfbd-11e4-8faf-61ff08fec832.PNG)
Client: 
![client](https://cloud.githubusercontent.com/assets/8217564/7093952/a356c1de-dfbd-11e4-9ad7-599837cfaada.PNG)
In the logs theres nothing

**Comment by Khailz** [comment]
Does the Bot have talk power? Are you sure it's playing on the correct bot?

**Comment by MrJoki007** [comment]
Yes

**Comment by thetruestarr1337** [comment]
I have the same Problem. Windows Server 2012. Nothing in Logs. Talk power granted.

**Comment by flyth** [comment]
Hopefully fixed in the new version. Please re-open if that's not the case.
