### ISSUE TITLE
[Bug + Enhancement] Moving Files / Search Feature

### ISSUE THREAD

**Issue by DurtyFree** [flyth/ts3soundbot#183]
Heya,
just noticed that if you try to move a couple of files in bulk mode (by selecting those which you want to move into another folder and dragging them then) the file list doesn't update after moving.
First I thought it wouldn't work at all but then I saw they got moved, only the view didn't  update.

Now to my feature request, I would like to have the ability to search including all sub folders (Maybe some options or advanced searching?)

Well done soundbot btw, keep up the good work :)

**Comment by Raphouphe** [comment]
Agree with the bug

This search feature is planned for the next release

**Comment by flyth** [comment]
Fixed / implemented in the beta releases. When you hit return after entering a searchterm, results from all subfolders will be shown.
