### ISSUE TITLE
Radio stop after a few hours

### ISSUE THREAD

**Issue by manasau** [flyth/ts3soundbot#184]
Hallo,

bei mir hört alle paar stunden, werden so 4-6h sein, das Radio einfach so auf zu spielen?
Hat dort evtl. jemand eine Lösung bzw Idee, woran das liegen könnte?
Läuft das Radio denn bei euch durch?

MfG. M.

**Comment by fipso** [comment]
Ich hab genau das selbe Problem.

**Comment by Michigras** [comment]
Liegt vielleicht auch am Radiostream. Habe TechnobaseFM seit über vier Tagen laufen. Die Anzeige sagt 20:13 Stunden, glaube aber, die kennt keine Tage und fängt dann wieder bei 0 an. Neugestartet habe ich den Stream auf jeden Fall nicht.

**Comment by manasau** [comment]
Fängt leider nicht wieder an... Stoppt dann jetzt anscheinend noch immer erst bei fast glatt 8h... Evtl einfach ein button, der, wenn aktiviert, den Stream immer neu lädt wenn nichts mehr ankommt ?

**Comment by flyth** [comment]
Das liegt an unsauberen Disconnects mancher Stream-Anbieter. In der kommenden Version wird es Reconnect-Versuche in solchen Fällen geben.

**Comment by flyth** [comment]
Ist jetzt hoffentlich besser.
