### ISSUE TITLE
Passwort nicht änderbar!

### ISSUE THREAD

**Issue by SaroxDE** [flyth/ts3soundbot#186]
Hallo,
ich kann das Passwort des Admin Accounts nicht mehr ändern.
Wenn ich auf save drücke, lädt die Seite zuerst sehr lange und dann passiert gar nichts mehr.

Habe es auch schon mit einer Neuinstallation versucht.

MfG

**Comment by am4nr** [comment]
ist ein fehler in der momentanen version, das habe ich auch und bei meinem neu installierten musikbot kann ich keine einstellungen vornehmen

**Comment by nrauschcom** [comment]
Yep, matches the bug report #158

**Comment by BlueFreakLP** [comment]
fixed
