### ISSUE TITLE
Integrate audio stream for youtube videos

### ISSUE THREAD

**Issue by robotrono** [flyth/ts3soundbot#187]
Is possible integrate mps-youtube? This is a terminal player for stream youtube videos. 

https://github.com/np1/mps-youtube

**Comment by nrauschcom** [comment]
@flyth told us, that he will probably work on a way to include other sources manually, but a direct integration is very unlikely, I think. You have youtube-dl, so why you need to stream music?

**Comment by robotrono** [comment]
Because I have a little vps, I can't store much.

Sorry for my English.

**Comment by flyth** [comment]
Integration of mps-youtube cannot happen since it doesn't have an API or such. However, the download-feature will soon be changed so that videos don't get stored all the time if you don't want them to.
