### ISSUE TITLE
[Issue] Bot doesn't say the same Track

### ISSUE THREAD

**Issue by UnwishingMoon** [flyth/ts3soundbot#190]
When I play a track on YouTube, the bot say the name, but if I stop and I re-start the same track the bot doesn't say the name of the track.

Sorry if there is another Issue like this...

GoodBye

**Comment by Raphouphe** [comment]
Can you give an example please?

**Comment by BlueFreakLP** [comment]
He mean if the stop the track and play it again, there is no announcement in the chat.

**Comment by UnwishingMoon** [comment]
If I stop che song, I shutdown the bot (exit from ts) and rejoin and play the same song from chat or web commands he doesn't say the same track
