### ISSUE TITLE
Updater Issue

### ISSUE THREAD

**Issue by yolomaker** [flyth/ts3soundbot#191]
_____ ___ _______                   _ _                      _
 |_   _/ __|__ / __| ___ _  _ _ _  __| | |__  ___  __ _ _ _ __| |
   | | \__ \|_ \__ \/ _ \ || | ' \/ _` | '_ \/ _ \/ _` | '_/ _` |
   |_| |___/___/___/\___/\_,_|_||_\__,_|_.__/\___/\__,_|_| \__,_|

               (C) 2013-2015 Michael Friese. All rights reserved.

2015/04/18 13:26:21 UPDATER invalid character '<' looking for beginning of value

do i need to force update it from the package 0.9.5?

or is this a know issue allready solved did`nt see anythink related to this error

maybe you can display the current version running on the web-side or when updating to latest version

**Comment by flyth** [comment]
Sorry, for the inconvenience - someone with an obviously huge interest to prevent you guys from using/downloading the bot is currently attacking the platform. I'm migrating some things right now and either everything will be back online later today or I will provide a more recent installation package.

**Comment by flyth** [comment]
Should work again. :)
