### ISSUE TITLE
XOpenDisplay failed

### ISSUE THREAD

**Issue by konradmm** [flyth/ts3soundbot#192]
18/04/2015 13:36:23 ***************************************
18/04/2015 13:36:23 *** XOpenDisplay failed (:1.0)

*** x11vnc was unable to open the X DISPLAY: ":1.0", it cannot continue.
*** There may be "Xlib:" error messages above with details about the failure.

Some tips and guidelines:

////////// I DELETED THIS PART SINCE ITS NOT IMPORTANT ///////////////

2015/04/18 13:36:23 RadioStation data loaded
2015/04/18 13:36:23 eaffa8a6 ab858961 INFO   TSClient quit.
2015/04/18 13:36:24 Imported radio stations
2015/04/18 13:36:28 eaffa8a6 ab858961 WARN   Could not request shutdown

Obviously did all the instructions from the install notes...
This is what happens when i use ./ts3bot

WHen i use install notes' command:

XXX@s3:~/ts3soundboard$ xinit ts3bot -- /usr/bin/Xvfb :1 -screen 0 800x600x16 -ac

xinit: XFree86_VT property unexpectedly has 0 items instead of 1
xterm: No absolute path found for shell: ts3bot
xinit: connection to X server lost

I rly have no idea what else i can do...

**Comment by flyth** [comment]
use
`xinit ./ts3bot -- /usr/bin/Xvfb :1 -screen 0 800x600x16 -ac`

You're missing the ./ in front of ts3bot.

**Comment by konradmm** [comment]
ok that really helped, but any idea how can i find out my web admin/password ? xD too far in history cant see it anymore

**Comment by flyth** [comment]
admin / foobar

**Comment by konradmm** [comment]
Great mate, really appreciate help with first one ;)
User is working as well ;)

Thanks!
