### ISSUE TITLE
error, youtube-dl not available

### ISSUE THREAD

**Issue by konradmm** [flyth/ts3soundbot#193]
Weird error, tried searching for similar tickets but nothing found which would be my problem.

Config.ini:
TS3Path = "/home/XXXXX/ts3soundboard/TeamSpeak3-Client-linux_amd64/ts3client_linux_amd64"
ListenHost = "0.0.0.0"
DataDir = ""
ListenPort = 8087
LocalPlayback = false
SecretKey = [172, 180, 60, 195, 150, 183, 179, 236, 74, 251, 197, 111, 126, 232, 9, 168, 88, 80, 197, 124, 105, 121, 24, 53, 16, 188, 45, 13, 91, 86, 83, 254]
Debug = false
LogLevel = 3
EnableProfiler = false
YoutubeDLPath = "/home/XXXXX/ts3soundboard/data/yt/"
EnableDebugConsole = false
UploadLimit = 83886080
RunAsUser = 0
RunAsGroup = 0
InstanceActionLimit = 6

Obviously created new folder named 'yt' in ts3soundboard/data/...

Just have no idea what i need to change to make it work...

edit// not sure about "LocalPlayback"...

**Comment by nrauschcom** [comment]
You have to install youtube-dl, and then you should insert the path to your youtube-dl script in this config var.
How to install youtube-dl: http://rg3.github.io/youtube-dl/download.html

**Comment by konradmm** [comment]
Wow great!
Actually i didnt think i need external database for that, believed it was implemented ;p

Anyway, to not waste the ticket so fast...
What are the paths that every upload is saved in ?

**Comment by nrauschcom** [comment]
The up- and downloads aren't stored as normal files. There's no way for you to use them right now.

**Comment by konradmm** [comment]
But they are stored somewhere.
Is it possible so i can change the path?
What i mean is im not using the same VPS for storing all files and i want BOT to communicate with lan drive to access these files, but first i need to know the path and/or where i can change that path ;]

**Comment by nrauschcom** [comment]
I'm pretty sure they're stored in ./data. I think you can change this behaviour by changing "DataDir" in the config file.
