### ISSUE TITLE
A few new commands & features

### ISSUE THREAD

**Issue by Bielecki** [flyth/ts3soundbot#194]
Hello! I have an idea for a couple new commands to bot :)
!play / !start - plays playback after !stop
!stick - toggles Stick to Channel (to the present channel)
!now / !nowplaying - displays now played song. Could be used whenever Announce Tracks is enabled or disabled.  (requires no permission)
!help - displays help or all commands (requires no permission)
!motd - display Message Of The Day previously set by user (additionally it could be able to set "When someone joins channel with bot send motd on channel / private message - ON / OFF") (requires no permission)
!follow / !followme / !love - toggles bot following user 
!announce - toggles announcing tracks
!list [page] - lists available tracks (limit to 5/10/20/30 track to page) (toggle permission require)
!track [track ID] - play track with ID [track ID]

That's it for now :) important for me is !stick, !play, and !nowplaying :)
Have a nice day
Bielecki

Update: There could be a feature, that when channel where bot is is empty for [seconds], changes channel to his default channel.
Update2: Can there be a separate user permissions / user accounts between instantions? I've created bot for my friend, and I want to allow him to log in on page and manage his instance, but prohibit to mess with my instance.

**Comment by DurtyFree** [comment]
Love the !follow idea!:)

**Comment by flyth** [comment]
Follow is available as script soon.
Many other commands can be implemented with scripts as well.
