### ISSUE TITLE
"Limit exceeded" (max. possible number of instances is 6)

### ISSUE THREAD

**Issue by buschtoens** [flyth/ts3soundbot#198]
This isn't really a bug, as I am pretty sure that this behaviour was programmed with intent, but I'd like to know why. The only reason that comes to mind is a possible future licensing system?

If not, is there a way to increase the limit or circumvent it at all?

**Comment by buschtoens** [comment]
#164

**Comment by buschtoens** [comment]
Still interested in an answer though.

**Comment by buschtoens** [comment]
After updating and restarting the config now has this line:

```
InstanceActionLimit = 6
```

Use it to tweak the limit.

**Comment by buschtoens** [comment]
Actually no. This line doesn't seem to have any effect.

**Comment by flyth** [comment]
Your assumption was correct: this could be a setting that demands a license (since 6 bots is pretty much actually for non-commercial usage). I'm not yet sure about how this will be handled, though. There's also my blog where I go into detail a bit more - if you care.
