### ISSUE TITLE
Can't open the ts3bot file

### ISSUE THREAD

**Issue by DeeJayBro** [flyth/ts3soundbot#199]
When i type ./ts3bot -update it says:
 -bash: ./ts3bot: No such file or directory

ls -al:
-rw-r--r--  1 root root        0 Apr 19 02:12 ???@@@??@8
drwxr-xr-x  3 root root     4096 Apr 19 01:55 .
drwxr-xr-x  3 root root     4096 Apr 19 01:42 ..
-rw-r--r--  1 root root     3093 Jan 26 06:05 README.md
drwxrwxr-x 13 root root     4096 Aug  4  2014 TeamSpeak3-Client-linux_amd64
-rwxr-xr-x  1 root root 35784109 Aug  4  2014 TeamSpeak3-Client-linux_amd64-3.0.16.run
-rw-r--r--  1 root root      124 Apr 19 01:54 config.ini
-rwxr-xr-x  1 root root 10910656 Jan 22 07:06 libavcodec.so.56
-rwxr-xr-x  1 root root  1843856 Jan 22 07:06 libavformat.so.56
-rwxr-xr-x  1 root root   311752 Jan 22 07:06 libavutil.so.54
-rwxr-xr-x  1 root root   317176 Mar  7 15:51 libsoundbot_plugin.so
-rwxr-xr-x  1 root root   107992 Jan 22 07:06 libswresample.so.1
-rwxr-xr-x  1 root root  9611520 Mar  7 15:51 ts3bot

When i want to start it this error appears:
xinit: XFree86_VT property unexpectedly has 0 items instead of 1
/opt/ts3soundboard/ts3bot: 1: /opt/ts3soundboard/ts3bot:ELF: not found
/opt/ts3soundboard/ts3bot: 1: /opt/ts3soundboard/ts3bot: Syntax error: "&" unexpected
xinit: connection to X server lost

waiting for X server to shut down

**Comment by flyth** [comment]
The bot is 64bit only. You're probably using a 32bit OS, right?

**Comment by DeeJayBro** [comment]
Yes ok s i cant use the bot

**Comment by flyth** [comment]
Yup, sorry.
