### ISSUE TITLE
Updater problem

### ISSUE THREAD

**Issue by Finch29** [flyth/ts3soundbot#200]
hello i have this error : 
UPDATER Get https://frie.se/ts3bot/manifest.json: x509: failed to load system roots and no roots provided
When i'm go with firefox or explorer on " https://frie.se/ts3bot/manifest.json " i may look the file but when i do " wget https://frie.se/ts3bot/manifest.json " on my server to test, i recieve this : " GnuTLS: A TLS fatal alert has been received. Incapable d'établir une connexion SSL. " 

Sorry for my bad english ( i'm french ) & thx for your music bot ! ;)

**Comment by flyth** [comment]
Which distribution are you using?

**Comment by Finch29** [comment]
Debian 7.8

**Comment by flyth** [comment]
Please try `apt-get install ca-certificates`

**Comment by Finch29** [comment]
it works nice ! thx a lot ;)
