### ISSUE TITLE
[Enhancement] Custom message when ignore message is active

### ISSUE THREAD

**Issue by Khailz** [flyth/ts3soundbot#202]
Some people don't understand that the bot isn't working because it is currently ignoring chat. I think a custom or fixed message that tells the user in private chat or channel chat would help people know why their commands aren't working.

**Comment by flyth** [comment]
The bot will tell the user in the next version that it's now allowed to listen to commands in such cases :) Thanks!

**Comment by Khailz** [comment]
No problem always glad to help :D

**Comment by flyth** [comment]
Implemented.
