### ISSUE TITLE
Sound Distortion / Seltsamer Sound

### ISSUE THREAD

**Issue by OggerMC** [flyth/ts3soundbot#205]
Hello, i have really bad Sound Distortion when playing MP3's with the sound bot.
I use the latest versions (i used the installer) and also DLed the youtube-dl file and put the path in the config.
my system:
Win 7 64bit
Phenom II x4 955
6 gb Ram

**Comment by flyth** [comment]
Sorry for the late answer: try to increase the process priority via the task-manager, that might help.

**Comment by BlueFreakLP** [comment]
Like flyth said, it looks like an performance problem of your hardware.
