### ISSUE TITLE
Value on instances

### ISSUE THREAD

**Issue by MiniMinerLPs** [flyth/ts3soundbot#206]
Hello,

how can i change the value of instances?

**Comment by nrauschcom** [comment]
What's the "value" of an instance..?

**Comment by MiniMinerLPs** [comment]
Sorry my english isn't very well... i can only add 5 instances... how can I add more?

**Comment by nrauschcom** [comment]
That's not possible at the moment.

Also, this is a duplicate of #198.
Read there for more information.

**Comment by flyth** [comment]
Note to self: create a FAQ page **really** soon.

**Comment by MiniMinerLPs** [comment]
xD I installed a second music bot ^^

**Comment by MiniMinerLPs** [comment]
on Port :8088 :)
