### ISSUE TITLE
Radio Bot

### ISSUE THREAD

**Issue by MiniMinerLPs** [flyth/ts3soundbot#207]
Hello,

i have another issue! :D
I can upload my radio file. (.m3u) but cannot play it. (Donwloadlink: http://www.iloveradio.de/listen.m3u )
Can you fix this?

**Comment by nrauschcom** [comment]
Just add `http://stream02.iloveradio.de/iloveradio1.mp3` via the "Add URL" Button.
Please search the issues. This one is a duplicate of #172.

**Comment by MiniMinerLPs** [comment]
Oh ich hätte auch Deutsch schreiben können? ._. Sorry...

**Comment by nrauschcom** [comment]
You should not.

**Comment by CrAazZyMaN21** [comment]
Better Idea go to Radio and search for iloveradio!
