### ISSUE TITLE
Download YouTube playlists?

### ISSUE THREAD

**Issue by Briefmarke** [flyth/ts3soundbot#208]
Hello, can i download a YouTube Playlist by an link?

**Comment by flyth** [comment]
Nope, that's not yet possible, sorry.

**Comment by P-Kito** [comment]
Issues are not for questions. Make sure you use the correct way for grabbing your information.

**Comment by JBou** [comment]
Could this feature please be added? I would also like to see support for Soundcloud playlists (right now it only downloads the first song in the playlist).

**Comment by BlueFreakLP** [comment]
@flyth  said already "Nope, that's not yet possible, sorry."

**Comment by JBou** [comment]
Yeah, I know. I've read the comments. It was only an additional feature request.
