### ISSUE TITLE
Announce songs with tts

### ISSUE THREAD

**Issue by DeeJayBro** [flyth/ts3soundbot#209]
Can I announce songs with Text to Speech?

**Comment by nrauschcom** [comment]
That's not possible by default:

**But here's a little hack for you:**

1. Create a user account with your bot as connected identity.
2. Change your now playing string to "`!say Now playing %s`" or something like this
3. Have fun ;)

**Comment by DeeJayBro** [comment]
thx 
But all users can see that the user write this in the channel chat

**Comment by nrauschcom** [comment]
Whats the problem with this?

**Comment by flyth** [comment]
@nrauschcom haha, nice one :+1:

**Comment by DeeJayBro** [comment]
Its not a problem but I think it would be better if the user doesn't  have to read the message !say Now playing

**Comment by CrAazZyMaN21** [comment]
Better idea announce the song title by rename a channel with id 3 or so. So everyone on the Teamspeak can see it and join the channel if it's a good song.

**Comment by DeeJayBro** [comment]
And how can i rename the server when the song change?

**Comment by CrAazZyMaN21** [comment]
Flyth need to do this with teamspeak query via php

**Comment by nrauschcom** [comment]
Sorry, but the bot is not using any PHP.
There are other ways to achieve this, but I don't know if it is his intention to do so.

In my opinion, renaming a channel to announce a track seems not really intuitive.

**Comment by DeeJayBro** [comment]
Do you have a better idea

**Comment by CrAazZyMaN21** [comment]
No only PHP or JTS3 Server Mod

**Comment by Raphouphe** [comment]
I will add some details :)
In the next Linux (and I think Windows) version, there will be a powerful script-feature which will allow doing this.

**Comment by flyth** [comment]
Yup, this can be achieved by scripting now.
