### ISSUE TITLE
Sicherheitsstufe erhöhen

### ISSUE THREAD

**Issue by Laaw** [flyth/ts3soundbot#214]
Gibt es eine möglichkeit via VNC auf den Musikbot zu connecten? Wenn ich über /settings/debug drauf gehe bekomme ich nur ein weißes Feld.
Und wie kann ich die Sicherheitsstufe von der Identiät erhöhen?

**Comment by flyth** [comment]
Einfach lokal bei dir auf dem Rechner eine Identität generieren und diese dann aus der Identitätsdatei (kann man exportieren) in den Bot-Einstellungen einfügen. VNC funktioniert momentan nicht ohne Weiteres.

**Comment by Laaw** [comment]
Wie fügt man die auf den Linux Server?

**Comment by flyth** [comment]
Wie ich schon sagte: in den Bot-Einstellungen. Also im Web-Interface.
