### ISSUE TITLE
Special Sign Support

### ISSUE THREAD

**Issue by CrAazZyMaN21** [flyth/ts3soundbot#215]
At this Moment it is not possible to set a password with -/:;()€&@".,?!' and co. Is it possible to get this enabled?

**Comment by flyth** [comment]
I just used `-/:;()€&@".,?!'`as the password for a user and it worked fine. :)
Why do you think it wouldn't work?

**Comment by CrAazZyMaN21** [comment]
Last time it doesn't work. Sry
