### ISSUE TITLE
[Question] Update?

### ISSUE THREAD

**Issue by mauzao9** [flyth/ts3soundbot#216]
Hello there.

I was poking around Milestones and see they are being released to new versions, etc.. But a new release is never done.

When are you planning to make a release? I believe the changelog will be already big. :)

**Comment by flyth** [comment]
No ETA questions please :)

I have been on vacation for a few weeks and work on the infrastructure also takes more time than I thought, so I'm a bit behind the schedule. However, the next version is almost done and will bring you some shiny new features as well as many fixes.

**Comment by mauzao9** [comment]
Shiny features! One of ones not yet implemented is the stream videos instead of upload, i had to re-install because i could not delete 7 Thousand files at once, oh gawd.

But thanks for reply :dash:

**Comment by flyth** [comment]
o_O

Will take care of that soon :)
