### ISSUE TITLE
Instances Immediately Quit

### ISSUE THREAD

**Issue by topCyder** [flyth/ts3soundbot#217]
Hey, I searched through other issues, but couldn't find anything about this problem.

Whenever I make a new instance, it never starts. Log just says that it is immediately shutting down.

I can post the log here if needed.

Thanks!

**Comment by flyth** [comment]
Once an instance has been created, it automatically starts a TS client for a few seconds to finish setup. That is working as intended. To actually use the instance, activate it in the webinterface and configure it / start it there. Does that help?

**Comment by topCyder** [comment]
Thanks for responding! When I go to activate it, it immediately shuts off. Would you like login credentials?

**Comment by flyth** [comment]
Nope, I'd like a log with LogLevel = 10, please :)

**Comment by topCyder** [comment]
I went to enable logging, and now once I booted it, I get the following error when I try to access:
>Error: Index-File could not be served. open static/index.html: no such file or directory

**Comment by flyth** [comment]
**Don't** set `Debug = true`.

**Comment by topCyder** [comment]
Ah. My bad, sorry

**Comment by topCyder** [comment]
2015-04-27T20:10:15-04:00 Spawning instance shortly due to missing configuration file
2015-04-27T20:10:15-04:00 Starting instance ts3server://?port=9987&nickname=Test&password=&channel=&channelpassword=
2015-04-27T20:10:15-04:00 TSClient quit.
2015-04-27T20:10:20-04:00 Could not request shutdown
2015-04-27T20:10:45-04:00 Storing configuration.
2015-04-27T20:10:51-04:00 BOT-CONFIG [admin] HOST PASSWORD CHAN CHANPW ANNOUNCE ANNOUNCESTR DUCKING DUCKINGVOLUME STICKY TTSLOCALE CHATIGNSRV CHATIGNPRIV CHATIGNCHAN CC OK
2015-04-27T20:11:01-04:00 Starting instance ts3server://[IP REDACTED]?port=9987&nickname=Test&password=nopassword&channel=&channelpassword=
2015-04-27T20:11:02-04:00 TSClient quit.

**Comment by flyth** [comment]
Okay, the client doesn't even start as it seems. Are you sure you're using the 64bit version of the client and have installed all dependencies as well as entered the correct path to it in the config.ini?
Could you please run `ldd <pathtoyourclient/ts3client_linux_amd64>`?

**Comment by topCyder** [comment]
Yup. I got this; 

-bash: syntax error near unexpected token `newline'

**Comment by flyth** [comment]
When did you get this? You probably just entered something wrong there. Replace `<pathtoyourclient/ts3client_linux_amd64>` with the actual binary (which should match the TS3Path in the config.ini).

**Comment by topCyder** [comment]
Ah, yeah, I accidently hit the wrong button

nux_amd64
        linux-vdso.so.1 (0x00007ffcb17f2000)
        libQt5Core.so.5 => not found
        libQt5Gui.so.5 => not found
        libQt5Widgets.so.5 => not found
        libQt5Network.so.5 => not found
        libQt5Sql.so.5 => not found
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fab6a40b000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fab6a1f0000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fab69fe8000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fab69de3000)
        libquazip.so.1 => not found
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fab69bc6000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fab698c4000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fab6951b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fab6a63d000)

**Comment by flyth** [comment]
Okay, looks normal so far. Which OS are you running? And just to be sure: you set the `LogLevel = 10` for the log output above, right?

**Comment by topCyder** [comment]
Yup, log level 10. I am on Debian 8.0 64bit

**Comment by flyth** [comment]
And you also installed libglib2.0-0?

**Comment by topCyder** [comment]
Yup

**Comment by flyth** [comment]
Then I have no clue. It's probably still a missing dependency or an issue with privileges.

You could try a
`xinit <pathto/ts3client_runscript.sh> -- /usr/bin/Xvfb :1 -screen 0 800x600x16 -ac`
and paste its output. Make sure you're using the _runscript-file this time.

**Comment by funkenstrahlen** [comment]
Experiencing the exact same bug here.
