### ISSUE TITLE
Help with YouTube Download

### ISSUE THREAD

**Issue by DarkAlex97** [flyth/ts3soundbot#218]
i'm sorry for the noob question but.. i have downloaded youtube-dl and i put its path on config.ini of TS3 Soundboard bot. Are there other steps? When i start the bot i can see "youtube-dl version compatible, support enabled" But when i try to play a track from a youtube link it says "Could Not Playback"

**Comment by flyth** [comment]
Go to the upload page and use the download function there (sorry, I just realized that's confusing).

**Comment by DarkAlex97** [comment]
When i try to download from a link it says "Could not import" =\

**Comment by flyth** [comment]
Are you using the windows version? That one has a bug regarding the youtube-dl functionality in the currently available public version.

**Comment by DarkAlex97** [comment]
I'm using the 0.9.7

**Comment by p4wlik** [comment]
error, could not import

That's what I'm getting after trying to add song from youtube. Song is downloaded but is not added to library...
Any fix for that? Windows platform.

**Comment by flyth** [comment]
I need to fix a few other things and will then release the windows update as well which fixes this.

**Comment by DCha0tiC** [comment]
Hi,if someone could help i will appreciate, i'm trying to "Exec or install" the youtube-dl.exe but everytime that i run the app it says : "the application has failed to start because its side-by-side configuration is incorrect". I installed Python 3.3 but don't know what is happening.

**Comment by DCha0tiC** [comment]
Hi there,i'm having trouble to install youtube-dl.exe because when i try to install it,it just flashes a prompt screen and don't do anything more,it's installed? I would like to know.

**Comment by gamefanpage** [comment]
Hello just wanna report that one also
i'm using linux version (sinusbot-0.9.8.tar.bz2)
and youtube can't be imported

**Comment by Khailz** [comment]
@gamefanpage Youtube-dl works fine for me, do you have the latest version installed?

**Comment by gamefanpage** [comment]
i'm using linux version (sinusbot-0.9.8.tar.bz2)
and it doesnt work
also i didn't had old version so it's fresh install (maybe the fact if u install old one then upgrate it can fix it ? )

**Comment by Khailz** [comment]
It's probably you're version of youtube-dl, how did you install it? With apt-get install?

**Comment by gamefanpage** [comment]
something i forgot install ><
so i just run yum install youtube-dl
then add a folder for it and edit config

next when i restart the ts3sounbot
here whave i receive as error
(the folder has permission but can't find the youtube-dl maybe i miss something )
fork/exec /opt/ts3soundboard/youtube: permission denied youtube-dl not found

**Comment by Khailz** [comment]
Follow these instructions instead https://github.com/rg3/youtube-dl/#installation

**Comment by gamefanpage** [comment]
Ok thank you i'll let you know when fixed :)

**Comment by gamefanpage** [comment]
ahh yeah but what i have to set on config ?

i did add : YoutubeDLPath = "/opt/ts3soundboard/youtube"

maybe there the issue ? as it can't read it

**Comment by gamefanpage** [comment]
Ok i fixed it (thank for your help)

what i did on centos ;

mkdir -p /opt/ts3soundboard/youtube
chown bot:bot /opt/ts3soundboard/youtube
sudo curl https://yt-dl.org/latest/youtube-dl -o /opt/ts3soundboard/youtube/youtube-dl
sudo chmod a+x /opt/ts3soundboard/youtube/youtube-dl

edit config file with
YoutubeDLPath = "/opt/ts3soundboard/youtube/youtube-dl"

save it and restart the bot it's work :)

thank

**Comment by Khailz** [comment]
No problem
