### ISSUE TITLE
I cant start the ts3client

### ISSUE THREAD

**Issue by Desiqnx3** [flyth/ts3soundbot#219]
Hello,
I cant start the client -.- 
I have Debian x64 and the problem is, when i start my bot comes that:

2015/04/29 15:39:25 RadioStation data loaded
2015/04/29 15:39:25 Imported radio stations
2015/04/29 15:39:30 1b5dc9fc 0cc3d651 INFO   TSClient quit.
2015/04/29 15:39:30 1b5dc9fc 6dcc97cd WARN   Could not send var command
2015/04/29 15:39:30 1b5dc9fc 6dcc97cd INFO   TSClient quit.

-.- And when i want to start my client from the panel comes TSClient  quit too 

PLS help

regards

**Comment by nrauschcom** [comment]
Please read https://frie.se/soundblog/pages/faq/ before creating an issue.

**Comment by flyth** [comment]
Also please read https://github.com/flyth/ts3soundbot/wiki/Installation---Debian-&-Ubuntu#troubleshooting and #217
