### ISSUE TITLE
TS3 Bot stutter and lag

### ISSUE THREAD

**Issue by Gh0stM1ner** [flyth/ts3soundbot#220]
When I start the TS3 bot it works for a few seconds but then it begins tu stutter and lag, it sounds like 8-bit sound :smile:  and when i type !next it plays the next song but without sound :confused: 
I don't know what I've done wrong...
The Bot runs on a Win x64 PC with 2.3Ghz and 8GB Ram (TS3 Server is also running on this machine)

**Comment by sdrl** [comment]
i have a similar which i think is the vac if i play a shoutcast stream the audio breaks up, thought it might be network lag but not so sure.

**Comment by BlueFreakLP** [comment]
I think its a windows specific problem, Linux runs fine.

**Comment by sdrl** [comment]
Thanks for reply will try it on Linux just sadly gateway commander dose not like windows.

**Comment by vazabisong** [comment]
I've this problem too but on Ubuntu 14.04 64bit with 4GB of Ram.  I really have no idea how to fix this.

**Comment by BlueFreakLP** [comment]
Currently we dont hear about any performance problems and it seems to run everywhere fine so i close the ticket now.
