### ISSUE TITLE
Stream youtube

### ISSUE THREAD

**Issue by Doc94** [flyth/ts3soundbot#222]
I knew of a good music system ts admitting links to youtube but not unloaded but it reproduced it directly ...
Which it is a payment system music (shame to be poor) what I wonder is that it is possible to do that here.

**Comment by nrauschcom** [comment]
Duplicate of #216

**Comment by flyth** [comment]
Next version will only temporarily store youtube-files. However, download before playback will still happen - there's no easy way around this. But on servers with fast access to the internet that shouldn't really be a problem.
