### ISSUE TITLE
dtmf, gateway commander and a couple of bugs

### ISSUE THREAD

**Issue by sdrl** [flyth/ts3soundbot#223]
Hi firstly great work on the plugin just what we have been looking for, Issues we have had are audio seems to break up on a stream can not put my finger on whether its a network issue or plugin struggling with processing the audio. We have been using it to provide news and alerts over our radio gateways which apart from the odd stutter has been working fine. 

Main Issues have been if playing a Music stream (shoutcast) it quite often just stops and wont start by commands and needs a reset by server. Playing a playlist like a weather alert once its played it dosn't seem to reset and allow us to play another. Just stops responding to commands and needs a reset. 

Would like to know if there is a way to use dtmf to control the play stop next track and change rooms would be really usefull.  We use the latest gateway commander would be great to be able to use this with it for control using radio.  would like a tts mayb where the bot could broadcast a message if it has one sent. great work and thanks.

**Comment by flyth** [comment]
If I understand your first issue with hanging streams - I hope to have a fix for that ready in the next version. It's in internal testing right now.

DTMF is not planned since I think the user base that'd use a feature like that is **really** small. If however you decide to write a plugin that can detect the signals, get back to me and I'll explain to you how you can trigger things on the bot.

**Comment by sdrl** [comment]
Excellent OK will look into it been looking to find a way to get broadcastify  stream into it to. For the roip users and ameture radio users i think the potential of the app and team speak hasn't been duly realised.
On 3 May 2015 22:42, flyth <notifications@github.com> wrote:If I understand your first issue with hanging streams - I hope to have a fix for that ready in the next version. It's in internal testing right now.

DTMF is not planned since I think the user base that'd use a feature like that is really small. If however you decide to write a plugin that can detect the signals, get back to me and I'll explain to you how you can trigger things on the bot.

**Comment by flyth** [comment]
I will close this for now. If there's some progress on your side, feel free to re-open.

**Comment by sdrl** [comment]
OK and thanks keep up the good work, we have a few techies who pop in and out of channel feel free to pop on and say hi. Sussex downs radio link on Zello and team speak. 
On 21 May 2015 23:10, flyth <notifications@github.com> wrote:I will close this for now. If there's some progress on your side, feel free to re-open.
