### ISSUE TITLE
TS3Client Bug?

### ISSUE THREAD

**Issue by Benjarobbi** [flyth/ts3soundbot#224]
Hello, how i can fix that?
/home/musikbot/TeamSpeak3-Client-linux_amd64/ts3client_linux_amd64: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
I used the tutorial from tscoach!

**Comment by Bielecki** [comment]
I had the same bug. Run it using flyth instruction (use xinit):
https://github.com/flyth/ts3soundbot/wiki/Installation---Debian-&-Ubuntu

**Comment by Benjarobbi** [comment]
Thanks! I've fixed IT. I installed it on a other servers and used this tut.
