### ISSUE TITLE
was ist das passwort 

### ISSUE THREAD

**Issue by nEstarra** [flyth/ts3soundbot#225]
was ist das paswwort ich kann mich da net ein logen

**Comment by thetruestarr1337** [comment]
Hast du die Anleitung jemals ganz durchgelesen ?

The default username / password is: admin / foobar


https://github.com/flyth/ts3soundbot/wiki/Installation-Windows

**Comment by nEstarra** [comment]
würte ich aber ich habe keine anleitug

**Comment by nEstarra** [comment]
aber ich komm auch net bin admin foobsr
