### ISSUE TITLE
v server

### ISSUE THREAD

**Issue by nEstarra** [flyth/ts3soundbot#226]
ich hsbe den auf mein v server  kann ich von mein ps  drauf zu greifen da ich net imer auf mein server mus

**Comment by flyth** [comment]
a) Anleitung lesen
b) FAQ lesen
c) Fragen ordentlich formulieren

**Comment by P-Kito** [comment]
Manchmal frage ich mich wie dumm manche Leute sind...

**Comment by nrauschcom** [comment]
Auch bei (zugegebenermaßen sehr) seltsamen Fragen darf man hier gerne freundlich bleiben. :)
