### ISSUE TITLE
User Add Api

### ISSUE THREAD

**Issue by wbbler** [flyth/ts3soundbot#227]
Hi,

how can i create a new user with the Api?

What i have testet:

public function AddUser($username, $password) {
        $ch = curl_init();
        curl_setopt_array($ch, array(
            CURLOPT_URL => 'http://'.$this->botHost.':'.$this->botPort.'/api/v1/bot/user/add',
            CURLOPT_RETURNTRANSFER => 1,
            CURLOPT_POSTFIELDS => json_encode(array('username' => $username, 'password' => $password)),
            CURLOPT_HTTPHEADER => array('Authorization: bearer '.$this->token)
        ));

Or isn´t there an api function for user creating?

**Comment by flyth** [comment]
There will be no support nor documentation for the internal API **right now** since I might change it without further notice. However - use your browsers' development tools and you will see exactly which call gets triggered with which parameters.

Just as a hint: it's `/api/v1/bot/users` via POST.
