### ISSUE TITLE
[Bug] Delete music

### ISSUE THREAD

**Issue by Niggolo** [flyth/ts3soundbot#23]
If i delete a music with the X button it will be removed just from the list and not the file, you can try it youself: download anything, remove it from list, redownload it, the job list say "duplicate" and im usable to download it

**Comment by flyth** [comment]
The bot de-duplicates files to save space. So when you upload a file twice, it will only use references and not store the file again. Once you remove the last reference, the file will get deleted as well (as of yesterdays update). Does that information solve the issue?

**Comment by Niggolo** [comment]
oh with new version i dont have the problem anymore :) thank you
