### ISSUE TITLE
[Request] Sorting songs by title-number

### ISSUE THREAD

**Issue by TRiechar** [flyth/ts3soundbot#230]
I have a request for a feature that should be very useful:

It would be very nice if one could sort uploaded songs by the title-number saved to the ID3-Tags or simply by the filename.
This would add the opportunity to hear an album in the right order, otherwise the user would have to sort all songs manually.

I would love to see this feature implemented in a later build.
Thanks in advance and thanks for this epic piece of software! :)

**Comment by flyth** [comment]
The new beta releases can will sort by track number if you sort by album as well.
