### ISSUE TITLE
Bot(teamspeak) will not start.

### ISSUE THREAD

**Issue by Benjarobbi** [flyth/ts3soundbot#232]
2015/05/04 12:54:14 4eda25d6 INFO   Initializing bot://4eda25d6-64d2-44f2-ab70-06bcb1dd9567
2015/05/04 12:54:14 4eda25d6 dd5e2e6c INFO   Loaded
2015/05/04 12:54:14 4eda25d6 f9843e07 INFO   Loaded
2015/05/04 12:54:14 FFmpeg/avcodec v3675236; license: LGPL version 2.1 or later; 494 codecs
2015/05/04 12:54:14 FFmpeg/avformat v3674980; license: LGPL version 2.1 or later; 139 formats
2015/05/04 12:54:14 4eda25d6 dd5e2e6c INFO   Starting instance ts3server://37.59.46.170?port=9987&nickname=Freund%20Spielt&password=&channel=&channelpassword=
2015/05/04 12:54:14 4eda25d6 f9843e07 INFO   Starting instance ts3server://37.59.46.170?port=9987&nickname=Ich%20bin%2040&password=&channel=&channelpassword=
2015/05/04 12:54:14 4eda25d6 f9843e07 INFO   TSClient quit.
2015/05/04 12:54:14 4eda25d6 dd5e2e6c INFO   TSClient quit.

The VNC desktop is:      localhost:0
PORT=5900
2015/05/04 12:54:14 RadioStation data loaded
2015/05/04 12:54:16 Imported radio stations
2015/05/04 12:54:19 4eda25d6 f9843e07 WARN   Could not request shutdown
2015/05/04 12:54:19 4eda25d6 dd5e2e6c WARN   Could not request shutdown

What i can do?

**Comment by nrauschcom** [comment]
Please read the FAQ [1].
If you don't find something useful there, please set your LogLevel [2] to 10 and report a more detailed bug.

[1] https://frie.se/soundblog/pages/faq/
[2] https://github.com/flyth/ts3soundbot/wiki/Solving-Problems---Bug-Reporting

**Comment by Benjarobbi** [comment]
Fixed.
