### ISSUE TITLE
Better music file managment

### ISSUE THREAD

**Issue by Joniator** [flyth/ts3soundbot#233]
I want to implement a FTP-Acces to the music library of the Bot.
I looked for and found the directory the files are saved. Sadly, all the Files are named with randomly numbers and without prefixes. I did not try to upload some MP3s in that, but I think it wont work, even if it would, its not nice-looking for FTP-Users.

My request: a directory where I can copy my MP3s to, maybe as main storage for every music file, so I can easily give an FTP-Access to them.

**Comment by Khailz** [comment]
Flyth said he doesn't want to turn the bot into a file share. That probably also means that music wil stay with database id's.

**Comment by Joniator** [comment]
Too bad :(
I would be happy about just uploading music too, mostly i want to upload my Music zipped and unzip it directly on the server, m

**Comment by flyth** [comment]
There might be an import feature sooner or later.
