### ISSUE TITLE
Only run in root

### ISSUE THREAD

**Issue by Joniator** [flyth/ts3soundbot#235]
If i switch with su musicbot to my user for the bot and start the bot, I got an error:

http://pastebin.com/0LfnkL0t

If I start the Bot out of my root-user with exactly the same command it works well.

http://pastebin.com/ukqRyQPx

Ubuntu 14.10

**Comment by nrauschcom** [comment]
You ran the bot as root the first time, so the database files are not writable by any other user.
You need to reinstall the bot or change file rights, if you know what you're doing in order to get the bot running as non-privileged user.

**Comment by flyth** [comment]
If you "switch" to another user, make sure the bot owns all the files so it can write to them.

`panic: attempt to write a readonly database` tells you exactly that.

**Comment by Joniator** [comment]
Thanks, now it works :)
