### ISSUE TITLE
Max. space 0 MB | Cannot upload any music

### ISSUE THREAD

**Issue by buschtoens** [flyth/ts3soundbot#236]
I feel like I am just too stupid, but it appears like I can't upload any music, as the max space is 0 MB.
Did I do something wrong or is this a bug?

**Comment by flyth** [comment]
0 actually means unlimited. Check / post your log for more information.

**Comment by buschtoens** [comment]
Every upload request is cancelled with a `413 Entity Too Large`, no matter how big the file is.

**Comment by buschtoens** [comment]
btw, the `youtube-dl` works.

**Comment by flyth** [comment]
There's a setting in the config.ini called `UploadLimit` - it's in bytes. That's the only limitation for uploads. Which browser are you using?

**Comment by buschtoens** [comment]
The config has the default `83886080` (80 mb).

I experience the same problem in Chrome and Firefox on Ubuntu. Haven't actually tried it on Windows yet, but I don't expect it to work there either.

**Comment by flyth** [comment]
Did you solve this problem somehow?

**Comment by buschtoens** [comment]
Nope. It happens on a different ubuntu system as well.

flyth <notifications@github.com> schrieb am Fr., 22. Mai 2015 00:08:

**Comment by buschtoens** [comment]
I'm currently working on dockerizing the SinusBot (and successfully did so! :tada:).

However, this problem *still* persists, even with the most recent version. Youtube-dl works, but the normal file upload doesn't.

```
2015/06/29 16:39:37 [ERROR] Could not delete file /opt/ts3soundboard/data/store/4ef7dc7e-26e4-4b44-b70e-5644f11ccb48//opt/ts3soundboard/data/tmp/4e98069ae0f3bcf9eabc64dac062149f5e181c3959806539bdf489f89ac53927
```

The used base image is Ubuntu.

**Comment by flyth** [comment]
:+1: on dockerizing it. Always planned to do that myself :)

Yes, the path looks wrong. What exactly did you do to make that error message appear?

**Comment by buschtoens** [comment]
I just uploaded a .wav (drag and drop). The error appeared in the cli. The error also happens on a debian base image.

**Comment by buschtoens** [comment]
Oh wait a sec. An small .mp3 just worked.
I'll investigate.

**Comment by buschtoens** [comment]
btw, if you're curious:

https://github.com/VeltroGaming/sinusbot
https://registry.hub.docker.com/u/veltro/sinusbot/

I'll document it later and do some more polishing. The sexiest thing in my opinion is the automatic installation of the TS3 client.

**Comment by flyth** [comment]
The next version will be even tinier :) I've completely removed the xvfb/x11 requirements.

About that automatic installation of the TS-Client (and even though it's solved nicely): I've heard that the TS guys don't like that as you're not explicitly accepting the terms & conditions. Otherwise I'd have implemented it myself as well - because the manual installation of the users cause at least 10% of the support cases :)

**Comment by buschtoens** [comment]
> I've completely removed the xvfb/x11 requirements.

Amazing news! I'm super-thrilled! :)

> About that automatic installation of the TS-Client...

Yeah, already expected that. It's really unfortunate. I'll add their (and your and the sub-components') license very visibly in the README and LICENSE.

The only other way would be implementing an installer in your web-interface, that displays their license, as there's no way to hook into the install routine of docker. It would also completely defy docker's purpose.

If you wanna use my "hack" you're welcome to do so and implement it in the web-interface! :)

**Comment by flyth** [comment]
If you want to test-drive such a version, feel free to contact me on the forums via PM.

I've thought about the solution via the web-interface as well - maybe I'll contact the TS guys when everything else is done. That'd really improve the installation.

**Comment by buschtoens** [comment]
Yeah, that will probably be for the best. Let's hope their nicer than in the forums...

You got mail. :)
