### ISSUE TITLE
Stream youtube 

### ISSUE THREAD

**Issue by nEstarra** [flyth/ts3soundbot#240]
ich habe ein windows server wenn ich Stream hochladen will kommt immer die fehlermeldung muss ich noch was frei geben oder so kann mir einer helfen 

error, youtube-dl not available

**Comment by flyth** [comment]
youtube-dl funktioniert derzeit nicht unter Windows. In der kommenden Version dann wieder und dann wird es auch im Wiki einen Eintrag zur Installation geben.

Hier im Issue-Tracker bitte nur Tickets auf Englisch einstellen, danke :)
