### ISSUE TITLE
[Request] Public "vote" page

### ISSUE THREAD

**Issue by kebre001** [flyth/ts3soundbot#241]
Since clients loves to be able to interact with stuff I would like a feature that enables a page with the current playlist where users can suggest music and vote for a song.

**Comment by DurtyFree** [comment]
Great idea :)
Or at least some way to do it your own (php api?)

**Comment by flyth** [comment]
The next version will feature a queue-system. With that activated you can easily script your own voting-page. :)

**Comment by flyth** [comment]
Queue implemented.
