### ISSUE TITLE
[Request] Reserv a bot for 1h

### ISSUE THREAD

**Issue by kebre001** [flyth/ts3soundbot#242]
A "request" mode for a instance.

What I mean is that there is a channel in the forum where "afk" bots is stored. A user can write a message to one of them and reserv the bot for 1h (example).
This will make the user the admin over that bot and that user can move it and control it.
This will maybe prevent the user from uploading music but stream music together with friends can be gold worth if its simple.

**Comment by mauzao9** [comment]
Well i'm using a system to let users of my game party channels can have their own bot instance to use, this inside the same teamspeak but it can be done manually already. I think if any automation would be a permission that lets you call one instance of the bot/or the bot itself to your channel.

**Comment by flyth** [comment]
I think this would be too complex for the core of the bot. However, you're welcome to script this behavior yourself. Using the API it shouldn't be a big problem.

**Comment by BlueFreakLP** [comment]
There will be options in the new versions to implement it by the users.
