### ISSUE TITLE
youtube-dl error

### ISSUE THREAD

**Issue by mattrick16** [flyth/ts3soundbot#243]
Hello, I know that you have said that you will not support issues pertaining to youtube-dl, but I would like to see if there is a way to resolve this.

I am attempting to download a video from YouTube, but after attempting to import it, it simple says "error" in the download queue. There is no errors in the console.

If there is anything else I can provide, please ask. Thanks!

**Comment by nrauschcom** [comment]
Currently does not work on Windows.

mattrick <notifications@github.com> schrieb am Di., 12. Mai 2015 02:54:

**Comment by mattrick16** [comment]
I'm actually running Ubuntu 15.10.

-----Original Message-----

**Comment by flyth** [comment]
Please increase the LogLevel and watch the console. The bot **has to say** that support for youtube-dl has been enabled on startup. Ubuntu 15.10 sounds pretty bleeding edge, btw. :)

**Comment by mattrick16** [comment]
Whoopsie, I meant 15.04 :P

It does say it supports youtube-dl. Here is the console:
```
mattrick@ipaddress:/var/musicbot/ts3soundboard$ xinit ./ts3bot -- /usr/bin/Xv1 -screen 0 800x600x16 -ac

xinit: XFree86_VT property unexpectedly has 0 items instead of 1
  _____ ___ _______                   _ _                      _
 |_   _/ __|__ / __| ___ _  _ _ _  __| | |__  ___  __ _ _ _ __| |
   | | \__ \|_ \__ \/ _ \ || | ' \/ _` | '_ \/ _ \/ _` | '_/ _` |
   |_| |___/___/___/\___/\_,_|_||_\__,_|_.__/\___/\__,_|_| \__,_|

               (C) 2013-2015 Michael Friese. All rights reserved.

2015/05/12 18:22:16 f5216814 INFO   Initializing bot://f5216814-6a0b-4b04-8588-1238ced9190f
2015/05/12 18:22:16 f5216814 DEBUG  Got user://4c645fd6-7532-4b67-a146-ddbb16f7a510/admin
2015/05/12 18:22:16 f5216814 DEBUG  Got file://295bb355-0d12-4432-86f6-fa73fd344dda
2015/05/12 18:22:16 f5216814 c6e6a2a7 INFO   Loaded
2015/05/12 18:22:16 FFmpeg/avcodec v3675236; license: LGPL version 2.1 or later; 494 codecs
2015/05/12 18:22:16 FFmpeg/avformat v3674980; license: LGPL version 2.1 or later; 139 formats
2015/05/12 18:22:16 youtube-dl checking...

The VNC desktop is:      localhost:0
PORT=5900
2015/05/12 18:22:16 youtube-dl version compatible, support enabled
2015/05/12 18:22:17 RadioStation data loaded
2015/05/12 18:22:17 Imported radio stations
2015/05/12 18:22:28 f5216814 DEBUG  youtube-dlquit
```

**Comment by Bielecki** [comment]
Did you have VPS on OVH? Youtube blocks OVH IPv6 addresses. If error is 500, then try use IPv4. Just create file:
/etc/youtube-dl.conf 
and type:
-4
Save it, rerun TS3 bot. It should work now.

**Comment by mattrick16** [comment]
Works now, thanks @Bielecki :)
