### ISSUE TITLE
Doesn't start anymore (Ubuntu 64bit)

### ISSUE THREAD

**Issue by am4nr** [flyth/ts3soundbot#244]
![ss 2015-05-12 at 12 02 57](https://cloud.githubusercontent.com/assets/11098327/7584609/e3cf5d94-f89e-11e4-823d-b417d08bfd72.jpg)

**Comment by flyth** [comment]
Maybe your disk is full? :)
`disk I/O error` sounds like that.

**Comment by am4nr** [comment]
Yep thanks!
