### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by fastscape** [flyth/ts3soundbot#248]
Well I'm not the best when it comes to computing but I cant figure out how to get the bot in Teamspeak. I have downloaded the bot but don't know how to set it up. I scoured all of  the website but there were no definite directions on how to get it working. It would be nice to get a link to the instructions or it be posted here.

Very excited user,
fastscape

**Comment by KuroNeko-san** [comment]
https://frie.se/soundblog/pages/installation-ubuntu-14-04/

**Comment by flyth** [comment]
Where did you download the bot from? Just so I can place a link to the documentation there as well. :)

**Comment by flyth** [comment]
Ah, and most recent version is available [here](https://github.com/flyth/ts3soundbot/wiki/Installation---Debian-&-Ubuntu).

**Comment by fastscape** [comment]
I have downloaded the bot from here. https://frie.se/ts3bot/

**Comment by flyth** [comment]
I guess this has been resolved? :)
