### ISSUE TITLE
[manual] Installation TS3SoundBoard on Centos 6.6 x86_64 VPS

### ISSUE THREAD

**Issue by KuroNeko-san** [flyth/ts3soundbot#249]
__Update system__
yum -y update

__Select locale__
vi /etc/sysconfig/i18n

```bash
LANG="en_US.UTF-8"
```

__Install Desktop and TightVNC server__

yum -y groupinstall Desktop
yum -y install tigervnc-server

vi /etc/sysconfig/vncservers

```bash
VNCSERVERS="1:root"
VNCSERVERARGS[1]="-geometry 1024x786"
```

__Set password for VNC login__
vncpasswd
__and enter password two times__

vi /root/.vnc/xstartup
```bash
#!/bin/sh
[ -r /etc/sysconfig/i18n ] && . /etc/sysconfig/i18n
export LANG
export SYSFONT
vncconfig -iconic &
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
OS=`uname -s`
if [ $OS = 'Linux' ]; then
  case "$WINDOWMANAGER" in
    *gnome*)
      if [ -e /etc/SuSE-release ]; then
        PATH=$PATH:/opt/gnome/bin
        export PATH
      fi
      ;;
  esac
fi
if [ -x /etc/X11/xinit/xinitrc ]; then
  exec /etc/X11/xinit/xinitrc
fi
if [ -f /etc/X11/xinit/xinitrc ]; then
  exec sh /etc/X11/xinit/xinitrc
fi
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
xterm -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
twm &
```
__Set TightVNC start on boot__
chkconfig vncserver on

__Because CentOS 6 have old glibc we need to compile new libstdc++.so__
__Thats really hentai, but ... we need this__
yum -y install gcc gcc-c++ cpp make zip glibc-devel glibc-devel.i686

cd /usr/src
wget http://ftp.gnu.org/gnu/gcc/gcc-4.7.4/gcc-4.7.4.tar.gz
tar xzf gcc-4.7.4.tar.gz
cd gcc-4.7.4
./contrib/download_prerequisites
cd ..
mkdir objdir
cd objdir
$PWD/../gcc-4.7.4/configure --prefix=/opt/gcc-4.7.4
make && make install

__wait ... wait ... wait ...__

mv /usr/lib64/libstdc++.so.6.0.13 /usr/lib64/libstdc++.so.6.0.13.original
cp /opt/gcc-4.7.4/lib64/libstdc++.so.6.0.17 /usr/lib64/

rm /usr/lib64/libstdc++.so.6
ln -s /usr/lib64/libstdc++.so.6.0.17 /usr/lib64/libstdc++.so.6
ln -s /usr/lib64/libstdc++.so.6.0.17 /usr/lib64/libstdc++.so.6.0.13

__Download and install TS3 and SoundBoard__
cd /opt
wget http://frie.se/ts3bot/ts3soundboardbot-0.9.5.tar.bz2
tar -xjf ts3soundboardbot-0.9.5.tar.bz2

wget http://dl.4players.de/ts/releases/3.0.16/TeamSpeak3-Client-linux_amd64-3.0.16.run
chmod 0755 TeamSpeak3-Client-linux_amd64-3.0.16.run
./TeamSpeak3-Client-linux_amd64-3.0.16.run

cp ./ts3soundboard/libsoundbot_plugin.so ./TeamSpeak3-Client-linux_amd64/plugins

vi ./ts3soundboard/config.ini
```bash
TS3Path = "/opt/TeamSpeak3-Client-linux_amd64/ts3client_linux_amd64"
```

__Update SoundBoard__

./ts3soundboard/ts3bot -update

__Autorun__

vi ./ts3soundboard/run_script
```bash
#!/bin/bash
DISPLAY=":1.0" /opt/ts3soundboard/ts3bot > /dev/null 2>&1 &
```

chmod +x ./ts3soundboard/run_script

vi /etc/rc.local
```bash
# start TS3 soundboard bot
/opt/ts3soundboard/run_script
```

**Comment by flyth** [comment]
Awesome :) Thank you very much. I will migrate that to the wiki if that's okay with you. :+1:

**Comment by KuroNeko-san** [comment]
Yes, please add this to wiki.

**Comment by Topsii** [comment]
I can confirm, this works!

Only two minor things:
1. You can't save a file in a nonexistent directory, so one should execute vncpasswd before editing xstartup.
2. tar -xjf ts3soundboardbot-0.9.5.tar.bz2 creates the folder ts3soundboard not ts3soundboardbot.

I also had to set library path for the client to work (otherwise it wouldn't find some qt libraries), so I looked at TeamSpeak3-Client-linux_amd64/ts3client_runscript.sh to do the nessecary exports.
And for me it was DISPLAY=":1" not :1.0

**Comment by KuroNeko-san** [comment]
Thanks, fixed.

**Comment by BlueFreakLP** [comment]
It works and its done =)
