### ISSUE TITLE
[enhancement] !votenext

### ISSUE THREAD

**Issue by Niggolo** [flyth/ts3soundbot#25]
Maybe a command like !votenext avaible to everyone (activable from config: enable votenext= true/false or command up to you)
Maybe after a X number of !votenext (configurable on config.ini or with command up to you) it will change music, if the bot change music his self (the music end) the cound reset to 0

Thank you :P

**Comment by flyth** [comment]
See #6.

**Comment by Niggolo** [comment]
Oh sorry didnt see it
