### ISSUE TITLE
Windows Service

### ISSUE THREAD

**Issue by Abchrisabc** [flyth/ts3soundbot#251]
I'd love it if there was a way to add the ts3soundbot as a Windows Service so that it automatically starts  when my server starts and so that I don't have to be logged in all the time.

**Comment by nrauschcom** [comment]
You can create a simple startup script which initializes the bot. You don't
have to be logged in via SSH at all.

Abchrisabc <notifications@github.com> schrieb am Do., 14. Mai 2015 21:25:
