### ISSUE TITLE
Theme Issues

### ISSUE THREAD

**Issue by Everfallen** [flyth/ts3soundbot#252]
I know this was already mentioned [here](https://github.com/flyth/ts3soundbot/issues/108), but there are other themes this is affecting as well.
Cosmo, Darkly, Flatly, and Lumen all have this issue.

You can't see the tag editor/add to playlist menu at all on Lumen. The hover values of both the text and the background of it are also set to white, making it impossible to use the menu at all as shown.

![j5tsne4](https://cloud.githubusercontent.com/assets/1348912/7667428/12d45020-fbd5-11e4-849f-19a0f169be6e.png)

Cyborg's player itself is also incredibly hard to read. The background is a very light grey with the text being white as shown below.

![akhrelh](https://cloud.githubusercontent.com/assets/1348912/7667441/a469b354-fbd5-11e4-9fd8-5ed1a0bdea73.png)

**Comment by flyth** [comment]
Will be fixed in the next version :)
Thanks for adding images, helped a lot!
