### ISSUE TITLE
PHP Info frage

### ISSUE THREAD

**Issue by RevUnix** [flyth/ts3soundbot#253]
Da die meisten hier eh Deutsch sind, frage ich einfach mal auf Deutsch ^^

Und zwar verstehe ich dieses Script nicht zu ganz:
https://github.com/flyth/ts3soundbot/wiki/Accessing-Bot-Info-via-PHP

was hat es mit dem Token auf sich?! die BotID ist mir klar aber der Token?!
Und was muss noch alles geändert werden?

**Comment by nrauschcom** [comment]
Nach dem Login am Server bekommst du ein Token zurück, mit dem du dem Server bei deinen Anfragen mitteilst, dass du dich eingeloggt hast.
Was geändert werden muss, kommt natürlich darauf an, was das Skript tun soll.

Für die vorgesehene Funktionalität musst du nur

    $bot = new Bot('127.0.0.1', 8087);
    $bot->Login('admin', 'foobar');

bearbeiten.

**Comment by RevUnix** [comment]
Okay, aber wo sehe ich den Token? :smile: steht der noch im Log?

**Comment by nrauschcom** [comment]
der token wird in der funktion `Login(name, passwort)` erzeugt. Daran musst du überhaupt nichts ändern.

**Comment by RevUnix** [comment]
Hat nun geklappt!

Nur ist die frage warum er den artist nicht abfragen kann.

Notice: Undefined index: artist in /bot.php on line 82
Trap.FM is playing Trap.FM by

Notice: Undefined index: artist in /bot.php on line 82
Q-Dance 24/7 is playing Q-dance Radio by

**Comment by nrauschcom** [comment]
Das liegt daran, dass deine Radiosender keinen Interpreten setzen, sondern nur einen Titel. Vielleicht kannst du das im Tag-Editor ändern, ansonsten musst du das PHP-Script eben leicht anpassen und den Artist einfach rausnehmen.

**Comment by RevUnix** [comment]
Doch. Die senden einen Titel mit, das ist ja dass komische.
```
￼<22:53:14> "Q-Dance 24/7": Now playing: The Anarchist - We Connect
￼<22:57:22> "Q-Dance 24/7": Now playing: Abyss & Judge - Rockit
```

Ich will ja einen Artist anzeigen lassen, sonst bräuchte ich das Script ja nicht ^^

**Comment by flyth** [comment]
Ich fände es trotzdem toll, wenn wir hier bei Englisch bleiben könnten, damit nicht viele Themen gleich mehrfach durchgesprochen werden müssen. Steht auch so in den FAQ.

Wie auch immer: in deinem Fall musst du die Felder `tempArtist` und `tempTitle` lesen.

**Comment by RevUnix** [comment]
Ja, so kann ich es aber besser erklären ;) 
Gibt es noch eine Möglichkeit irgendwie beides anzeigen zu lassen?

**Comment by nrauschcom** [comment]
printf("%s is playing %s by %s on radio station %s\n", $instances[$i]['nick'], $info['currentTrack']['tempTitle'], $info['currentTrack']['tempArtist'], $info['currentTrack']['title']);

**Comment by RevUnix** [comment]
Puuh... Es geht aber das tollste ist das nicht. Daran solltet ihr echt noch mal arbeiten. Kann man die Abfragen nicht irgendwie anders machen? So wie es jetzt ist, ist es Mist. :/

**Comment by nrauschcom** [comment]
Was genau ist daran denn das Problem..?

**Comment by RevUnix** [comment]
also wenn ich eine MP3 abspiele, zeigt er den Interpreten nicht an, wenn ich noch ein %s dran hänge schon.

Nun ist da das Problem wenn ich zb. Technobase höre das dieser dann 2x mal angezeigt wird, also richtig dämlich.

Hab schon rum probiert... wie ich es mache ist es noch blöder.
Gibt es keine andere Lösung? Und kann man die API irgendwo sehen?!

**Comment by nrauschcom** [comment]
Nein, die API zu veröffentlichen während noch alles unter Bearbeitung ist, wäre vermutlich eine schlechte Idee.
Du kannst selbstverständlich eine Fallunterscheidung machen und bspw. überprüfen ob 2 mal derselbe Interpret drin steht und jeweils etwas anderes ausgeben.

**Comment by flyth** [comment]
Magst du dich bitte mal über Programmierung und Scripting im Allgemeinen informieren? Das hier ist nun wirklich nicht der richtige Ort dafür. Der Bot gibt dir alle Informationen - was du damit machst / wie du diese aufbereitest, ist deine Sache und nicht die des Bots.
