### ISSUE TITLE
how does the music get saved?!

### ISSUE THREAD

**Issue by Koetjh** [flyth/ts3soundbot#254]
Good day great coder,

How does the bot save the music data?! where does it place the created playlists with there inherited songs?! 

I'm also asking this for copyright reasons. since i run the bot on an Virtual Private Server. they have strict rules on copyright. Would this mean i can only use the stream function?! 

Thanks in advance,

**Comment by flyth** [comment]
See #87

You won't get any legal advice here.
Files are stored unencrypted, if that's your question - however: as a bot **user** (not admin) you can never download anything.

**Comment by Koetjh** [comment]
"however: as a bot user (not admin) you can never download anything."

thank so far, but could you elaborate?!

**Comment by flyth** [comment]
A user has no access to the underlying files via the bot software itself.

**Comment by Koetjh** [comment]
ah ok, now i get it. Thanks alot!

**Comment by Koetjh** [comment]
is there any chance that you guys might add encryption?! or isn't that in the scope of the your project.

**Comment by flyth** [comment]
Nope, I don't think so. I don't want to encourage illegal things in any way.

**Comment by Koetjh** [comment]
"Nope, I don't think so. I don't want to encourage illegal things in any way."

ok, i can understand that. thank you
