### ISSUE TITLE
./ts3bot: Datei oder Verzechnis nicht gefunden

### ISSUE THREAD

**Issue by P-Kito** [flyth/ts3soundbot#255]
root@********:/opt/ts3soundboard# ./ts3bot -update
-bash: ./ts3bot: Datei oder Verzeichnis nicht gefunden
root@*********:/opt/ts3soundboard#

Sowohl als User "bot" als auch user "root".

Kennt jemand den Fehler?

[ENGLISH]
File or directory not found for ./ts3bot
Tried as user "bot" or "root".

Does anyone know a solution?

**Comment by nrauschcom** [comment]
Are you sure you are using a 64-bit OS?

**Comment by P-Kito** [comment]
:+1: 

Is it portable to 32bit?

**Comment by P-Kito** [comment]
Short answer:
http://superuser.com/questions/111975/can-i-run-64-bit-executables-on-a-32-bit-linux

**Comment by nrauschcom** [comment]
> **Is there a version for 32bit Windows / Linux?**
 > 
 > No, there isn’t and there won’t be. The main reason for this is that the audience is too small as to support yet another version.`
 > - FAQ at https://frie.se/soundblog/pages/faq/

But you said you are using 64bit?

**Comment by P-Kito** [comment]
All good, I am using 32-bit. 
No wonder it does not work for me :>

Not gonna upgrade the system for the bot. Maybe I will do it on one of my other servers.
Actually just wanted to test the bot, didn't know it would end up in more work :-P
