### ISSUE TITLE
Fehler beim Start

### ISSUE THREAD

**Issue by Zitrapfel** [flyth/ts3soundbot#258]
Hallo Freunde,

ich habe heute den TS3Soundbot installiert.
Lief auch problemlos. Bis zum Starten dort erhalte ich folgende Fehler, hier der Auszug:

[dix] Could not init font path element /var/lib/defoma/x-ttcidfont-conf.d/dirs/TrueType, removing from list!
xinit: XFree86_VT property unexpectedly has 0 items instead of 1
  _____ ___ _______                   _ _                      _
 |_   _/ __|__ / __| ___ _  _ _ _  __| | |__  ___  __ _ _ _ __| |
   | | \__ \|_ \__ \/ _ \ || | ' \/ _` | '_ \/ _ \/ _` | '_/ _` |
   |_| |___/___/___/\___/\_,_|_||_\__,_|_.__/\___/\__,_|_| \__,_|

               (C) 2013-2015 Michael Friese. All rights reserved.

2015/05/21 16:20:17 f25691c2 INFO   Initializing bot://f25691c2-98e8-499c-8b2f-5b7f01060014
2015/05/21 16:20:17 f25691c2 bea6b7d1 INFO   Loaded
2015/05/21 16:20:17 FFmpeg/avcodec v3675236; license: LGPL version 2.1 or later; 494 codecs
2015/05/21 16:20:17 FFmpeg/avformat v3674980; license: LGPL version 2.1 or later; 139 formats
Xlib:  extension "DPMS" missing on display ":1.0".

The VNC desktop is:      localhost:0
PORT=5900
2015/05/21 16:20:17 RadioStation data loaded
2015/05/21 16:20:17 Imported radio stations

Hoffe ihr könnt helfen.
Vielen Dank im Vorraus :)

**Comment by flyth** [comment]
Alles eher Warnungen, die man ignorieren kann. Was genau ist das Problem?

**Comment by Zitrapfel** [comment]
Wenn ich mein Webinterface öffnen möchte (unter: IP-Adresse:8087) lädt es nicht. Habe extra nochmal in den config.ini nachgeschaut und der Port ist der Richtige (Host auf 0.0.0.0) gelassen

**Comment by flyth** [comment]
Firewall-Problem vielleicht?

**Comment by Zitrapfel** [comment]
Ja. Gut das es Leute gibt die einem helfen. Danke, hab schon gedacht ist ein ernstzunehmendes Problem am Server :+1:
