### ISSUE TITLE
Bot stop sending sounds after 1 song.

### ISSUE THREAD

**Issue by Guibibi** [flyth/ts3soundbot#259]
So the bot works great, except that after it finished playing a song, it will start another song, but no actual sound is coming out.

**Comment by flyth** [comment]
Are you using playlists? For the "All files" it's normal that it stops after each song.

**Comment by Guibibi** [comment]
Yes I am using a playlist, and when the sound is off I can still see the progress bar moving.

**Comment by capsload** [comment]
Time for auto play after auto restart ;-)

**Comment by xsairam** [comment]
I just tested the bot and I almost got  same problem. Its just with !next command - sound keeps playing in webinterface but you dont hear anything. Ts3 Client keeps glowing.
0.9.6 -not sure since its showing it only in the icon xD
Windows server 2012R2

**Comment by BlueFreakLP** [comment]
Is the problem still there with the newst version @xsairam @Guibibi ?

**Comment by xsairam** [comment]
i didnt try again.
