### ISSUE TITLE
[suggestions] suspecct's suggestions

### ISSUE THREAD

**Issue by Suspect** [flyth/ts3soundbot#26]
I hope I can provide some suggestions here instead of making more 'issues'.

1. I was wondering if you could make an easy way of adding favicons just for aesthetic reasons.
2. If possible can you make a global permissions system to allow certain permissions without registering users. 
3. When a requested youtube video stops playing it will switch to a radio stream [make global stream URL] \ have control if this is enabled via commands? !enable-auto-radio !disable-auto-radio also a the volume for the radio.
4. I'm not sure if this is a feature but the ability to add a custom radio .pls link [part of a playlist or all music], I have not managed to add one yet.

** I have just noticed your TODO list so avoid the duplicates.

**Comment by Niggolo** [comment]
about n* 3 i like it too but not only to radio maybe it can resume the playlist?
about n* 4 i found out you can reproduce custom radio like "!stream http://mp3.kataweb.it:8000/RadioDeejay! and it reproduce Radio DeeJay, but you have to find a valid url

**Comment by flyth** [comment]
1. good idea, will implement that
2. planned
3. also a good idea; there's also a wish for a function to auto-start a specific file - I'll add both features
4. adding playlists (.pls/.m3u) is not supported yet - you may however as @Niggolo suggests add specific stream-urls directly (there's also a button on the upper right on the files-list to add streams permanently)

Thanks for the valuable feedback!

**Comment by flyth** [comment]
1. added in the latest release; copy the favicon to ./static/favicon.ico

**Comment by Suspect** [comment]
@flyth Thanks, do you make any changelogs anywhere?

**Comment by JanDevDE** [comment]
@Suspect Go on your webinterface. Go on Settings, go on Info, go on Changelog ;)

**Comment by Suspect** [comment]
@JanDevDE Ahhh okay, I totally forgot about that, thanks :)

**Comment by Niggolo** [comment]
if i can ask, where is .static/favicon.ico LOL

**Comment by flyth** [comment]
You have to create it :)

**Comment by Niggolo** [comment]
but where? ts3soundboard/data?

**Comment by flyth** [comment]
ts3soundboard/static then
By `./` I meant the path of the executable

**Comment by Niggolo** [comment]
oh ok thank you

**Comment by flyth** [comment]
Most of the things have been implemented. The playlist-stuff (m3u/pls) exists somewhere else.
