### ISSUE TITLE
How to connect to CPanel from another PC

### ISSUE THREAD

**Issue by xviber** [flyth/ts3soundbot#260]
Hi and thank you for all the stuff that you make for us, it's unbelievable that is free. 
I have a question, what can i do to connect to the bot cpanel from another pc. I have to specify that the bot is hosted on a vps, all ports are opened, and when i try to connect with http://botip:8087 the page is loading but nothing to do. Thank you againg. Best regard

**Comment by flyth** [comment]
You're welcome :)
Is your VPS directly connected to the internet? Do you have `ListenHost = "0.0.0.0"` in your config.ini? Are you sure there's no firewall blocking connections? Which OS are you using? What kind of VPS is it?

**Comment by xviber** [comment]
Is directly connected to the internet i guess, firewall configured to accept entries, windows 6 gb ram and so on. Listen 0.0.0.0

**Comment by flyth** [comment]
Hmm... "i guess" ;) What does the IP of that server start with? You mentioned "from another pc". From your own pc it does work?

**Comment by xviber** [comment]
Ok never mind. It's working with firewall off. Thank you again flyth. Maybe when i take the cash, a beer 🍻 it's your

**Comment by flyth** [comment]
Great :)
