### ISSUE TITLE
Connect to cpanel problem

### ISSUE THREAD

**Issue by xviber** [flyth/ts3soundbot#261]
Hi again. I can connect to cpanel but i recive Unauthorized error.
User and pass are good, full acces but nothing to do. What can be broken ?
![capture](https://cloud.githubusercontent.com/assets/12551670/7770669/5551d6be-0091-11e5-93f2-f43ea53f1771.PNG)

**Comment by BlueFreakLP** [comment]
Have you read the wiki?

**Comment by flyth** [comment]
Changed the password via !password? That's buggy in the current version. Use the webinterface.

**Comment by xviber** [comment]
I read the wiki, it's nothing about my problem, and if you don't understand what i ask, please don't make a reply. Flyth, i change the pass of admin from webinterface. From the vps i can login but from my pc doesn't work.

**Comment by xviber** [comment]
flyth if you let me your email adress to keep in contact and maybe i will give you a remote to see what is wrong ?

**Comment by flyth** [comment]
Please check the website or use the forum for that :)
