### ISSUE TITLE
Bot doesent download whit !yt Command

### ISSUE THREAD

**Issue by Atomzwieback** [flyth/ts3soundbot#263]
Hey Guys,

I have the Problem that the bot doesnt dowload any yt song.
Can anyone help me?

Redgards

Pictures:

http://fs1.directupload.net/images/150523/ppdmiczs.png
http://fs1.directupload.net/images/150523/m55f4mpl.png

**Comment by UnwishingMoon** [comment]
Have you try to change the link??
Because, sometimes, some link of youtube doesn't work or the videos is blocked in the VPS country

**Comment by Atomzwieback** [comment]
Yes i think 20 Times

**Comment by flyth** [comment]
Are you using the windows-version? Or is OVH your provider?

**Comment by Atomzwieback** [comment]
Hi flyth im using the Linux version on debian 7 my provider is x4tec

**Comment by Benjarobbi** [comment]
Hey, Flyth if you not know, what x4tec is here is the Link: https://x4-tec.com/de/
P.S They not host in a OVH Datacenter :+1: 
PP.S They host in the https://www.plusserver.de/ Datacenter :smile:

**Comment by BlueFreakLP** [comment]
Old ticket and still open. If there is any problem, please create a new ticket.
