### ISSUE TITLE
Youtube-dl incompatible Version

### ISSUE THREAD

**Issue by Joniator** [flyth/ts3soundbot#264]
I installed youtube-dl via "apt-get install youtube-dl"
Updated via apt-get update
Looked for the path which youtube-dl
Copied the path in the config.ini youtubeDLPath = "/usr/bin/youtube-dl"

Looked for the version:
youtube-dl --version: 2014.08.05

This should not be incompatible, right?
If I try to load a link it says youtube-dl not available

2015/05/24 00:37:46 2d8ee8e7 INFO   Initializing bot://2d8ee8e7-f504-4e5d-a106-c9682150b37d
2015/05/24 00:37:46 2d8ee8e7 969f21d6 INFO   Loaded
2015/05/24 00:37:46 FFmpeg/avcodec v3675236; license: LGPL version 2.1 or later; 494 codecs
2015/05/24 00:37:46 FFmpeg/avformat v3674980; license: LGPL version 2.1 or later; 139 formats
2015/05/24 00:37:46 youtube-dl checking...

The VNC desktop is:      localhost:0
PORT=5900
2015/05/24 00:37:46 youtube-dl incompatible version, please update
2015/05/24 00:37:46 RadioStation data loaded
2015/05/24 00:37:46 Imported radio stations

**Comment by supimfuzzy** [comment]
Same problem here. I have the most recent version.

**Comment by flyth** [comment]
It's like the bot says. 2014.08.05 is MUCH too old.
Try `sudo youtube-dl --update`

**Comment by Joniator** [comment]
It just says "It looks like you installed youtube-dl with a package manager, pip, setup.py or                                                       a tarball. Please use that to update."
I try to reinstall, looks like the apt-get isnt´t up to date :(

Install it from their site, this one works fine and is up to date: http://rg3.github.io/youtube-dl/download.html
Just follow the instructions via wget or curl, this works fine for me ;)

**Comment by BlueFreakLP** [comment]
Yes with curl it works fine. You need to set in the config the path after, 
you
can get the path with the Command "which youtube-dl"

**Comment by supimfuzzy** [comment]
This is the wrapper I use to download via IPv4 and also audio only.

````
#!/bin/bash
/usr/local/bin/youtube-dl -4 -f bestaudio "$@"
````

Put that in a file and name it `youtube-dl-wrapper` and save it to the `/ts3soundboard` folder.
Then run `chmod u+x youtube-dl-wrapper`.
Open up your `config.ini` and change the value of `YoutubeDLPath` to where ever youtube-dl-wrapper is located.

**Comment by Joniator** [comment]
You, sir, are my hero <3

Works all pretty fine, thank you ;)
