### ISSUE TITLE
Bot ruckelt andauernd

### ISSUE THREAD

**Issue by pasi123567** [flyth/ts3soundbot#265]
Habe mir den bot runtergeladen doch er ruckelt ständig sodass keiner die musik ordentlich hören kann :(
Hab auch schon probiert die priorität höher zu stellen hat aber nix gebracht...

**Comment by flyth** [comment]
Auch Windows, nehme ich an? Virtuelle Maschine oder Rechner?
Versuch mal bitte in der config.ini
`SampleInterval = 200`
zu stellen.

**Comment by pasi123567** [comment]
Ich habe Windows 7 Rechner und bei mir sieht die config so aus:
http://i.imgur.com/pMtkxhp.png
Muss ich das einfach hinzufügen oder wie?

**Comment by flyth** [comment]
Ja.
Merkwürdig, dass es auf einem normalen Rechner auftritt... Es könnte auch helfen, die Firewall mal temporär zu deaktivieren.

**Comment by pasi123567** [comment]
Hab alles probiert, aber half nicht

**Comment by flyth** [comment]
Schade, dann habe ich keine weitere Idee. Scheint bei einigen der Fall zu sein, auf meinen Windows-Maschinen (8.1 / 10) läuft alles flüssig - daher kann ich's auch nicht wirklich debuggen :/
Windows 7 habe ich seit geraumer Zeit nicht mehr im Einsatz - aber ich hörte von Leuten, dass es dort ebenfalls ohne Probleme lief.

**Comment by pasi123567** [comment]
Könntest du vielleicht irgendwie helfen? Teamviewer oder Teamspeak???

**Comment by flyth** [comment]
Ich fürchte nicht, sorry. Du kannst aber gerne mal deine Systemspezifikationen (Prozessor, Mainboard, Grafikkarte) posten, vielleicht findet man Gemeinsamkeiten...

**Comment by pasi123567** [comment]
Vllt was mit der Soundkarte? http://i.imgur.com/FcYs5Zf.png

**Comment by pasi123567** [comment]
Ok habe grade die Priorität von dem 2ten TS client höher gestellt, hat geholfen! Ist zwar noch immer net 100% laggfrei aber es ist besser. 
Hab ca herausgefunden woran es liegt.
Liegt glaube echt an der soundkarte oder and der verbingung vom ts3bot zum ts3client.
Hatte grade minecraft gestartet und es hat direkt angefangen mehr zu ruckeln.
Mehr cpu = mehr lagg

**Comment by BlueFreakLP** [comment]
Deine CPU hoch ausgelastet? Evtl. Versucht windows deswegen die prozesse
einzudämmen.

**Comment by pasi123567** [comment]
Nein normal ist die cpu bei 2% Torzdem habe ich laggs
Ist die cpu aber zB auf 50% ruckelt es VIEL mehr

**Comment by flyth** [comment]
Was für eine CPU hast du?

**Comment by pasi123567** [comment]
CPU: http://i.imgur.com/lxtfE7H.png
Motherboard: http://i.imgur.com/bqDKKKw.png
BIOS: http://i.imgur.com/uZCqnX9.png
RAM: http://i.imgur.com/XSpxVos.png
Grafik: http://i.imgur.com/aEe90J4.png
Festplatte: http://i.imgur.com/yCSMbv8.png
Soundgeräte: http://i.imgur.com/h1zAaCg.png

**Comment by flyth** [comment]
Danke :)

**Comment by pasi123567** [comment]
Achja, auserdem wenn ich den bot installiere steht m desktop dann nicht version 0.9.7 sondern 0.9.6?

**Comment by pasi123567** [comment]
Hey hab grade den gößtenteil des lagges gefixt! Aber vllt kannst du ja irgendwie probieren die verbindung vom bot zum ts zu verbessern. 
Auf jedenfll habe ich beim radip sender gerade den österreichischen gesucht aber den findet er nicht D: ( Hitradio ö3 bzw. oe3)

**Comment by flyth** [comment]
Viel optimieren kann ich da ohne Weiteres leider nicht. Danke auf jeden Fall für den Lösungsansatz, ich werde das mal in die FAQ einpflegen.

Radiosender kannst du über "URL hinzufügen" unter "Alle Dateien" manuell hinzufügen. Dazu brauchst du dann die korrekte Stream-Url des Senders.

**Comment by pasi123567** [comment]
Noch eine frage : Wie geht das mit lieder von youtube abspielen? Irgendwas mit der Youtube dll, hab aber keine ahnung wie ich diese installiere D:

**Comment by flyth** [comment]
Zu youtube-dl gibt es haufenweise Infos und bald auch eine offizielle Anleitung. Unter Windows ist es bis zur nächsten Version leider noch buggy.

Zum Stream: Google nach "oe3 orf mp3 stream" brachte mich zu folgender Seite:
http://blog.cabl.at/2009/10/orf-radio-streams.html
Da findest du die Urls, die du brauchst.

**Comment by flyth** [comment]
Ich mach hier erst mal zu. Danke für die Hilfe!
