### ISSUE TITLE
Win:[Cannot start bot]TSClient quit.

### ISSUE THREAD

**Issue by Hellosir55** [flyth/ts3soundbot#266]
Hi,

i have installed the bot and it shows me this on startup :

               (C) 2013-2015 Michael Friese. All rights reserved.

Generating new bot instance with account 'admin' and password 'foobar'
2015/05/24 19:34:41 Updating database to v1... 0
2015/05/24 19:34:41 Updating database to v2... 1
2015/05/24 19:34:42 b527eb86 INFO   Creating default instance
2015/05/24 19:34:42 b527eb86 INFO   Promoting instance to main instance
2015/05/24 19:34:42 b527eb86 d79b5dbd INFO   VNC not supported for this platform
.
2015/05/24 19:34:42 b527eb86 d79b5dbd INFO   Starting instance ts3server://127.0
.0.1?port=9987&nickname=TS3SB-Demobot&password=&channel=&channelpassword=
2015/05/24 19:34:42 b527eb86 INFO   Adding new useradmin
2015/05/24 19:34:42 FFmpeg/avcodec v3673444; license: LGPL version 2.1 or later;
 493 codecs
2015/05/24 19:34:42 FFmpeg/avformat v3673958; license: LGPL version 2.1 or later
; 138 formats
2015/05/24 19:34:42 Could not find RadioStation-Data, updating...
tracks 10039
2015/05/24 19:34:46 RadioStation data loaded
2015/05/24 19:34:46 Imported radio stations
2015/05/24 19:34:47 b527eb86 d79b5dbd INFO   TSClient quit.
2015/05/24 19:39:34 b527eb86 INFO   LOGIN [admin] OK

As you can see, TS quits right away.
If i quit the bot and relauch it, it doesn't even show up thsi line (ts3 don't even start).
Deleting "data" folder makes the error too show up again.
I suspect there's someting written to data folder that is making TS to quit.

I changed address, bot name, etc in the web interface, saved, and restarted the bot. But with the data folder being not deleted (to save settings) the TS isntance does not start. Same problem, so i can't configure it.

I deleted everything/reinstalled on another folder/drive => Same problem, on 1st start, "TS quit" then nothing on following restarts.

Speaking of restart, i restarted the computer, same.

I tried all i could i think. I have enough RAM, etc.
Does the bot creates reg lines ? or anything ?

os : Windows 8.1 x86_64

**Comment by flyth** [comment]
Did you actually push the small "Power"-button at the upper right in the webinterface after you configured the bot?

The one-time launch/quit after a new installation is normal - it just creates a dummy config for the client.

**Comment by Hellosir55** [comment]
I forgot that step... I'm dumb. Did not know that power button was there to kill/invoke TS.

It works now. I'll try the linux version later.

If i find any -REAL- bug, i'll report it to help.

Thanks for the (very) fast answer, and sorry. Also, nice program, it avoids the use of a VM and all the problems with it.
