### ISSUE TITLE
[Feature Request] Set Bot Avatar+Description on TeamSpeak

### ISSUE THREAD

**Issue by Flybel** [flyth/ts3soundbot#268]
I'd like to see the ability to set a TeamSpeak avatar and the TeamSpeak Client description for each instance. For example, through the webpanel, by a drag and drop field for local files and a "Insert link" field, and another field for "Client description".

I also hope to see the ability to stream YouTube videos without having to download them soon (I know you said the YouTube streaming function will be improved soon), as I don't want to have a full hard drive each week. :P 

Thanks for making that amazing bot for free!

**Comment by flyth** [comment]
Avatar will come with the next version, not sure about the description, yet.
Stream-without-download will also be in the next version.

:)

**Comment by Flybel** [comment]
Amazing to hear that! Any idea when the version will be released?

Thanks so much, you're doing an incredibly good job!

**Comment by flyth** [comment]
Reeeallly soon now :)
And thanks^^

**Comment by Flybel** [comment]
:3

**Comment by flyth** [comment]
If you don't have more than 2 instances running and want to help finding some last minute bugs, try this version: https://frie.se/ts3bot/sinusbot-0.9.8-bin.tar.bz2

(Also, to all those who are watching this "repo": feel free to join as well! For discussions, please visit https://forum.sinusbot.com/)
