### ISSUE TITLE
shuffle problem

### ISSUE THREAD

**Issue by Niggolo** [flyth/ts3soundbot#27]
i have one playlist with 110 files and shuffle enabled but i found out something:

i was doing !next every 1/2 sec for search a music and i noticed it play one music twince or more time in short period, now i always use shuffle on windows media player ect and if im not wrong it reproduce the file only one time untill the playlist is not fully reproduced.

here one example:

<19:46:28> "Niggolo": !next
<19:46:28> "SpHx Music": Now playing: Ultra Music - Steve Aoki feat. Polina - Come With Me (Deadmeat) (Official Video)

<19:49:54> "Niggolo": !next
<19:49:54> "SpHx Music": Now playing: Ultra Music - Steve Aoki feat. Polina - Come With Me (Deadmeat) (Official Video)

Between file i only did 4 !next, and it happen every time even if not using next, since the fisrt time i start use the bot i noticed many files of my playlist is not being reproduced and other file are reproduced 4/5 time

**Comment by flyth** [comment]
Yeah, the shuffle is currently pretty dumb, I'm aware of that :)
I will change that behavior once all the basic features are done.

**Comment by Niggolo** [comment]
ok thank you

**Comment by nrauschcom** [comment]
Shuffle would be pretty nice, my mates aren't so amused hearing the same song three times in a row :D

**Comment by flyth** [comment]
Has been optimized recently.
