### ISSUE TITLE
Dateien fehlen

### ISSUE THREAD

**Issue by Benjarobbi** [flyth/ts3soundbot#271]
Im Neuen Bot fehlen mehrere Dateien, z.B die die man als Plugin in den TS3 Client einfügen soll. 
Ich beziehe mich auf die Linux Version! 0.9.8

**Comment by GERIskillzZz** [comment]
Jo, habe das auch gerade bemerkt. Sogar die config Datei fehlt, deshalb ist es nicht möglich den Bot auszuführen

**Comment by flyth** [comment]
Huiuiui, zu schnell released... sorry... melde mich in ein paar Minuten.

**Comment by Benjarobbi** [comment]
Hehe, da sind deine Kleinen Bug reporter doch gleich gekommen :laughing:

**Comment by Atomzwieback** [comment]
Hab ich auch gemerkt :+1:

**Comment by flyth** [comment]
Soo, Anleitung wurde upgedated und die Datei auf dem Server auch. Es gibt Änderungen beim Kopieren des Plugins (liegt jetzt in einem Unterordner) und die config.ini.dist dient als Basis für die config.ini.
Ich werde das in den kommenden Tagen mal ein wenig optimieren, hoffe aber, dass es jetzt erst mal so funktioniert.

Dass die Limits in/nach der Beta-Phase noch heruntergeschraubt werden, hatte ich mal in einem [Blog-Eintrag](https://frie.se/soundblog/post/next-steps/) erwähnt (über Spenden ist leider nie wirklich etwas zusammen gekommen). Das ist jetzt die finale Limitierung. Wer den Bot wirklich so ausgiebig nutzt, kann sich in hoffentlich nicht allzu ferner Zukunft für einen kleinen Betrag eine Premium-Version kaufen oder sich an die Hosting-Partner wenden.
Frühe Beta-Tester werden belohnt und bekommen eine Gratis-Premium-Lizenz, die u.A. die Limits wieder hoch setzt. Ich kann allerdings noch keinen genauen Zeitpunkt nennen (hoffe aber auch hier möglichst bald). Wer die 6 Instanzen unbedingt braucht, sollte also vorerst lieber noch bei der alten Version bleiben.

**Comment by Atomzwieback** [comment]
Wollte mich auch nur Kurz erkundigen ist eine Re-Installation von Nöten oder reicht es wenn ich den Bot via "./ts3bot -update"  Update?  Und die zweite Frage ist ab wann wird die Premium Version verfügbar sein? LG

**Comment by flyth** [comment]
Das Update **muss** manuell passieren, weil ich eben niemandem dieses 6 => 2 Bots "aufdrücken" will. Allerdings reicht es, die `ts3bot` und das Plugin upzudaten. Eine Neuinstallation ist nicht nötig. Eine Update-Anleitung folgt bald für die Leute, die sich ein selbstständiges Update nicht zutrauen.

Was den Zeitpunkt betrifft gilt hier wie **immer** (siehe FAQ): es gibt generell keine genaueren Auskünfte. "Hoffentlich bald" muss dir genügen.
