### ISSUE TITLE
New update made !yt break on my side

### ISSUE THREAD

**Issue by mauzao9** [flyth/ts3soundbot#272]
Hello there.

After i update i noticed that via !yt all the youtube links i ask to download to fail at the end, yet they work if i use the upload link on the web panel.

The logs show this:
2015/05/25 16:46:03 6f2e7204 DEBUG  youtube-dl[out] [download]   0.0% of 7.95MiB at 29.33KiB/s ETA 04:37
2015/05/25 16:46:03 6f2e7204 DEBUG  youtube-dl[out] [download]   0.0% of 7.95MiB at 87.35KiB/s ETA 01:33
2015/05/25 16:46:03 6f2e7204 DEBUG  youtube-dl[out] [download]   0.1% of 7.95MiB at 202.86KiB/s ETA 00:40
2015/05/25 16:46:03 6f2e7204 DEBUG  youtube-dl[out] [download]   0.2% of 7.95MiB at 433.18KiB/s ETA 00:18
2015/05/25 16:46:03 6f2e7204 DEBUG  youtube-dl[out] [download]   0.4% of 7.95MiB at 747.62KiB/s ETA 00:10
2015/05/25 16:46:03 6f2e7204 DEBUG  youtube-dl[out] [download]   0.8% of 7.95MiB at 833.86KiB/s ETA 00:09
2015/05/25 16:46:03 6f2e7204 DEBUG  youtube-dl[out] [download]   1.6% of 7.95MiB at  1.12MiB/s ETA 00:06
2015/05/25 16:46:03 6f2e7204 DEBUG  youtube-dl[out] [download]   3.1% of 7.95MiB at  1.39MiB/s ETA 00:05
2015/05/25 16:46:03 6f2e7204 DEBUG  youtube-dl[out] [download]   6.3% of 7.95MiB at  1.43MiB/s ETA 00:05
2015/05/25 16:46:04 6f2e7204 DEBUG  youtube-dl[out] [download]  12.6% of 7.95MiB at  1.66MiB/s ETA 00:04
2015/05/25 16:46:05 6f2e7204 DEBUG  youtube-dl[out] [download]  25.2% of 7.95MiB at  2.01MiB/s ETA 00:02
2015/05/25 16:46:05 6f2e7204 DEBUG  youtube-dl[out] [download]  50.3% of 7.95MiB at  2.11MiB/s ETA 00:01
2015/05/25 16:46:06 6f2e7204 DEBUG  youtube-dl[out] [download]  78.3% of 7.95MiB at  2.26MiB/s ETA 00:00
2015/05/25 16:46:06 6f2e7204 DEBUG  youtube-dl[out] [download] 100.0% of 7.95MiB at  2.45MiB/s ETA 00:00
2015/05/25 16:46:06 6f2e7204 DEBUG  youtube-dl[err] WARNING q8ir8rVl2Z4: writing DASH m4a. Only some players support this container. Install ffmpeg or avconv to fix this automatically.
2015/05/25 16:46:06 6f2e7204 DEBUG  youtube-dlquit

**Comment by mauzao9** [comment]
Okay i used  
sudo apt-get install libav-tools

Still refuses it:
2015/05/25 16:49:24 6f2e7204 DEBUG  youtube-dl[err] WARNING Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.

This is new was working before update O__o

**Comment by flyth** [comment]
!yt won't save the files anymore but it should still play them.
!ytdl should do what !yt did before.

But you're saying that !yt doesn't do anything at all after it downloaded?

**Comment by mauzao9** [comment]
so ytdl is working, but yt isn't, always returns me this:
youtube-dl[err] WARNING q8ir8rVl2Z4: writing DASH m4a. Only some players support this container. Install ffmpeg or avconv to fix this automatically.

Once it reaches 100%, i actually installed those packages (apt-get), and it still errors saying it's outdated?

**Comment by flyth** [comment]
Both commands should actually return the same. Weird. Will look into that. I don't really think the warning has something to do with it.

**Comment by mauzao9** [comment]
Thanks for look on it. On my side i just can get the !ytdl to work (doesn't face that warning).

**Comment by flyth** [comment]
Okay, was a bug. Pushed an update. Thanks :)

**Comment by flyth** [comment]
Could you please confirm that it's working for you as well now? :)

**Comment by mauzao9** [comment]
Yes working correctly, the alert is there but doesn't break functionality.

**Comment by flyth** [comment]
Great, thanks!

**Comment by Bluscream** [comment]
Will you fix it in WIndows version too?

**Comment by flyth** [comment]
Nope, I think bugs on Windows are perfectly fine :P
Just kidding - of course I will fix that on Windows as well :) Just need a bit more time to publish the new version.

**Comment by Bluscream** [comment]
I just was confused since on linux there is already version 0.9.8 out and for windows still 0.8.6 :disappointed_relieved: I feel discriminated :c

**Comment by Bluscream** [comment]
Also i cant upload any files since reinstalling since chrome shows me a :no_entry_sign: icon when i try to move a file in my browser. Is it so hard to implement a "Upload file" button? :D

**Comment by Bluscream** [comment]
Also if this is buggy i want report it; otherwise ignore :)

2015/05/31 13:41:45 bd6958e8 e5c522b0 DEBUG  Could not delete from Notificationsno such table: Notifications
2015/05/31 13:41:45 bd6958e8 e5c522b0 DEBUG  Could not insert into Notifications-Tableno such table: Notifications
2015/05/31 13:41:45 bd6958e8 e5c522b0 DEBUG  Could not delete from Notificationsno such table: Notifications
2015/05/31 13:41:45 bd6958e8 e5c522b0 DEBUG  Could not insert into Notifications-Tableno such table: Notifications
2015/05/31 13:41:45 bd6958e8 e5c522b0 DEBUG  Could not delete from Newsno such table: News
2015/05/31 13:41:45 bd6958e8 e5c522b0 DEBUG  Could not insert into News-Tableno such table: News
2015/05/31 13:41:45 bd6958e8 e5c522b0 DEBUG  Could not delete from Newsno such table: News
2015/05/31 13:41:45 bd6958e8 e5c522b0 DEBUG  Could not insert into News-Tableno such table: News
2015/05/31 13:41:45 bd6958e8 e5c522b0 DEBUG  Could not delete from Newsno such table: News
2015/05/31 13:41:45 bd6958e8 e5c522b0 DEBUG  Could not insert into News-Tableno such table: News

**Comment by Bluscream** [comment]
Oh sorry i just read this: https://github.com/flyth/ts3soundbot/issues/288.

I still have 1 question, will windows updates always been delayed? I dont really want to install a linux VM just for your ts3bot :c

**Comment by flyth** [comment]
Actually, the windows version (0.9.7, not 0.8.6) was for a long time a bit ahead of the linux version. I also had to reinstall my Windows build-system, which took me some time.

But yes, the windows version will probably always be a bit behind and get less love: if I release a new version and people find bugs, I don't want to re-deploy for two OSes all the time. This is still a spare time project :)

About the messages: they're flagged as DEBUG, which means: not really important and could be helpful for finding/fixing bugs.

**Comment by Bluscream** [comment]
Ive also read that you will limit the users/files too, is that right? If so how many GB/Files are normal users allowed to have? :o How much money do you want to give away a pro license?

**Comment by Bluscream** [comment]
Oh sorry for posting again but would it be okay to donate you a 15€ PSC? PayPal wont accept a payment to you: http://gyazo.com/7808e02e543614d34764c8ff01b7562d

**Comment by flyth** [comment]
**Currently**, there are no plans on decreasing user/file limits. There's also no pricing info available yet. And donations are of course always welcome and motivate me to spend more time on the project - but I don't know why PayPal doesn't accept your payment option, maybe Lastschrift is not supported for donations. :/

**Comment by Bluscream** [comment]
So can i send you a 15€ PSC Code instead? :D

**Comment by flyth** [comment]
I really wouldn't know what to buy with a PSC :)
But you know what? Spend that money on a bot hosted by a partner (I know they accept PSC) for a few months and I'll add you to the donators list as well. That way you'll get donators status AND one or more bots for a few months :) In the end that helps keeping the project alive just as much.
However you will decide: thanks a lot for your support!

**Comment by BlueFreakLP** [comment]
Or you simple get an Credit Card for Paypal...

**Comment by Bluscream** [comment]
@BlueFreakLP how old are you? This is nothing personal but your avatar makes me think you are 14 and talking about "credit cards" xD Im going to rent some bots for a month on TS3Index because of their software. I would love to have that for self-hosted bots :D
