### ISSUE TITLE
API for changing user permissions/adding users

### ISSUE THREAD

**Issue by supimfuzzy** [flyth/ts3soundbot#274]
Is there any way to control user permissions using the API?

**Comment by flyth** [comment]
Please see the last entry in the FAQ :)

**Comment by supimfuzzy** [comment]
Alright, so I have everything but the permissions figured out. What are the values?

**Comment by DurtyFree** [comment]
Can you share what you have figured out about the api? Because I cant find any proper list of all the available functions

**Comment by supimfuzzy** [comment]
I'm still working on it, I'll post it here after I complete it (should be done today). I'm just working on getting a list of available users and setting permissions.

If you didn't come across it, theres a PHP class for the bot with basic functions here: https://github.com/flyth/ts3soundbot/wiki/Accessing-Bot-Info-via-PHP

**Comment by flyth** [comment]
```
PRIV_LOGIN           = 0x00000001
PRIV_LIST_FILE       = 0x00000002
PRIV_UPLOAD_FILE     = 0x00000004
PRIV_DELETE_FILE     = 0x00000008
PRIV_EDIT_FILE       = 0x00000010
PRIV_CREATE_PLAYLIST = 0x00000020
PRIV_DELETE_PLAYLIST = 0x00000040
PRIV_ADDTO_PLAYLIST  = 0x00000080
PRIV_STARTSTOP       = 0x00000100
PRIV_EDITUSERS       = 0x00000200
PRIV_CHANGENICK      = 0x00000400
PRIV_BROADCAST       = 0x00000800
PRIV_PLAYBACK        = 0x00001000
PRIV_ENQUEUE         = 0x00002000
PRIV_ENQUEUENEXT     = 0x00004000
PRIV_ADMINQUEUE      = 0x00008000
PRIV_EDITBOT         = 0x00010000
PRIV_EDITINSTANCE    = 0x00020000
```

**Comment by supimfuzzy** [comment]
I see, how are they grouped together?

**Comment by flyth** [comment]
It's a bitmask. So in PHP that's basically
`$privileges = 0x00000001 | 0x00000002;` for PRIV_LOGIN and PRIV_LIST_FILE.

Make sure to read the current privileges before, though :)

**Comment by DurtyFree** [comment]
@supimfuzzy I already came along that file but I havent found any list of all the available functions yet.

**Comment by supimfuzzy** [comment]
I figured out all the API requests I need using Fiddler. AFAIK there is no public documentation regarding using the API besides that PHP script.

**Comment by DurtyFree** [comment]
Can you post the full list of all the available api requests?

**Comment by flyth** [comment]
Nope, since the API is not yet stable and might change without notice.

**Comment by DurtyFree** [comment]
Okay.
@supimfuzzy Could you maybe email the list of the api requests you found out about? :octopus:

**Comment by flyth** [comment]
@DurtyFree It's _really_ easy if you just use the developer tools of your browser. You will see every call in there.

**Comment by DurtyFree** [comment]
@flyth Okay I guess I figured it out myself, I just need to capture the calls the webinterface does to do the stuff.
Neat, i'll definetely play with that for a while, thanks! :octocat:

**Comment by supimfuzzy** [comment]
Check out Fiddler. Much more cleaner than the dev tools.

**Comment by supimfuzzy** [comment]
Well, I uh...Created this abomination to change user permissions while high as a kite. It does what I essentially need it to do which is allowing users to give themselves the playback permission after registering with the bot. 

I wouldn't suggest using this to give people permissions as opposed to the bots native control panel.

This uses the Bot class from [here](https://github.com/flyth/ts3soundbot/wiki/Accessing-Bot-Info-via-PHP), so just paste it in that file and you should be good to go.

Also note that this uses the decimal values to set the user's permission, so refer to this. If anyone would like to use something like enums, go right ahead.

Permission | Value
------------ | -------------
PRIV_LOGIN | 1
PRIV_LIST_FILE | 2
PRIV_UPLOAD_FILE | 4
PRIV_DELETE_FILE | 8
PRIV_EDIT_FILE | 16
PRIV_CREATE_PLAYLIST | 32
PRIV_DELETE_PLAYLIST | 64
PRIV_ADDTO_PLAYLIST | 128
PRIV_STARTSTOP | 256
PRIV_EDITUSERS | 512
PRIV_CHANGENICK | 1024
PRIV_BROADCAST | 2048
PRIV_PLAYBACK | 4096
PRIV_ENQUEUE | 8192
PRIV_ENQUEUENEXT | 16384
PRIV_ADMINQUEUE | 32768
PRIV_EDITBOT | 65536
PRIV_EDITINSTANCE | 131072



And here's the code:
```php
    public function getUsers() {
        $ch = curl_init();
        curl_setopt_array($ch, array(
            CURLOPT_URL => 'http://'.$this->botHost.':'.$this->botPort.'/api/v1/bot/users',
            CURLOPT_RETURNTRANSFER => 1,
            CURLOPT_HTTPHEADER => array('Authorization: bearer '.$this->token)
        ));
        $data = curl_exec($ch);
        $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);
        if ($code != 200) return NULL;
        $data = json_decode($data, TRUE);
        return $data;
    }

    public function setPermission($username, $privilege, $allow) {
        $users = $this -> getUsers();
        foreach ($users as $row) {
            if($row['username'] == 'cameron') {
                $user = $row['username'];
                $id = $row['id'];
                $privileges = $row['privileges'];
            }
        }

        if($allow) {
            if($privileges & $privilege){
                die("User already has this privilege.");
            }else {
                $permission = $privileges + $privilege;
            }
        }else {
            if($privileges & $privilege){
                $permission = $privileges - $privilege;
            }else {
                die("User does not have this privilege.");
            }
        }

        $ch = curl_init();
        $payload = '{"privileges":'.$permission.'}';

        curl_setopt_array($ch, array(CURLOPT_URL => 'http://'.$this->botHost.':'.$this->botPort.'/api/v1/bot/users/'.$id,
            CURLOPT_CUSTOMREQUEST => 'PATCH',
            CURLOPT_RETURNTRANSFER => 1,
            CURLOPT_POSTFIELDS => $payload,
            CURLOPT_HTTPHEADER => array('Authorization: bearer '.$this->token, 
                'Content-Type: application/json')));
        $response = curl_exec($ch);
        curl_close($ch);
    }
}
```

Usage: setPermission(String $username, int $privilege, bool $allow);
