### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by robotrono** [flyth/ts3soundbot#276]
I want know the changes or fixes.

**Comment by Khailz** [comment]
feat: avatar upload / removal
feat: stream-to-browser (experimental)
feat: several new !-commands
feat: bind account to a server group
feat: queue (with separate privileges to add tracks at the end or beginning of the queue)
feat: new whispermode for music-subscriptions
feat: add option to make tracks and playlists automatically play on startup or when idle
feat(hosting): single-sign-on
feat(hosting): add support for multicast
enh: don't import files from youtube-dl when streaming (but import when using the download-functionality)
enh: don't add temporary youtube-dl streams to the library anymore
enh: some HTTP header-corrections to speed things up and make things more secure
enh: added meta-tag to prevent robots from indexing
fix: hide options in track-dropdown that don't exist for the selected track
fix: unlock playlists on several operations that caused a deadlock before
fix: properly delete files (bulk as well)
fix: refresh file list on upload
fix: make youtube-dl work on windows
fix: no more endless loading when saving settings
fix: don't crash when playing back empty playlists
fix: reconnect streams after timeout
fix: many more small bugfixes

**Comment by robotrono** [comment]
Then, can I stream YT without download the file?

**Comment by Khailz** [comment]
!yt doesn't work for me

**Comment by flyth** [comment]
@Khailz did you update to the latest version? The 0.9.8 had a Problem #272 that got already fixed.

**Comment by Khailz** [comment]
@flyth no I haven't updated I get "UPDATER invalid character '<' looking for beginning of value" error

**Comment by flyth** [comment]
That's odd. Could you please try again and also manually a
`curl -v https://frie.se/ts3bot/updates/linux/amd64/manifest.json` ?

**Comment by Khailz** [comment]
Same error, the curl says Connection #0 to host frie.se left intact

**Comment by flyth** [comment]
Nothing else? That's really strange.

**Comment by Khailz** [comment]
Want the whole output?

**Comment by flyth** [comment]
There should be JSON.

**Comment by Khailz** [comment]
Oh, I thought it was just a GET response, there is no JSON

**Comment by flyth** [comment]
Thanks @Khailz
The issue with the updater has been resolved. If you get an error, please update manually by re-downloading the latest version. Sorry for the inconvenience.
