### ISSUE TITLE
Windows 32-bit

### ISSUE THREAD

**Issue by ramazanqqq** [flyth/ts3soundbot#277]
Have the Windows 32-bit link ?

**Comment by flyth** [comment]
[FAQ](https://frie.se/soundblog/pages/faq/)

**Comment by ramazanqqq** [comment]
what ?

**Comment by ramazanqqq** [comment]
when will it come out

**Comment by MrJoki007** [comment]
never

**Comment by ramazanqqq** [comment]
why do ?

**Comment by nrauschcom** [comment]
There won't be a 32 bit version. Read the FAQ

ramazanqqq <notifications@github.com> schrieb am Do., 28. Mai 2015 um
18:03 Uhr:

**Comment by ramazanqqq** [comment]
there are a lot of mistakes when it boots up windows come the new version will B
