### ISSUE TITLE
Help with Ts can't shutdown

### ISSUE THREAD

**Issue by 6xPink** [flyth/ts3soundbot#278]
```
2015-05-27T14:59:34+01:00 Loaded
2015-05-27T14:59:34+01:00 Starting instance ts3server://ts.siropgaming.co.uk?port=9989&nickname=TS3SB-Demobot&password=&channel=&channelpassword=
2015-05-27T14:59:34+01:00 TSClient quit.
2015-05-27T14:59:36+01:00 Starting instance ts3server://ts.siropgaming.co.uk?port=9989&nickname=TS3SB-Demobot&password=&channel=&channelpassword=
2015-05-27T14:59:36+01:00 TSClient quit.
2015-05-27T14:59:39+01:00 Could not request shutdown
2015-05-27T15:02:52+01:00 BOT-CONFIG [admin] HOST PORT CHAN CHANPW ANNOUNCE ANNOUNCESTR DUCKING DUCKINGVOLUME STICKY TTSLOCALE CHATIGNSRV CHATIGNPRIV CHATIGNCHAN CC OK
2015-05-27T15:03:17+01:00 Starting instance ts3server://127.0.0.1?port=9987&nickname=TS3SB-Demobot&password=&channel=&channelpassword=
```

**Comment by flyth** [comment]
Need more information. #232 ?

**Comment by 6xPink** [comment]
Hi this still hasn't worked

**Comment by 6xPink** [comment]
(C) 2013-2015 Michael Friese. All rights reserved.                                                                                                                                    
                                                                                                                                                                                      
2015/05/27 16:40:02 feba756e INFO   Initializing bot://feba756e-d059-4044-b2d0-aa0fb7a3b82d                                                                                           
2015/05/27 16:40:02 feba756e 914f3dde DEBUG  Spawning instance shortly due to missing configuration file                                                                              
2015/05/27 16:40:02 feba756e 914f3dde INFO   Loaded                                                                                                                                   
2015/05/27 16:40:02 FFmpeg/avcodec v3675236; license: LGPL version 2.1 or later; 494 codecs                                                                                           
2015/05/27 16:40:02 FFmpeg/avformat v3674980; license: LGPL version 2.1 or later; 139 formats                                                                                         
2015/05/27 16:40:02 feba756e 914f3dde INFO   Starting instance ts3server://127.0.0.1?port=9987&nickname=TS3SB-Demobot&password=&channel=&channelpassword=                             
This application failed to start because it could not find or load the Qt platform plugin "xcb".                                                                                      
                                                                                                                                                                                      
Available platform plugins are: xcb.                                                                                                                                                  
                                                                                                                                                                                      
Reinstalling the application may fix this problem.                                                                                                                                    
2015/05/27 16:40:03 RadioStation data loaded                                                                                                                                          
2015/05/27 16:40:03 Imported radio stations                                                                                                                                           
2015/05/27 16:40:03 feba756e 914f3dde INFO   TSClient quit.                                                                                                                           
2015/05/27 16:40:07 feba756e 914f3dde WARN   Could not request shutdown                                                                                                               
2015/05/27 16:40:33 feba756e 914f3dde DEBUG  Storing configuration.

**Comment by flyth** [comment]
What's your OS? Could you please run
`ldd /opt/ts3soundboard/TeamSpeak3-Client-linux_amd64/plugins/libsoundbot_plugin.so`
and
`ldd /opt/ts3soundboard/TeamSpeak3-Client-linux_amd64/ts3client_linux_amd64`
(make sure that the paths match your environment) and post the output?

**Comment by 6xPink** [comment]
My os this time is 14.04 lts

**Comment by 6xPink** [comment]
Also here's what u told me to run 

 ldd /opt/ts3soundboard/TeamSpeak3-Client-linux_amd64/plugins/libsoundbot_plugin.so                                                                                                  
        linux-vdso.so.1 =>  (0x00007fff323fc000)                                                                                                                                      
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1c16b0b000)                                                                                               
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1c16805000)                                                                                                             
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1c165ed000)                                                                                                     
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1c16228000)                                                                                                             
        /lib64/ld-linux-x86-64.so.2 (0x00007f1c1706e000)                                                                                                                              
$ ldd /opt/ts3soundboard/TeamSpeak3-Client-linux_amd64/ts3client_linux_amd64                                                                                                          
        linux-vdso.so.1 =>  (0x00007fffb3755000)                                                                                                                                      
        libQt5Core.so.5 => not found                                                                                                                                                  
        libQt5Gui.so.5 => not found                                                                                                                                                   
        libQt5Widgets.so.5 => not found                                                                                                                                               
        libQt5Network.so.5 => not found                                                                                                                                               
        libQt5Sql.so.5 => not found                                                                                                                                                   
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fa1b8e6b000)                                                                                                   
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa1b8c52000)                                                                                                             
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa1b8a4a000)                                                                                                           
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa1b8845000)                                                                                                           
        libquazip.so.1 => not found                                                                                                                                                   
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa1b8627000)                                                                                                 
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa1b8320000)                                                                                                             
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa1b7f5b000)                                                                                                             
        /lib64/ld-linux-x86-64.so.2 (0x00007fa1b9090000)

**Comment by flyth** [comment]
The output looks okay.
Did you install all dependencies the docs suggest?
You could also try `apt-get install libx11-xcb1` and please make sure the file
`/opt/ts3soundboard/TeamSpeak3-Client-linux_amd64/platforms/libqxcb.so`
exists.

**Comment by 6xPink** [comment]
Lib does exist so I have no clue why this isn't working

**Comment by 6xPink** [comment]
Ah this

**Comment by 6xPink** [comment]
sudo apt-get install x11vnc xinit xvfb libxcursor1 ca-certificates bzip2                                                                                               
Reading package lists... Done                                                                                                                                                         
Building dependency tree                                                                                                                                                              
Reading state information... Done                                                                                                                                                     
Package libxcursor1 is not available, but is referred to by another package.                                                                                                          
This may mean that the package is missing, has been obsoleted, or                                                                                                                     
is only available from another source                                                                                                                                                 
                                                                                                                                                                                      
E: Unable to locate package x11vnc                                                                                                                                                    
E: Unable to locate package xinit                                                                                                                                                     
E: Unable to locate package xvfb                                                                                                                                                      
E: Package 'libxcursor1' has no installation candidate

**Comment by 6xPink** [comment]
Do I need this package

**Comment by 6xPink** [comment]
If so is there another way to instsll it

**Comment by flyth** [comment]
Yes, those packages are required, otherwise I wouldn't have mentioned them in the guide... Your system seems to be pretty broken or is missing tons of repos. Try to fix your apt sources. This is however way out of scope of the bot support.

**Comment by 6xPink** [comment]
Ah I always get teh wrong shit

**Comment by flyth** [comment]
You're welcome^^
