### ISSUE TITLE
Cant Start the Musicbot

### ISSUE THREAD

**Issue by Bestgamerforever** [flyth/ts3soundbot#279]
Hi Guys,

I cant start the musicbot with that issue (debian 7, 64bit)

waiting for X server to shut down
root@vps:/opt/ts3soundboard# xinit /opt/ts3soundboard/TeamSpeak3-Client-linux_amd64/ts3client_linux_amd64 -- /usr/bin/Xvfb :1 -screen 0 800x600x16 -ac

[dix] Could not init font path element /usr/share/fonts/X11/cyrillic, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/100dpi/:unscaled, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/75dpi/:unscaled, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/Type1, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/100dpi, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/75dpi, removing from list!
[dix] Could not init font path element /var/lib/defoma/x-ttcidfont-conf.d/dirs/TrueType, removing from list!
xinit: XFree86_VT property unexpectedly has 0 items instead of 1
/opt/ts3soundboard/TeamSpeak3-Client-linux_amd64/ts3client_linux_amd64: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
xinit: connection to X server lost

Regards Timo

**Comment by flyth** [comment]
You're not starting the bot, you're trying to start the client.
