### ISSUE TITLE
Bug music player.

### ISSUE THREAD

**Issue by ambroisedu68** [flyth/ts3soundbot#280]
Hello, I have bots on my server but the sound quality that bugue. I watch and that not of vps. I lonquement look but I do not find anything and it does not come from my connection because the other onscreen user say.

When the bot read the music file or radio he cuts often.

I also discovered a bug when music changes quond the bot do not read music. Pariel quond allowed a playlist light any time the bot is always connect but you can not hear the music and chat he said the current music.

**Comment by flyth** [comment]
Sorry, I have no real clue what you're talking about. If the bot lags, it's probably a too weak VPS - especially on Windows that can happen a lot.

**Comment by ambroisedu68** [comment]
A ok and there would be no way?

**Comment by pixmaip** [comment]
@ambroisedu68 On vois bien que tu es française ^^, écris ton problème en français et je le traduirais à @flyth 

Ah ... Google Translate, ... not that powerful  =)

Pixmaip

**Comment by flyth** [comment]
I thought so :) Thanks for helping out^^

**Comment by ambroisedu68** [comment]
Oui je suis français. Du coup je voulais dire il n y a pas moyen de régler les bugs de lectures sur mon vps windows.

**Comment by pixmaip** [comment]
Peux tu donner un peu plus de détails ?

**Comment by ambroisedu68** [comment]
Enfaite j'ai des bugs de bot niveau son. Et aussi j'ai un bot avec une playlist et je demande de jouer aléatoirement il le fait mais il se coupent vers 3,4 heures après avoir allumer le bot je lui demander de lire la playlist mais rien pas de son ni message et sur le panel il dit qui lit une musique et je l'entend pas.

**Comment by pixmaip** [comment]
Vérifie la qualité son du channel. Quels sont les caractéristiques de ton VPS Windows ? Essaye de redémarrer le processus complètement.

**Comment by ambroisedu68** [comment]
Pour les codecs ces ça : 10 (estimated bitrate: 11.87 KiB/s)

Et après c'est vrai que je n'est pas redémarrer merci je le ferait plus tard.

**Comment by pixmaip** [comment]
Tiens nous au courent ;)

**Comment by ambroisedu68** [comment]
C'est bon.

**Comment by BlueFreakLP** [comment]
Can you please talk here in English, so everyone can understand it?

**Comment by flyth** [comment]
@pixmaip Has the issue been resolved? :)

**Comment by pixmaip** [comment]
@flyth I suppose ... not a lot of informations except a "It's good". Good to close I think.

**Comment by flyth** [comment]
Okay, thank you :)
