### ISSUE TITLE
Bot won't stick to channel

### ISSUE THREAD

**Issue by Spazmic** [flyth/ts3soundbot#281]
Hey,

well the title says it all lol. With stick to channel enabled, when the bot is moved he doesnt go back to his channel...

**Comment by CrAazZyMaN21** [comment]
Does the bot have enough join power?

**Comment by Spazmic** [comment]
The bot previously joined the channel by itself, it's just that when it's manually moved, it won't go back to the channel where it should. "Stick to channel" option is ticked.

**Comment by flyth** [comment]
Is there a password on the channel? Maybe that's buggy right now.

**Comment by Spazmic** [comment]
Actually, the channel in question is the lobby lol.

**Comment by flyth** [comment]
Does it say anything in the logs?

**Comment by Spazmic** [comment]
nothing in the logs with log level at 10

**Comment by Spazmic** [comment]
I have to say, i don't know if it changes something but I have the old ts3soundboard, before it was called sinusbot. Normally I was about to update directly from the webpanel, but now it's been a while since it asked me to update.

**Comment by Khailz** [comment]
Version 0.9.8 is a manual update you can see here [
https://frie.se/soundblog/post/sinusbot-0.9.8/](here)

**Comment by Spazmic** [comment]
I will update manually, see if it fixes my problem! I'll reply when done :)

**Comment by Spazmic** [comment]
I won't update finally. I need more than 2 instances. Also, I do not understand why there is no non-profit version like there was supposed to be.

**Comment by flyth** [comment]
What do you mean by "like there was supposed to be"? Even the commercial version has not yet been released.

**Comment by Spazmic** [comment]
Is there a non-profit version planned? If yes, will it be hard-limited to 2 instances?

**Comment by flyth** [comment]
There's no final decision on whether there will be a non-profit version or not - if there will be, that'd be a version for sponsored hosting for verified sponsors. The limit there probably would be 2 instances per sponsoree and a license based number of allowed sponsoree instances.

**Comment by Spazmic** [comment]
2015/05/28 17:53:31 fe158559 756da1ab INFO   Could not move back (sticky): Channel-Id not numeric

I tried with the channel ID (1) and the name (Lobby).

**Comment by BlueFreakLP** [comment]
Should be fixed at this time.
