### ISSUE TITLE
Sound Problems

### ISSUE THREAD

**Issue by ramazanqqq** [flyth/ts3soundbot#283]
After the music doesn't sound botan.. I have to remove 3 Windows 64 bit

**Comment by flyth** [comment]
I **really** don't get what you're saying there.

**Comment by ramazanqqq** [comment]
playlist somewhere then it doesn't move

**Comment by ramazanqqq** [comment]
bidets !yt is not a command

**Comment by pixmaip** [comment]
Try to be precise ... If we don't know what problem you have, it will be difficult to help you.
