### ISSUE TITLE
Instance limit

### ISSUE THREAD

**Issue by lowterie** [flyth/ts3soundbot#286]
hello dude !

To begin I wanted to thank you for ur great work !
I have just one question for instance limit i think u've block at 2 instances for limit the commercial users ?

Thanks a lot.

**Comment by flyth** [comment]
Thanks! You can find more information on that at #287, [here](https://frie.se/soundblog/post/next-steps/) and [here](https://frie.se/soundblog/post/sinusbot-0.9.8/).

**Comment by lowterie** [comment]
Ok thx dude ! :)
