### ISSUE TITLE
No windows updates?

### ISSUE THREAD

**Issue by Dethy** [flyth/ts3soundbot#288]
Hey, The windows download link just downloads version 0.9.6, is Windows no longer being updated or have i missed something?

**Comment by flyth** [comment]
a) this is an issue tracker (!)
b) the linux version has only been out for 2 days now (and focus is on linux)
c) generally NO ETA, see FAQ
d) I did not announce that I will drop support for Windows

Sorry for the harsh words, but all these non-issues in the last days cost time that I'd rather spend on e.g. compiling a version for Windows.
