### ISSUE TITLE
bot music microphone turned off

### ISSUE THREAD

**Issue by KurganFX** [flyth/ts3soundbot#289]
Hello. Install the plugin, I set up, but there is no microphone and the bot can not make music.
and even in the console getting WARN Could not send configuration - how to fix it?

**Comment by flyth** [comment]
Please read the [FAQ](https://frie.se/soundblog/pages/faq/)

**Comment by flyth** [comment]
What's your OS?
Please run a `ldd /path/to/the/plugin/libsoundbot.so`and paste the output.

**Comment by KurganFX** [comment]
Debian OS 7

root @ www: / home / ts3soundboard # ldd /home/ts3soundboard/TeamSpeak3-Client-linux_amd64/plugins/libsoundbot_plugin.so
/home/ts3soundboard/TeamSpeak3-Client-linux_amd64/plugins/libsoundbot_plugin.so: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.15 'not found (required by / home / ts3soundboard / TeamSpeak3-Client-linux_amd64 / plugins / libsoundbot_plugin.so)
         linux-vdso.so.1 => (0x00007ffff6bf0000)
         libstdc ++. so.6 => /usr/lib/libstdc++.so.6 (0x00007f0c29e59000)
         libm.so.6 => /lib/libm.so.6 (0x00007f0c29bd7000)
         libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x00007f0c299c0000)
         libc.so.6 => /lib/libc.so.6 (0x00007f0c29657000)
         /lib64/ld-linux-x86-64.so.2 (0x00007f0c2a3c3000)

**Comment by flyth** [comment]
Looks like your GLIBC is too old :/

**Comment by KurganFX** [comment]
The problem can only be associated with this plugin ?

**Comment by flyth** [comment]
Yes. You could try to upgrade your system as the plugin itself has been built on Debian 7.

**Comment by KurganFX** [comment]
Thank you for your prompt response . The system Linux newbie and I probably could not do it with the updating of the library. You will be able to help, even leading conversation ?
