### ISSUE TITLE
donate

### ISSUE THREAD

**Issue by Tavinlol** [flyth/ts3soundbot#292]
How can I donate?

**Comment by Khailz** [comment]
https://frie.se/ts3bot/#download Look at the donate panel

**Comment by Tavinlol** [comment]
Otavio Henrique, your donation is now complete

**Comment by Tavinlol** [comment]
I was upset that he had few people donating
Euro is too expensive why not donate more

**Comment by flyth** [comment]
Thank you very much for your support :)
