### ISSUE TITLE
Album Cover as Avatar

### ISSUE THREAD

**Issue by UnderTheCraft** [flyth/ts3soundbot#294]
As described in the title I think it'd be a nice feature if the avatar of the musicbot would be the album cover of the title which is played at the moment.

Best regards
UnderTheCraft

**Comment by s1kk** [comment]
Also an automatic rewrite of the Bot description would be cool!

**Comment by flyth** [comment]
Both already on the todo-list inside my head. :) Thanks :)

**Comment by flyth** [comment]
This has been implemented as script in one of the latest betas. See [forums](https://forum.sinusbot.com)
