### ISSUE TITLE
Suggestion: Other Bot Functions

### ISSUE THREAD

**Issue by s1kk** [flyth/ts3soundbot#295]
Hi flyth,
it would be cool if the bot could do some other work on the teamspeak server too like mass moving all people with the webinterface, auto-kick/auto-move guys who are recording without permission, move afk guys, and so on.

Greetings from Germany ;)

**Comment by nrauschcom** [comment]
The bot is not made for Server managing functionality. If you want
something like this , you have to install a second bot like JTS for example.

Danny W. <notifications@github.com> schrieb am Mo., 1. Juni 2015 16:59:

**Comment by BlueFreakLP** [comment]
Will be possible with the new version (is in testing right now and is not public).
