### ISSUE TITLE
Can't bind bot-account to server group

### ISSUE THREAD

**Issue by Topsii** [flyth/ts3soundbot#297]
I added a new user account "Registered User" with password "password" and then edited it and entered the server group id which I looked up with Ctrl+F1 in my client.
However executing the search command leads to nothing: "> Command ignored, user unknown."
I tried granting all possible permissions and restarted the instance as well as the application itself.

**Comment by flyth** [comment]
Make sure the bot has the privileges to request the servergroups and their members.

**Comment by Topsii** [comment]
My client is a guest as well and I was able to look up the server group id, and I can also check the server and channel group of other users with my client, so I assume the bot is able to do the same. Am I wrong with that assumption?

**Comment by flyth** [comment]
Sounds plausible, yes. Did you just upgrade to the new version or was this a fresh installation - if the former is the case: did you re-copy the plugin as well?

**Comment by BlueFreakLP** [comment]
Ticket is too long open and no reply.
