### ISSUE TITLE
Bot verbindet sich nicht mit dem Server

### ISSUE THREAD

**Issue by Leg3ndAry** [flyth/ts3soundbot#299]
Hallo Leute ich habe alles der Anleitung nach gemacht. Der bot verbindet sich aber leider nicht mit dem Server. System: Ubuntu 14.04 
![image](https://cloud.githubusercontent.com/assets/12736979/7970070/d316760a-0a3b-11e5-949d-aa66389e04db.png)
Diese Fehler Meldung erscheint in der Konsole.

**Comment by flyth** [comment]
Überprüfe bitte mal die Sicherheitsstufe des Servers. Ggf. musst du eine eigene Identität importieren.

**Comment by Leg3ndAry** [comment]
Der Server hat die Sicherheitsstufe 10

**Comment by flyth** [comment]
Yup, dann liegt's daran.

**Comment by Leg3ndAry** [comment]
Super vielen Dank für die schnelle Hilfe Super Support :D
