### ISSUE TITLE
Up/Downgrade Problem

### ISSUE THREAD

**Issue by LeoStoch** [flyth/ts3soundbot#300]
Got a problem with the old version, havent seen that the new update cant be used for more than 2 instances and cant download the bot from an older link. Dont know if you want this or if its an issue

**Comment by flyth** [comment]
Nope, the old download link is still up [here](https://frie.se/ts3bot/ts3soundboardbot-0.9.5.tar.bz2). I don't want to force anyone into the new version / instance limit.
