### ISSUE TITLE
Bot quits after starting it up

### ISSUE THREAD

**Issue by SebastianEriksson** [flyth/ts3soundbot#302]
Loglevel set to 10 and debug enabled

Running CentOs 6.6 (final)

I can access the webpage and change stuff, but the bot won't join the specified channel at all. Thanks in advance :)
e
2015/06/04 18:28:23 1aad6855 1985caf7 INFO   Loaded
2015/06/04 18:28:23 FFmpeg/avcodec v3675236; license: LGPL version 2.1 or later; 494 codecs
2015/06/04 18:28:23 FFmpeg/avformat v3674980; license: LGPL version 2.1 or later; 139 formats
2015/06/04 18:28:23 1aad6855 1985caf7 INFO   Starting instance ts3server://removed?port=9987&nickname=TS3-Bot&password=&channel=removed&channelpassword=
QXcbConnection: Could not connect to display :0.0
2015/06/04 18:28:24 1aad6855 1985caf7 INFO   TSClient quit.
2015/06/04 18:28:24 RadioStation data loaded
2015/06/04 18:28:24 Imported radio stations
2015/06/04 18:28:24 1aad6855 1985caf7 WARN   Could not request shutdown
QXcbConnection: Could not connect to display :0.02015/06/04 18:28:35 1aad6855 1985caf7 DEBUG  Storing configuration.

**Comment by flyth** [comment]
Don't enable debug :) LogLevel is enough. And there needs to be much more debug output.
Also, CentOS isn't officially supported. You'll find a guide on this issue tracker you might want to read.

For me it looks like the plugin could not be loaded correctly but there might be other issues as well.

**Comment by SebastianEriksson** [comment]
okay thanks for the quick reply! :)
