### ISSUE TITLE
Bot stop after a few songs

### ISSUE THREAD

**Issue by xviber** [flyth/ts3soundbot#303]
Hi again, I make a playlist with maybe 20 songs with shuffle mode on. After 4 maybe 5 songs the bot stop. It's on bot i don't hear nothing, on web interface show me that it's running.

**Comment by Khailz** [comment]
I have this problem as well, my playlists have around 200+ songs and stop. Smaller playlists don't have a problem.

**Comment by flyth** [comment]
Hmm, will investigate that.

**Comment by DCha0tiC** [comment]
Yeah,if i pause or change the music to fast the BOT stop working. I Have to reconnect him to server to work.

**Comment by flyth** [comment]
@DCha0tiC sounds like another issue? What do you mean by "too fast"?

**Comment by xviber** [comment]
If you type on the ts chat !next to skip a song and you type it again in 1-2 second for a few times.

**Comment by DCha0tiC** [comment]
Example: 3 persons operating the bot via site,so each one choose the music that he likes,and the others don't want to listen,they go and change or pause(exclusively pause) the bot stops working,but show that the song is running.

**Comment by Maxjose** [comment]
//Spanish
De igual forma presento el mismo problema. Luego de un par de músicas el bot deja de enviar sonido pero sigue conectado al TS y envía los mensajes en el chat.
Saludos...
//English
Likewise I present the same problem. After a couple of songs the bot stops sending sound but still connected to the TS and sends messages in the chat.

**Comment by flyth** [comment]
Please give the 0.9.9 beta versions a try.
