### ISSUE TITLE
BOT don't start if change the config.ini

### ISSUE THREAD

**Issue by DCha0tiC** [flyth/ts3soundbot#305]
Hi Flyth,i'm having an issue that every time that i change the config.ini and restart the bot,the bot don't start, the bot cmd screen just vanish and don't load nothing i have to leave the original config.ini to the bot load.

**Comment by Khailz** [comment]
Post your config.ini

**Comment by DCha0tiC** [comment]
TS3Path = "C:\\Users\\Administrator\\Desktop\\TS3SoundBoardBOT\\TeamSpeak 3 Client\\ts3client_win64.exe"
ListenHost = "0.0.0.0"
DataDir = ""
ListenPort = 8087
LocalPlayback = false
SecretKey = [193, 2, 240, 173, 3, 52, 190, 154, 153, 119, 32, 98, 188, 251, 61, 254, 254, 43, 245, 218, 47, 142, 211, 35, 111, 106, 0, 227, 29, 211, 70, 114]
Debug = false
LogLevel = 3
EnableProfiler = false
YoutubeDLPath = ""
EnableDebugConsole = false
UploadLimit = 83886080
RunAsUser = 0
RunAsGroup = 0
InstanceActionLimit = 6
UseSSL = false
SSLKeyFile = ""
SSLCertFile = ""
Hostname = ""


If i change a single thing,the bot doesn't work anymore.

**Comment by flyth** [comment]
Yeah, the ini-Reader is pretty strict right now. I guess you're using an editor not capable of different line endings, converting the file somehow. On Windows, try Notepad++ or such, that should work.

**Comment by DCha0tiC** [comment]
I'm using Notepad,the simpliest one that come with windows,i ll try to edit with my Atom(code editor)

**Comment by DCha0tiC** [comment]
Fixed.
I was forgetting to put \\ on each directory line,this was causing the problem when launching the BOT.
