### ISSUE TITLE
TSClient quit

### ISSUE THREAD

**Issue by vikeyev** [flyth/ts3soundbot#306]
I can't start the bot, it keeps stopping with the error below, running on a Debian 8 VPS. 
Ram usage (with bot on attached screen):

total | used | free | shared | buffers | cached
------|--------|-------|----------|----------|-----------
Mem: | 2010 | 1525 | 484 | 41 | 72 | 1128
-/+ buffers/cache: | 324 | 1685
Swap: | 0 | 0 | 0

**Console Output:**
2015/06/06 15:46:35 44218e5e aa3e92f4 DEBUG  Could not delete from Notificationsno such table: Notifications
2015/06/06 15:46:35 44218e5e aa3e92f4 DEBUG  Could not insert into Notifications-Tableno such table: Notifications
2015/06/06 15:46:35 44218e5e aa3e92f4 DEBUG  Could not delete from Notificationsno such table: Notifications
2015/06/06 15:46:35 44218e5e aa3e92f4 DEBUG  Could not insert into Notifications-Tableno such table: Notifications
2015/06/06 15:46:35 44218e5e aa3e92f4 INFO   Starting instance ts3server://hardkunts.servebeer.com?port=9987&nickname=Disco%20Bot&password=&channel=&channelpassword=
QXcbConnection: Could not connect to display :0.0
2015/06/06 15:46:35 44218e5e aa3e92f4 INFO   TSClient quit.
2015/06/06 15:47:02 44218e5e aa3e92f4 DEBUG  Storing configuration.

**Config settings:**
TS3Path = "/opt/ts3soundboard/TeamSpeak3-Client-linux_amd64/ts3client_linux_amd64"                 
  ListenHost = "0.0.0.0"
  DataDir = ""
  ListenPort = 8087
  LocalPlayback = false
  SecretKey = [42, 29, 218, 159, 136, 105, 205, 180, 180, 27, 61, 1, 220, 96, 151, 231, 89, 146, 125,     86, 53, 133, 90, 160, 158, 74, 59, 162, 230, 17, 186, 109]
  EnableLocalFS = false
  LogLevel = 10
  EnableProfiler = false
  YoutubeDLPath = ""
  EnableDebugConsole = false
  UploadLimit = 83886080
  RunAsUser = 0
  RunAsGroup = 0
  InstanceActionLimit = 6
  UseSSL = false
  SSLKeyFile = ""
  SSLCertFile = ""
  Hostname = "x.x.x.x"
  MTU = 1500
  SampleInterval = 100
  StartVNC = false
  EnableMulticastMetadata = false
  EnableWebStream = false
  
  [StreamRewrites]

(Replaced Hostname with x's)

**Comment by flyth** [comment]
Done [that](https://github.com/flyth/ts3soundbot/wiki/Installation---Debian-&-Ubuntu#troubleshooting)?

**Comment by flyth** [comment]
I guess you have now... :/
