### ISSUE TITLE
Channel Commander as Command

### ISSUE THREAD

**Issue by Newcomer1989** [flyth/ts3soundbot#307]
I have the problem with the bot, that it stops playing the streams sometimes. Within this it losts his channel commander status. I didn't find out till today why it happens. Perhaps connections problems between the server where the bot run and the teamspeak server (different machines).
For reactivating I only need to send the bot a !stream command. For me I solve this with a little query script, which checks this.
It would be nice, if there is also a command to gain the channel commander like !commander

**Comment by flyth** [comment]
This can be done via a little script and at least version 0.9.9.
