### ISSUE TITLE
Add Gay.FM

### ISSUE THREAD

**Issue by Karlo137** [flyth/ts3soundbot#309]
http://www.gayfm.de/
best music, add pls

**Comment by nrauschcom** [comment]
Why don't you just add it your own?
There are already many issues on how to do that.

Just press "Add URL" in all music tab and add `http://www.gayfm.de/listen.pls`

Please use the search next time.

**Comment by zoxovsky** [comment]
RLy thanks for this GAY FM XD good music hehe

**Comment by nrauschcom** [comment]
Ahahahah, thats so funny. Don't be childish please, this is a serous issue board.

**Comment by Karlo137** [comment]
Error
Could not playback

**Comment by zoxovsky** [comment]
Try this : http://tuner.gayfm.de

**Comment by Karlo137** [comment]
Working <3 <3 thank you! Gay.FM are epic. btw i'm not a gay

**Comment by zoxovsky** [comment]
Me too but here is really nice music xd

**Comment by Karlo137** [comment]
better then ilover.... ^.^
