### ISSUE TITLE
error while loading shared libraries: libQt5Gui.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by funkenstrahlen** [flyth/ts3soundbot#316]
Experiencing the exact same bug here: https://github.com/flyth/ts3soundbot/issues/217

It is a problem with loading the ts3_client: `error while loading shared libraries: libQt5Gui.so.5: cannot open shared object file: No such file or directory`

All dependency packages are installed correctly. Running as root does not help, so it is not rights issue.

**Comment by flyth** [comment]
What's your launch command?

**Comment by funkenstrahlen** [comment]
```
xinit ./ts3client_linux_amd64 -- /usr/bin/Xvfb :1 -screen 0 800x600x16 -ac

Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension GLX
[dix] Could not init font path element /usr/share/fonts/X11/cyrillic, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/100dpi/:unscaled, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/75dpi/:unscaled, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/100dpi, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/75dpi, removing from list!
xinit: XFree86_VT property unexpectedly has 0 items instead of 1
./ts3client_linux_amd64: error while loading shared libraries: libQt5Gui.so.5: cannot open shared object file: No such file or directory
xinit: connection to X server lost

waiting for X server to shut down 
```

**Comment by flyth** [comment]
Wrong command then :)

**Comment by funkenstrahlen** [comment]
It is the debug command listed in your manual:
![screen shot 2015-06-19 at 21 11 42](https://cloud.githubusercontent.com/assets/144173/8261036/b773edc2-16c7-11e5-8003-b33e77a4b767.png)

`xinit /home/bot/ts3soundboard/TeamSpeak3-Client-linux_amd64/ts3client_linux_amd64 -- /usr/bin/Xvfb :1 -screen 0 800x600x16 -ac`

I use this to debug.

Starting the ts3bot with `xinit /opt/ts3soundboard/ts3bot -- /usr/bin/Xvfb :1 -screen 0 800x600x16 -ac` works. But he can not connect to the TS server as seen in https://github.com/flyth/ts3soundbot/issues/217. Exact same behavior.

**Comment by flyth** [comment]
Okay, you didn't say that the bot runs when started with the correct command, so I assumed you tried with the wrong one.
Try to start the client with the *_runscript.sh file instead of ts3client_linux_amd64. That should get rid of the libQt-messages and tell you more about what's wrong.

**Comment by funkenstrahlen** [comment]
Somehow regenerating all locales fixed it. Strange behaviour though...

So you can close this. Thanks for fast response!

**Comment by flyth** [comment]
Okay, great :)
