### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by gmanc2** [flyth/ts3soundbot#317]
![Image of issue](http://i.gyazo.com/0726fe2f43d99434e5915ac18c50fe6b.png)
![Image of issue#2](http://i.gyazo.com/74eabdffce9fe0923131b87a5ebcc490.png)

**Comment by Raphouphe** [comment]
Do you tried to reinstall the bot? Or even your TS3? I'm not sure, but I think it has to do something with the Qt lib not installed / found

**Comment by BlueFreakLP** [comment]
Its an normal issue, that happends if the user dont install it right with the instructions.

**Comment by BlueFreakLP** [comment]
#365 the same.
