### ISSUE TITLE
Permissions are broken in latest version

### ISSUE THREAD

**Issue by SephLeague** [flyth/ts3soundbot#318]
Giving just playback permission doesnt work anymore and you have to give upload permission too for people to play things? and the server group functionality doesn't work either. Changing permissions is not as responsive as before.

**Comment by flyth** [comment]
Could you list exactly what commands differed for you in terms of privileges from the commands list on the info page?
The bot needs to be able to get the servergroups. It might also run into antiflood conditions when the server has MANY groups. This has been fixed in a newer release which should be released soon.

**Comment by SephLeague** [comment]
Well in older versions, i just gave friends playback (the music icon) and it worked, now i have to give them that and Upload files for them to use !Yt, then i tried to do that for another friend it didn't work. I had to manually register an acc for him from the web interface and set to his name then give him playback and upload files in order to play music. i just removed upload files and he can't use the command and when i enabled it works.

**Comment by flyth** [comment]
Ah, okay. !yt downloads something and for that the upload privilege is required. Might sound strange at first, but as it kind of uploads something to your server (requiring space), I thought it'd be better to request that privilege as well. If that's wrong on the commands-page, I need to update it.

**Comment by SephLeague** [comment]
meh, the upload files permission i thought has to do with uploading music files manually via the web interface. 

You've done a really good job on this man. Thanks for your hard work.
