### ISSUE TITLE
List of ports

### ISSUE THREAD

**Issue by SephLeague** [flyth/ts3soundbot#319]
There should be a list of ports  the bot needs to function properly so we can allow it if we have firewalls.

**Comment by flyth** [comment]
Inbound: only the port you configure in your config.ini.
Outbound: Everything the bot needs to reach (e.g. 80/tcp 443/tcp for streams) and of course everything that a TS client would need.

**Comment by SephLeague** [comment]
Well i mainly wanted to know for like all the features like !search was working without firewall but when i enabled it it keeps saying no results.

**Comment by flyth** [comment]
If you get ANY result using !search (even no result found), it hasn't got to do with the firewall. It generally shouldn't have anything to do with the firewall at all, because all internal bot communication is on 127.0.0.1.

**Comment by supimfuzzy** [comment]
What he is saying is that using the !search function does not search the web. It only searches the music you have uploaded onto the server.

**Comment by SephLeague** [comment]
Oh i thought maybe it searches youtube and provides links and !play grabs the first result and plays it
