### ISSUE TITLE
Music Folder

### ISSUE THREAD

**Issue by am4nr** [flyth/ts3soundbot#32]
Organize Music in different Folder

**Comment by flyth** [comment]
That's basically what the playlists are for. I will think about more ways to organize larger collections - like browsing by artist / album / genre & such. Also playlists will get the ability to upload directly to them to make things more simple.

**Comment by am4n** [comment]
But i mean if you use the bot with multiple user's it would be pretty awesome if you can put the different tracks in userspecific folders

**Comment by flyth** [comment]
will continue in #93
