### ISSUE TITLE
Bot wont start at all 

### ISSUE THREAD

**Issue by Graakt** [flyth/ts3soundbot#326]
So im on windows and when i hit the SinusBot shortcut it opens then instantly vanishs ive been redownloading it and deleting it over and over and it wont work please help.

**Comment by Graakt** [comment]
My config looks like no other config on this forum
![e693c9df124fc1cb8a7efe6ffb88e5f3](https://cloud.githubusercontent.com/assets/13129200/8447529/ee63b590-1f7f-11e5-84a8-95e95d97865f.png)

**Comment by Khailz** [comment]
Get rid of the double \\ and change them to /

**Comment by Graakt** [comment]
nope it still doesnt work

**Comment by Graakt** [comment]
TS3Path = "C:/SinusBot/TeamSpeak 3 Client/ts3client_win64.exe"
ListenHost = "0.0.0.0"
ListenPort = 8087

**Comment by Khailz** [comment]
Try it again reversed if you haven't already

**Comment by Graakt** [comment]
Nope still crashed

**Comment by Graakt** [comment]
I fixed it ty My ts was downloaded into a really strange folder

**Comment by Graakt** [comment]
Ok sorry another question just popped up where do i got to make a actual bot it started but nothing happened 
![7b94e9f763a88f967caeabc82a425ccd](https://cloud.githubusercontent.com/assets/13129200/8447724/ad555966-1f82-11e5-91ae-44c1dec931bd.png)

**Comment by flyth** [comment]
http://127.0.0.1:8087
admin / foobar
