### ISSUE TITLE
Problem launching teamspeak client

### ISSUE THREAD

**Issue by Amalios** [flyth/ts3soundbot#328]
Hi everyone,

I'm having some trouble starting the bot, mainly because teamspeak client doesn't want to launch. I tried both solutions in the troubleshooting section, but it didn't work at all.

The error is :
"error while loading shared libraries: libgthread-2.0.so.0: cannot open shared object file: No such file or directory"

But the lib is on the directory ...

Thanks

**Comment by Multivit4min** [comment]
yeah i have the same problem with a different library wich is in the teamspeak directory

If i start with 
LD_PATH=<path_to_teamspeak_install_dir>/ ./ts3client_linux_amd64

I get the Error:
./ts3client_linux_amd64: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory

I know this isnt a ts3soundbot problem but i havent found anything in teamspeak forum or else google....

I use Debian Wheezy

I am able to Launch the Latest Public Beta Bot but not the closed Beta one, i already tried all troubleshooting possibilities

**Comment by BlueFreakLP** [comment]
Hi,
can you please try to install some libaries with apt-get install libglu1-mesa ?
If this wont work, please try the x86 versions:
apt-get install libglu1-mesa:i386

Please let me know if it works or not :)
@Multivit4min  @Amalios

**Comment by Multivit4min** [comment]
Same Error with libglu1-mesa :(

**Comment by flyth** [comment]
Please **do not** and **never** install any x86 lib. That won't help.
Please also **do not** set **LD_PATH**. That won't help either.
Rather make sure that _neither_ **LD_PATH** nor **LD_LIBRARY_PATH** is set in your environment (check with `env`).

If the bot still reports issues, make sure that *that* library is installed *from the official repositories, if possible*. **Do not** copy any libraries to the bot folders manually if not stated explicitly in the docs. libgthread-2.0.so.0 for example does not belong in the bot or TeamSpeak-folder. That folder should only contain everything that's been extracted from the official installation file (with the only exception being the plugin). The same counts for the bot directory.

**Comment by Amalios** [comment]
For me, I juste followed the guide, didn't install others librairies or wierd stuff, and still have errors concerning librairies :/

**Comment by flyth** [comment]
Did you install `apt-get install libglib2.0-0` as well?

**Comment by Amalios** [comment]
No, should I ?

**Comment by flyth** [comment]
If you're on Debian, then yes :) It says so in the [guide](https://github.com/flyth/ts3soundbot/wiki/Installation---Debian-&-Ubuntu) :)

If not on Debian, please let me know^^

**Comment by Amalios** [comment]
I'm on Ubuntu server 14

**Comment by flyth** [comment]
It shoudn't be necessary on Ubuntu, but you could still try. If it doesn't help, please post the output of the ldd-command.

**Comment by flyth** [comment]
Any results?

**Comment by Amalios** [comment]
I'll try in a few hours, have work to finish !

**Comment by Amalios** [comment]
Okay this is finally working, I installed libglib2.0-0, who seems to be needed on Ubuntu server !
Well I need it to be running in root mod, with the command 
"xinit /opt/ts3soundboard/ts3bot -RunningAsRootIsEvilAndIKnowThat -- /usr/bin/Xvfb :1 -screen 0 800x600x16 -ac"

Any idea how to fix it ?

**Comment by flyth** [comment]
Thanks for the information!

What exactly tells you that you need to be root? Just make sure the entire directory and all of its subdirectories belong to the user you plan to use for the bot - so the bot can write to those directories.

`chown -R username:groupname /opt/ts3bot`
or whatever directory you used.

**Comment by BlueFreakLP** [comment]
@Amalios have you tried it? Was the try successful?
Please let me know that, so i can close the Ticket, if it works.

**Comment by Amalios** [comment]
Ok now everything is functionnal, thanks for your help !

**Comment by BlueFreakLP** [comment]
Thanks for you response :)
