### ISSUE TITLE
Soundcard not found?

### ISSUE THREAD

**Issue by xDefcon** [flyth/ts3soundbot#329]
Perfectly installed on CentOs 6. When the bot connects to TS3 server it show no soundcard

http://i.gyazo.com/f906f4bd8cc41c50440219410beeb8f9.png

I just get this error on console: Could not send config 

EDIT: Full log with Loglevel=10 http://paste.ubuntu.com/11807539/
How to fix?

**Comment by flyth** [comment]
[Crosspost](https://forum.sinusbot.com/discussion/95/soundcard-not-found).

**Comment by BlueFreakLP** [comment]
Then please use the Forum :)
