### ISSUE TITLE
radiotwitch.in

### ISSUE THREAD

**Issue by xLifeFelix** [flyth/ts3soundbot#330]
I know that Twitch is blocked and will probably be configurable in the future.
But I wanted to use http://radiotwitch.in/ and this site is also blocked.
I couldn't use the stream: http://monstercat.radiotwitch.in/twitch.m3u8
respectivly http://<Twitch_Name>.radiotwitch.in/twitch.m3u8

Will this also work in the future?

SFMBE

**Comment by BlueFreakLP** [comment]
I cant open your Streamlink with VLC.

**Comment by BlueFreakLP** [comment]
No Answer, radio cannot be opened normally, so its clear that the musicbot cant do that.
