### ISSUE TITLE
CMD closed

### ISSUE THREAD

**Issue by Alan-V** [flyth/ts3soundbot#332]
Hi,
When i launch "SinusBot 0.9.8" the cmd opens and closes and i can't go on http://127.0.0.1:8087. Pls help me, thx.

**Comment by BlueFreakLP** [comment]
Hi @Alan-V,
are you using the Windows or the Linux version?

**Comment by Alan-V** [comment]
I'm using the Windows version

**Comment by Khailz** [comment]
I don't use the Windows version but are you sure you're config is correct?

**Comment by Alan-V** [comment]
Yes, i'm on windows 7 64 bits and it is installed on "C:"

**Comment by nrauschcom** [comment]
You could try it with inactive Firewall / Security Programs.
If it works then, you have to unlock the Port 8087 TCP.

Warning: Re-Activate the Firewall after!

Alan-V <notifications@github.com> schrieb am Mo., 6. Juli 2015 01:30:

**Comment by Alan-V** [comment]
Doesn't work :/

**Comment by flyth** [comment]
Open the command line and start the bot manually, not via its shortcut. That way, the console will stay open and tell you what's wrong.

**Comment by Alan-V** [comment]
How can i open the command line and start the bot ?

**Comment by Khailz** [comment]
Go to the directory of the bot, hold shift, and click Open command prompt here

**Comment by Alan-V** [comment]
Ok it's done and now ?

**Comment by BlueFreakLP** [comment]
If you have open it and done that what @Khailz said, just type in NAME.exe (Replace it with the bot name, i dont know how its named in the windows version ;))

Then you should get an Output, please paste it here. @Alan-V

**Comment by Alan-V** [comment]
![sinusbot](https://cloud.githubusercontent.com/assets/6543986/8529456/9f19115c-241a-11e5-9b15-9fbacf690910.PNG) That's it

**Comment by Khailz** [comment]
YOu need to use the correct location of the Teamspeak 3 Client in your config

**Comment by Alan-V** [comment]
So what I have to do, i don't understand ? :/

**Comment by Khailz** [comment]
Just like I said, change the path to the Teamspeak 3 client in your config file. That means put the path of where your teamspeak 3 client is installed

**Comment by Alan-V** [comment]
oh ok, i'll try

**Comment by Alan-V** [comment]
He tells me that the path is wrong, put i've putted the right folder :/

**Comment by Khailz** [comment]
Are you sure that the path is correct, you have Teamspeak 3 located in the root directory of you bots folder?

**Comment by Alan-V** [comment]
Yes, it is at : C:\Program Files\TeamSpeak 3 Client

**Comment by Khailz** [comment]
That's not what the error says though

**Comment by flyth** [comment]
The windows installer normally copies the client into the bots' directory and doesn't require you to edit the config file at all. Didn't it do that at all?

**Comment by Alan-V** [comment]
I understand nothing, what I have do to from the begining ???

**Comment by flyth** [comment]
Please try from scratch, something during the installation got wrong:
* delete the complete folder C:\SinusBot.
* Download the latest version from my [website](https://www.sinusbot.com)
* Install it, following the instructions
* Make sure that `C:\SinusBot\TeamSpeak 3 Client\ts3client_win64.exe` exists; if it doesn't something, got wrong again
* If the file exists: start the bot

If the file however doesn't exist (that'd be strange), copy the WHOLE client directory from C:\Programs\....\TeamSpeak 3 Client\... to the Bot-Folder, so that `C:\SinusBot\TeamSpeak 3 Client\ts3client_win64.exe` exists afterwards.

**You don't need to change the config file manually.**

Hope that helps.

**Comment by Alan-V** [comment]
Hi, i don't have ts3client_win64.exe but ts3client_win32.exe, i'll copy the directory

**Comment by Alan-V** [comment]
I have copy the directory and nothing works.

**Comment by flyth** [comment]
You need the 64 bit version, not the 32 bit one. That's why I explicitly said ts3client_win64.exe.
It won't work with the TeamSpeak 32 bit version.
