### ISSUE TITLE
youtube-dl Windows

### ISSUE THREAD

**Issue by LegendWookie** [flyth/ts3soundbot#334]
So i downloaded Python and the normal Version of the yt-dl but both didnt work because when i wrote theyre path into the config it said "couldnt read the config" everytime i start the bot and i instantly closes again, anyone got a fix for that?

**Comment by flyth** [comment]
Please post your config.

**Comment by LegendWookie** [comment]
I uploaded it to Mega because i didnt know if i can upload it here somewhere, sorry if its wrong 

https://mega.co.nz/#!Z9dCWBxD!WTHvC1vI3S6zONK90akq1PM2kHo3LmhMHDAH1QbIQbU

**Comment by flyth** [comment]
That's youtube-dl - please post your **config** ;) And please post it as text.

**Comment by LegendWookie** [comment]
Oh im sorry.

TS3Path = "D:\\Sinud\\TeamSpeak 3 Client\\ts3client_win64.exe"
ListenHost = "0.0.0.0"
DataDir = ""
ListenPort = 8087
LocalPlayback = false
EnableLocalFS = false
LogLevel = 3
EnableProfiler = false
YoutubeDLPath = "D:\Sinud\yt-dl.py"
EnableDebugConsole = false
UploadLimit = 83886080
RunAsUser = 0
RunAsGroup = 0
InstanceActionLimit = 6
UseSSL = false
SSLKeyFile = ""
SSLCertFile = ""
Hostname = ""
MTU = 1500
SampleInterval = 100
StartVNC = false
EnableMulticastMetadata = false
EnableWebStream = false
LogFile = ""
LicenseKey = "Mw+nbtUhP4TLdjlZlmP8QhRrraTtmBkITNwQ6zwYnxg="
EnableAloneMode = false

[StreamRewrites]

**Comment by flyth** [comment]
Try `D:\\Sinud\\yt-dl.py`

**Comment by LegendWookie** [comment]
I can start the Bot now but when i try to download a Video it says youtube-dl not avaible

**Comment by flyth** [comment]
Yeah, for Windows you should actually use the "Windows exe"-file that you can find on their official download page.

**Comment by LegendWookie** [comment]
Thanks you very much it worked.

**Comment by flyth** [comment]
:) You're welcome.
