### ISSUE TITLE
bot cuts in and out 

### ISSUE THREAD

**Issue by flobie** [flyth/ts3soundbot#336]
here is what it sounds like http://vocaroo.com/i/s0NQarXxznE2

running windows 7 cpu usage 15% total  
ts3 bot using 1% when on high priority 
ts3 client 2% when on high 

fire wall port is open  

don't know what is causes it to sound like that

**Comment by flobie** [comment]
fixed it

**Comment by flyth** [comment]
Great :)
What did you do?

**Comment by flobie** [comment]
to fix go to the config and set sampleinterval to 50 
tested on windows 7

**Comment by flyth** [comment]
Ah, that's odd. Will look into it. Thanks for sharing!

**Comment by flobie** [comment]
yeah seems to be that number set it back to 100 just to see if it was luck but when i put it to 100 when choppy again but on 50 works fine

**Comment by s1kk** [comment]
Hey. I have the same problems and setting sampleinterval to 50 temporarily fixed it for me. After about 1h the cuts in and out are back.

Sample: http://pub.slown.de/soundbotcuts.mp3
Used command: !yt https://www.youtube.com/watch?v=HH8bJEt15Yg

As you can hear all elements of the audio are fastened. I just recorded 24 seconds of this song.

**Comment by flyth** [comment]
Update: the audio skipping has been fixed in one of the latest betas (0.9.9). See [forums](https://forum.sinusbot.com)
