### ISSUE TITLE
AUTO START RADIO STATION STILL NOT WORKING?

### ISSUE THREAD

**Issue by capsload** [flyth/ts3soundbot#338]
Whenever i start my Music Bot, it still does NOT autoplay the Radio stations.
What the, after all that months?

**Comment by Khailz** [comment]
Look at your logs, auto start works fine for radio stations, maybe not for actual songs though

**Comment by capsload** [comment]
Whats the actual correct config?
Can i set idle track too?
When the Bot startsup with a cronjob, it just doesnt start sometimes.
