### ISSUE TITLE
Konnte nicht gestartet werden Hilfe

### ISSUE THREAD

**Issue by nEstarra** [flyth/ts3soundbot#339]
ich habe sinusbot-win-0.9.8.6 installiert und wie das starten  dan schließt das sich
Bitte um Hilfe Danke schonmal

under window

**Comment by BlueFreakLP** [comment]
Bitte mit CMD starten und auf english schreiben..

**Comment by flyth** [comment]
Mehr Hilfe gibt's im Forum. Dort gibt es bereits ähnliche Themen, die sicherlich helfen. Bitte die Suche verwenden.
