### ISSUE TITLE
How to give privilege to new user for particular instance  ( not for all instances)

### ISSUE THREAD

**Issue by royaljaat111** [flyth/ts3soundbot#344]
Hello,

I want to give privileges to new user for a particular instance, I don't want to give privileges to all of the instances. I didn't find any such settings, please help me over this.

Thanks
Regards

**Comment by Khailz** [comment]
#204 and #209 a lot of other information on this as well if you read a lot of the issues.

**Comment by royaljaat111** [comment]
@Khailz  Thanks for the reply but, I didn't get the solution yet. Could you please explain me on this a little bit, Is this feature is coming soon or what?

**Comment by flyth** [comment]
This feature will be available in the premium version of the bot later on.
