### ISSUE TITLE
youtube-dl

### ISSUE THREAD

**Issue by freakxkiller** [flyth/ts3soundbot#345]
I have the Problem that the weninterface show me that youtube-dl ist not available 
although youtube-dl is installed on my Debian8 VServer. 
Sorry for my bad English im from Germany :D

**Comment by cookingboy3** [comment]
Remember to check the bot's config.ini file and set `YoutubeDLPath` to point to your copy of youtube-dl

**Comment by freakxkiller** [comment]
what is the standard Path to youtube-dl when i install it with apt-get?

**Comment by BlueFreakLP** [comment]
Try the command "locate youtube-dl"

**Comment by nrauschcom** [comment]
.. or `which youtube-dl`

**Comment by iTaskmanager** [comment]
@flyth: Can I download via youtube-dl Videos at 100MBs and more? It's don't working (~400MB YT-Song) via ts3soundboard.

**Comment by Bielecki** [comment]
I'm downloading music mixes longer than 1h, and I don't have any problems. Debian 7, youtube-dl version 2015.07.04.
