### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by SephLeague** [flyth/ts3soundbot#347]
Make it so you can queue youtube links. So if you do !ytque, it puts it after the current song is done, etc.

**Comment by flobie** [comment]
might want to look here before you put suggestion https://forum.sinusbot.com/discussion/140/current-feature-requests-fixes#latest

**Comment by SephLeague** [comment]
well i don't want it to download it or store it, i just want it so that when the current song's done it just automatically starts streaming the next one. Also youtube playlist supports would be extremely nice as well

**Comment by flyth** [comment]
This will come with one of the next beta releases.
