### ISSUE TITLE
Forbidden beim Login / Webinterface

### ISSUE THREAD

**Issue by CptWindows** [flyth/ts3soundbot#350]
Hey,
wenn ich versuche mich mit "Admin" und "foobar" einzuloggen kommt "Forbidden", woran liegt dies?

**Comment by nrauschcom** [comment]
​Try using "admin" instead of "Admin"

2015-07-30 16:51 GMT+02:00 CptWindows <notifications@github.com>:

> Hey,
> wenn ich versuche mich mit "Admin" und "foobar" einzuloggen kommt
> "Forbidden", woran liegt dies?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flyth/ts3soundbot/issues/350>.
>



-- 
Nico Rausch
nrauschcom Webdesign
http://nrausch.com/
*info@nrausch.com <info@nrausch.com>*

**Comment by IceFlom** [comment]
Benutzernamen immer komplett klein schreiben beim Login, dann klappt es. Gilt nicht nur für "admin", auch wenn weitere User angelegt werden über die Registrierungsfunktion im TS, werden diese komplett kleingeschrieben gespeichert.

**Comment by BlueFreakLP** [comment]
Hi, danke für die Lösung. Bitte versucht in Zukunft auf Englisch hier zu kommunizieren, damit die anderen auch etwas verstehen :)

By the way, the user above me said, that the usernames should by written in lower case, also if the user was registered over the teamspeak chat.
