### ISSUE TITLE
Edit the Webinterface

### ISSUE THREAD

**Issue by leoje** [flyth/ts3soundbot#353]
Hey guys,

I want to edit the webinterface ( I want to connect the webinterface with my homepage ) But i cant find the directory with the html file :/

Can anyone tell me the directory ? 

that would be great ^^

( im german, sry for my english ^^ )

**Comment by nrauschcom** [comment]
The Webinterface is down in the binaries (for now). Theres currently no way
of editing it.
Am 04.08.2015 00:27 schrieb "leoje" <notifications@github.com>:

**Comment by leoje** [comment]
Hmm thanks ^^

im a bit sad about that but ok ^o^

**Comment by flyth** [comment]
You can use the [API](https://www.sinusbot.com/api/#api-_), though.

**Comment by leoje** [comment]
Thank you, @flyth!
^^
