### ISSUE TITLE
Auto stop and resume playback

### ISSUE THREAD

**Issue by It0w** [flyth/ts3soundbot#355]
Hallo Zusammen,

erstmal vielen Dank für den großartigen Bot! Ist inzwischen fester Bestandteil unseres
TS-Servers.

Ist es möglich, dass der Bot die Wiedergabe automatisch pausiert, sobald kein User mehr im Channel ist, und fortsetzt, sobald wieder ein User den Channel betritt ?

is it possible to stop the playback if the channel is empty and resume the playback if the channel not longer empty

**Comment by flyth** [comment]
This feature is already implemented in the upcoming version to save cpu/bandwidth. :)

**Comment by It0w** [comment]
Vielen Dank ;)

Thanks !
