### ISSUE TITLE
TTS URL

### ISSUE THREAD

**Issue by Heronickproductions** [flyth/ts3soundbot#358]
I had tts working for a while but because google did bring in there captcha system i can not use it anymore.
and no i can not enable images as far as im aware  
 dos somebody know a way around this ?
![image](https://cloud.githubusercontent.com/assets/8710537/9274595/6f304ea6-4297-11e5-8b17-1310c4b624ae.png)

**Comment by Topsii** [comment]
http://w3m.sourceforge.net/MANUAL -> 
i - Peek image URL
ESC I - Save inline image to file

You should be aware that the same image link will give you a different image, if you call it 2 seconds later. So you'd have to set your browser to autodownload the link when loading the captcha page. That should possible too, but I gave up at that point.

After a long search I found a site that I can use:
http://www.voicerss.org/controls/speech.ashx?hl=__LOCALE&src=__TEXT&c=mp3

**Comment by CrAazZyMaN21** [comment]
You can still use Google's TTS with this link: http://translate.google.com/translate_tts?tl=__LOCALE&q=__TEXT&ie=UTF-8&total=1&idx=0&client=t

**Comment by BlueFreakLP** [comment]
Try to use another TTS service...
