### ISSUE TITLE
need help with other users

### ISSUE THREAD

**Issue by daniellee44** [flyth/ts3soundbot#359]
how can i allow other users on teamspeak to access the bot control panel in web browser to upload music and other things.

**Comment by CrAazZyMaN21** [comment]
Create Accounts for them there is no other solution.

**Comment by daniellee44** [comment]
but how can they get to it,what link do i need to give them to get to the web control panel?

**Comment by CrAazZyMaN21** [comment]
Your Server IP and Port

**Comment by daniellee44** [comment]
thanks
