### ISSUE TITLE
QT Error

### ISSUE THREAD

**Issue by J-kit** [flyth/ts3soundbot#360]
Hey,
sinusbot doesn't work because there is an error message box which says:
---------------------------
ts3client_win64
---------------------------
This application failed to start because it could not find or load the Qt platform plugin "windows".

Reinstalling the application may fix this problem.
---------------------------
OK   
---------------------------
Reinstalling has no effect on this error.

**Comment by flyth** [comment]
Solution to this can be found [here](https://forum.sinusbot.com/threads/windows-qt.330/#post-1739)
