### ISSUE TITLE
Startet nicht // Doesnt start because Windows 10

### ISSUE THREAD

**Issue by fabm3n** [flyth/ts3soundbot#362]
Wenn ich die .exe starte kommt das Fenster, aber der Bot startet nicht. Im Fenster steht nur Sinusbot Beta und Version 0.9.8 Und (C) 2013-2015 und so weiter, Mehr nicht

English: When I start the .exe then com e the window, but the Bot doesnt start. In the Windows is the default Text with Sinusbot Beta and the version

**Comment by BlueFreakLP** [comment]
Screenshoots?

**Comment by fabm3n** [comment]
Da gibt es nichts zu sehen... Das ist ja das Problem

**Comment by fabm3n** [comment]
The Problem is because win 10. Das Problem liegt an WIndows 10. Mein PC ist jetzt wieder auf windows 7 und da funktionier es bestens.

**Comment by alyphen** [comment]
I have no problems running it on Windows 10.
