### ISSUE TITLE
Playliste versus days and restart on join

### ISSUE THREAD

**Issue by Tryice** [flyth/ts3soundbot#363]
His would be nice to have pre-configured playlist depending on the day. At the playlist A would be played on Monday, Tuesday, B, C on Wednesdays ... it would Home to have a music that would be diferent and would avoid weariness.

And if possible add a restard of the music on player join. (When the music contain a message, that maybe better)

**Comment by flyth** [comment]
Please join the [forums](https://forum.sinusbot.com) to discuss new features / feature requests.
However - this would be rather a candidate for a script than becoming part of the core.

**Comment by nrauschcom** [comment]
Both can be achieved with scripting, I think. You're one of maybe 10 people
needing this feature, so it won't be added to the Main bot.
Am 29.08.2015 13:46 schrieb "Tryice" <notifications@github.com>:
