### ISSUE TITLE
Qt platform plugin

### ISSUE THREAD

**Issue by gmanc2** [flyth/ts3soundbot#365]
![Image of Issue](https://i.gyazo.com/f783cf0d36a0741d1658bcf71c2cbe07.png)
It keeps failing to start and I have no idea why can someone please give me an awnser?

**Comment by J-kit** [comment]
Install a custom teamspeak ,copy the plugin in it and configure the path in the config.ini

**Comment by BlueFreakLP** [comment]
See #360
