### ISSUE TITLE
Bot stops working after playing around

### ISSUE THREAD

**Issue by J-kit** [flyth/ts3soundbot#367]
Just started and stopped the bot 3 or 4 times in series and it stopped and threw this error:
2015/09/05 18:00:25 ae635314 ae7a64ba INFO   SEEK [syntax] 25.584333 OK
2015/09/05 18:00:26 ae635314 ae7a64ba INFO   STOP [admin] OK
2015/09/05 18:00:30 ae635314 ae7a64ba INFO   PLAY [syntax] f0f78401-b386-47c7-b3b9-13aecf320f52 OK
2015/09/05 18:00:31 ae635314 ae7a64ba INFO   SEEK [syntax] 24.510424 OK
2015/09/05 18:00:32 ae635314 ae7a64ba INFO   PLAY [admin] f0f78401-b386-47c7-b3b9-13aecf320f52 OK
2015/09/05 18:00:33 ae635314 ae7a64ba INFO   STOP [admin] OK
2015/09/05 18:00:33 ae635314 ae7a64ba INFO   PLAY [admin] f0f78401-b386-47c7-b3b9-13aecf320f52 OK
2015/09/05 18:00:33 ae635314 ae7a64ba INFO   PLAY [admin] f0f78401-b386-47c7-b3b9-13aecf320f52 OK
2015/09/05 18:00:34 ae635314 ae7a64ba INFO   STOP [admin] OK
2015/09/05 18:00:34 ae635314 ae7a64ba INFO   PLAY [admin] f0f78401-b386-47c7-b3b9-13aecf320f52 OK
2015/09/05 18:00:34 ae635314 ae7a64ba INFO   STOP [admin] OK
2015/09/05 18:00:34 ae635314 ae7a64ba INFO   PLAY [admin] f0f78401-b386-47c7-b3b9-13aecf320f52 OK
2015/09/05 18:00:34 ae635314 ae7a64ba INFO   STOP [admin] OK
2015/09/05 18:00:34 ae635314 ae7a64ba INFO   PLAY [admin] f0f78401-b386-47c7-b3b9-13aecf320f52 OK
2015/09/05 18:00:35 ae635314 ae7a64ba INFO   STOP [admin] OK
2015/09/05 18:00:35 ae635314 ae7a64ba INFO   PLAY [admin] f0f78401-b386-47c7-b3b9-13aecf320f52 OK
2015/09/05 18:00:35 ae635314 ae7a64ba INFO   STOP [admin] OK
2015/09/05 18:00:35 ae635314 ae7a64ba INFO   PLAY [admin] f0f78401-b386-47c7-b3b9-13aecf320f52 OK
2015/09/05 18:00:35 ae635314 ae7a64ba INFO   STOP [admin] OK
2015/09/05 18:00:35 ae635314 ae7a64ba INFO   SEEK [syntax] 29.879974 OK
2015/09/05 18:00:36 ae635314 ae7a64ba INFO   PLAY [admin] f0f78401-b386-47c7-b3b9-13aecf320f52 OK
2015/09/05 18:00:36 ae635314 ae7a64ba INFO   STOP [admin] OK
2015/09/05 18:00:36 ae635314 ae7a64ba INFO   PLAY [admin] f0f78401-b386-47c7-b3b9-13aecf320f52 OK
2015/09/05 18:00:36 ae635314 ae7a64ba INFO   STOP [admin] OK
2015/09/05 18:00:36 ae635314 ae7a64ba INFO   PLAY [admin] f0f78401-b386-47c7-b3b9-13aecf320f52 OK
2015/09/05 18:00:36 ae635314 ae7a64ba INFO   PLAY [admin] f0f78401-b386-47c7-b3b9-13aecf320f52 OK
2015/09/05 18:00:36 http: panic serving 192.164.214.70:56360: send on closed channel
goroutine 3776 [running]:
net/http.func·011()
       /usr/local/go/src/net/http/server.go:1130 +0xbb
main.(*BotInstance)._stopNoClear(0xc208116f00)
        /opt/go/src/frie.se/ts3bot/stream.go:516 +0x187
main.(*BotInstance).Stop(0xc208116f00)
        /opt/go/src/frie.se/ts3bot/stream.go:502 +0x45
main.func·065(0x7f8ba3eecd80, 0xc208af68c0, 0xc208a59240)
       /opt/go/src/frie.se/ts3bot/server.go:1165 +0x24e
main.func·041(0x7f8ba3eecd80, 0xc208af68c0, 0xc2082c8dc0)
       /opt/go/src/frie.se/ts3bot/server.go:185 +0x395
main.func·042(0x7f8ba3eecd80, 0xc208af68c0, 0xc2081e1110, 0xc20816bce0, 0x1, 0x3)
       /opt/go/src/frie.se/ts3bot/server.go:297 +0x1197
github.com/flyth/httprouter.(*Router).ServeHTTP(0xc20818f1d0, 0x7f8ba3eecd80, 0xc208af68c0, 0xc2081e1110)
        /opt/go/src/github.com/flyth/httprouter/router.go:294 +0x18e
net/http.serverHandler.ServeHTTP(0xc20805d1a0, 0x7f8ba3eecd80, 0xc208af68c0, 0xc2081e1110)
        /usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208af6820)
        /usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1751 +0x35e

**Comment by flyth** [comment]
Which version is that?

**Comment by J-kit** [comment]
9.8

**Comment by flyth** [comment]
Then it has probably been fixed in the newer beta versions of 0.9.9.

**Comment by J-kit** [comment]
Thank you for the fast response :)
