### ISSUE TITLE
Youtube dl fail for more than 10 hours

### ISSUE THREAD

**Issue by J-kit** [flyth/ts3soundbot#368]
Hey
When i add a youtube video which is >= 10 hours long, it only drops a simple error on the queue screen
(for example: https://www.youtube.com/watch?v=OWFBqiUgspg)
Adding other big mp3's also dont work.

**Comment by flyth** [comment]
Upload limit for mp3s and such can be configured in the config.ini. Youtube-dl has a hardcoded limit of 200MB right now, I'll remove that soon / make it configurable as well.
Please use the [forums](https://forum.sinusbot.com) to discuss such things, thanks ;)
