### ISSUE TITLE
Soundcloud support?

### ISSUE THREAD

**Issue by NowNewStart** [flyth/ts3soundbot#374]
I think soundcloud is a great platform for music, and it would be a great thing to have it supported in the ts3 musicbot.

**Comment by DerEnderKeks** [comment]
You can download music from Soundcloud with youtube-dl. You can use the upload tab in the web interface or use !yt <link>.

**Comment by BlueFreakLP** [comment]
For a complete list checkout https://github.com/rg3/youtube-dl/blob/master/docs/supportedsites.md
