### ISSUE TITLE
Cannot run it

### ISSUE THREAD

**Issue by jasrosa** [flyth/ts3soundbot#379]
xinit: XFree86_VT property unexpectedly has 0 items instead of 1
/user/jasiek/ts3bot/ts3bot: 1: /user/jasiek/ts3bot/ts3bot: cannot create l�@@���@8: Permission denied
/user/jasiek/ts3bot/ts3bot: 1: /user/jasiek/ts3bot/ts3bot:ELF: not found
/user/jasiek/ts3bot/ts3bot: 2: /user/jasiek/ts3bot/ts3bot: Syntax error: ")" unexpected
xinit: connection to X server lost

waiting for X server to shut down

**Comment by BlueFreakLP** [comment]
I see there a permission error. Please make sure, that all permissions are set right.

**Comment by jasrosa** [comment]
Did everything as in instructions and nothing changes.

**Comment by DerEnderKeks** [comment]
Do `chown USERNAME:GROUP -R ./`(Replace your user and the group oft your user) and `chmod 755 ./ts3bot` in the folder of your bot. That should fix it.

**Comment by jasrosa** [comment]
No, it didn't fix it.

**Comment by nrauschcom** [comment]
Are you sure you run 64 bit OS?

**Comment by jasrosa** [comment]
Ouch, should it be 64-bit?

**Comment by BlueFreakLP** [comment]
yes..

**Comment by jasrosa** [comment]
Someone know when will be 32-bit version?

**Comment by Xuxe** [comment]
Hey,

https://forum.sinusbot.com/faq/i-get-some-message-like-elf-not-found-on-linux-when-trying-to-start-the-bot-wtf.4/

currently i don't know something about a 32-bit version.
