### ISSUE TITLE
Announce tracks in another Channel

### ISSUE THREAD

**Issue by snikerfreak** [flyth/ts3soundbot#38]
Possible to announce the track name in the channel name? 
Yes, i know it has a limitation, but it will be amazing.

**Comment by flyth** [comment]
General Settings -> Announce tracks

**Comment by snikerfreak** [comment]
I dont mean the channel CHAT. Yes, i use it.
I want to accounce in the channel NAME. Is this possible in the future?
(via Server or Client query)

**Comment by flyth** [comment]
Ah, sorry, didn't get that "name" was a variable :) If that requires client/server query, then this will not happen anytime soon - if not, I might add it. Will do some testing later.

**Comment by snikerfreak** [comment]
I dont think it requires. I dont know how can you do the channel chat announcer, i was thought you use this with query. 
Anyways, if its possible to do without query, I'll thank you. :)

**Comment by flyth** [comment]
Can be implemented by scripts soon.
