### ISSUE TITLE
Please be Quiet! How to STOP or REMOVE the Idle Song?? :)

### ISSUE THREAD

**Issue by thomasmalley** [flyth/ts3soundbot#380]
The Idle Song Feature is a nice Idea in general :+1: 
But since it is only ONE Song or Playlist that can be set as "Idle-Song" or "idle-playlist" where can i see, which one is set in the web interface or maybe via a !command?

I would like to have the Ability to remove or disable the Idle function via a simple click in the Web-Interface (i have a paid subscription of your service Bot-ID is buffalo119)

And it would be even nicer if i could still really !Stop the Bot :no_good:  

like a !mute function :+1:

**Comment by nrauschcom** [comment]
In instance settings, you can delete the idle song/playlist. I think there
is no chatcommand for this right now.
Am 08.10.2015 2:17 Nachm. schrieb "thomasmalley" <notifications@github.com>:

**Comment by flyth** [comment]
Will come with the next version as !!stop
