### ISSUE TITLE
Ability to import files from the local file system.

### ISSUE THREAD

**Issue by SilverCory** [flyth/ts3soundbot#384]
This would be a massive help. Previously using ts3musicbot, I've now over 10000 songs I'd love to import but by upload?! That's not happening.

![alt text](http://i.ac3-servers.eu/gallery-images/2015-11-01_12-02-38.png "list of music dirs")

I understand there's some link between the metadata of the song and the generated filename... Maybe an importer would be nice.. I'll work on one if I can figure it out (java), but if it were included it would be fantastic.

Please note if one is included somehow, I was unable to find it so maybe better documentation on it?

**Comment by SilverCory** [comment]
Dupeeee #37

Never saw the next page, mybad.. Mind you that's a long time ago..

**Comment by BlueFreakLP** [comment]
Duplicated = Close ;)
@flyth is checking the tickets, but there are other priorities.

**Comment by SilverCory** [comment]
Wee ooo!
[SinusPls, a file importer for SinusBot](https://github.com/SilverCory/SinusPls).

Figured out, tested, and made by moi. All works as intended. The only thing I've not tested is the fix feature.

Maybe #37 can enjoy this also. ;)
