### ISSUE TITLE
Remove folder - playlist import - localization

### ISSUE THREAD

**Issue by Niggolo** [flyth/ts3soundbot#386]
Hello,

beta 0.9.9-4965f0f
Ubuntu 14.04
Dedicated Server

Im using Mozilla firefox, i definitely like it except the limit :p

1)http://prntscr.com/8xxkp9 - those are created by import playlist, even after delete all the music inside i cant remove them, this is what the console is saying: FILE-DELETE [admin] (fd80ecd6-df1b-406f-a45e-76b03527a1f2) NOK

2)http://prntscr.com/8xxm1z - when i import a playlist that contains file blocked where the bot is host (in my case ovh - france), them get added to the list and they are blocking the bot, the fisrt song in the screenshot is blocking the bot, also if with shuffle enabled it find a blocked song the bot stop reproduce the playlist (i tryed to download the song and i confirmed it is blocked to my state), maybe is possible to skip the song if it is not found or corrupt or other case so the bot dont get blocked.

3)http://prntscr.com/8xxost - the file contains letter like "ò à ù è" and they appear like an error in the web, there is a method for fix them? the file is UTF-8

Sorry if there are errors but english is not my main language!
I also posted this on main forum because i didnt know if was the right place lol
Thank you

**Comment by flyth** [comment]
Please don't crosspost. The forum is the correct place to post stuff like that.
