### ISSUE TITLE
Playlist not displaying correctly

### ISSUE THREAD

**Issue by cjmwid** [flyth/ts3soundbot#388]
http://puu.sh/lbhyG/81c912ad42.png

selected multiple songs from "All music" created playlist, dragged and dropped. When i go to view it, looks like that?

**Comment by nrauschcom** [comment]
Hast du versucht, die Seite neuzuladen?

**Comment by cjmwid** [comment]
Rebooting the whole bot fixes the issue, only happens when its first created

**Comment by nrauschcom** [comment]
Omg i have no idea why i answered in German.. :D It's way too early.
Refreshing the Website (F5) should be enough,  I think.

**Comment by cjmwid** [comment]
I have and that didnt seem to do justice, ill try to recreate the issue.

**Comment by BlueFreakLP** [comment]
The Webinterface is based on angularjs, so there are maybe some script blockers, that cause erros like this.
