### ISSUE TITLE
Bot connectet nicht zum ts3 Server

### ISSUE THREAD

**Issue by KingPat-HD** [flyth/ts3soundbot#393]
Hallo, ich habe folgendes Problem. Ich starte den Bot, gucke im Ts3, hat keiner Connectet. Drücke ich noch mal auf dem Start Button im Webinterface, kommt in der Console:

2015/11/27 15:07:22 4e6d2aab 80d54491 WARN   Could not request shutdown. Please make sure that the loopback interface is not firewalled.
2015/11/27 15:07:23 4e6d2aab 80d54491 INFO   KILL [admin] OK

Sinusbot Version: 0.9.9
Server Version: Linux Debian 7 Wheezy 64 Bit
32 GB Ram

Config,ini:

TS3Path = "/opt/ts3soundboard/TeamSpeak3-Client-linux_amd64/ts3client_linux_amd$
ListenHost = "0.0.0.0"
DataDir = ""
ListenPort = 8087
LocalPlayback = false
EnableLocalFS = false
MaxBulkOperations = 300
LogLevel = 3
EnableProfiler = false
YoutubeDLPath = ""
EnableDebugConsole = false
UploadLimit = 83886080
RunAsUser = 0
RunAsGroup = 0
InstanceActionLimit = 6
UseSSL = false
SSLKeyFile = ""
SSLCertFile = ""
Hostname = ""

**Comment by AustrianNoob** [comment]
Hallo,

ich glaube es liegt daran, da das Sicherheitslevel deines Teamspeak 3 Servers zu hoch ist.

Einfach folgendes machen:

Virtuellen Server editieren -> Sicherheit -> Benötigte Sicherheitsstufe [DIES BITTE MUSST DU AUF 8 oder niedriger STELLEN!]

Dann müsste es funktionieren.

Mfg

AustrianNoob
