### ISSUE TITLE
Youtube Playlist : first song only.

### ISSUE THREAD

**Issue by Dhacan** [flyth/ts3soundbot#396]
Hello,
i know there are some other threads about the youtube playlist, i've read the FAQ, but despite the fact some people seemed to have fixed it, i didn't find a solution myself.
I'm using the bot on Xubuntu, installed version 0.9.8 and checked for updates. I also installed youtube-dl using the depository. It seems youtube-dl is working as i get that message when launching sinusbot : 'youtube-dl version compatible, support enabled'. I'm using the command !yt playlist, the problem is it only downloads and plays the first song, not the whole playlist.
Any help would be appreciated. Thank you !

**Comment by flyth** [comment]
The 0.9.9 betas feature initial support for playlists. Please have a look at the forums for more info on that.

**Comment by Dhacan** [comment]
Thank you for the quick answer. I just installed version 0.9.9, copied libsoundbot_plugin.so to teamspeak plugins, restarted the bot with './sinusbot', but still only the first song is played. :/

 Also when starting the bot i have some errors :
 > 2015/12/06 19:50:47 ecf0f9f8 eb7e55ba WARN   Script not loaded / crashed. Took too long.
 
 After closing sinusbot, it seems it's stuck and i've to ctrl+c twice to completely shut it down.
  >2015/12/06 20:03:02 [GENERAL        ] Shutting down... Hold on...

>desktop@ns326432:~/Bureau/ts3soundboard$ 2015/12/06 20:03:03 ecf0f9f8 eb7e55ba INFO   TS>libpng warning: iCCP: known incorrect sRGB profile
>2015/12/06 20:03:03 ecf0f9f8 eb7e55ba INFO   TS>warning: The VAD has been replaced by a hack pending a complete rewrite
>2015/12/06 20:03:03 ecf0f9f8 eb7e55ba INFO   TS>warning: The VAD has been replaced by a hack pending a complete rewrite
>2015/12/06 20:03:03 ecf0f9f8 eb7e55ba INFO   TS>qt.network.ssl: QSslSocket: cannot resolve SSLv2_client_method
>2015/12/06 20:03:03 ecf0f9f8 eb7e55ba INFO   TS>qt.network.ssl: QSslSocket: cannot resolve SSLv2_server_method
>2015/12/06 20:03:03 ecf0f9f8 eb7e55ba INFO   TSClient quit.
>2015/12/06 20:03:03 X [MAIN] Disconnected:  0
>2015/12/06 20:03:03 X [MAIN] Disconnected:  2

**Comment by flyth** [comment]
Please use the forums to ask for support - you will get more answers there in general.

Click Help => What's new to see a shot tutorial on how to use that feature.

**Comment by Dhacan** [comment]
Thank you, it's working !
i will ask on the forum about those errors though. :)
