### ISSUE TITLE
Announce Song not working because of notification error.

### ISSUE THREAD

**Issue by Khailz** [flyth/ts3soundbot#4]
d1fc3917 d1fc3917 WARN   Could not delete from Notifications no such table: Notifications
d1fc3917 d1fc3917 WARN   Could not insert into Notifications-Table no such table: Notifications

Tried adding a table but still receive this error

**Comment by flyth** [comment]
That message has nothing to do with the "Announce"-functionality and can simply be ignored for now. Announcing should work just fine in the latest version, if you enabled the option in the bot settings.

**Comment by Khailz** [comment]
Alright I'll do clean install and see what happens, just seem like Notification would go along with Announce :D

**Comment by Khailz** [comment]
Did my re install and still announce doesn't work, I've tried different types of channels as well. No errors in log.

**Comment by flyth** [comment]
If someone else runs into this issue as well: the bot had no privileges to write to the channel.
