### ISSUE TITLE
Kann SinusBot-Datei nicht ausführen

### ISSUE THREAD

**Issue by xXSenSeleSSXx** [flyth/ts3soundbot#400]
Sobald ich den Shortcut "Sinusbot 0.9.8" ausführen will  öffnet sich für eine sehr kurze zeit eine Konsole aber dann schliesßt sie sich wieder, ohne dass ich irgendeine chance haben etwas abzulesen oder ähnliches.

**Comment by BlueFreakLP** [comment]
Hallo @xXSenSeleSSXx ,
erstmal würde ich dich bitten auf Github in Englisch zu kommunizieren. Solltest du weiterhin Probleme haben, so kannst du gerne das Forum nutzen: https://forum.sinusbot.com/

**Comment by BlueFreakLP** [comment]
Please use the referenced ticket.
