### ISSUE TITLE
Login to panel Error/YT Failed

### ISSUE THREAD

**Issue by CameronRedGem** [flyth/ts3soundbot#402]
Hi there,

I setup port forwarding for the bot to add mp3 files for other people. When I do allowed them to login and access to upload ... it says an error for them. Help?

----
I also tried to bound the YT plugin in with the bot, but also failed help?

**Comment by BlueFreakLP** [comment]
We could help you, but you dont provide us any information like, the error message or the console log. @CameronRedGem
