### ISSUE TITLE
Can't open the bot (on windows)

### ISSUE THREAD

**Issue by PatrickePatate** [flyth/ts3soundbot#409]
Hello, My english is so bad because I'm french, so be nice ^^

When I open the bot, it instantly close. WTF !!

Please help me !

**Comment by BlueFreakLP** [comment]
More information please...

**Comment by PatrickePatate** [comment]
When I click on the bot, the cmd's open And instantly close. I try to start it in compatibility mode, but is the same.

**Comment by BlueFreakLP** [comment]
#397 same..
