### ISSUE TITLE
URL for access the panel

### ISSUE THREAD

**Issue by ItaloRFD** [flyth/ts3soundbot#415]
when I run the bot, appears in a line

[GENERAL/!!!!!!!] NOTICE You may now configure and launch the bots from the webinterface. http://0.0.0.0:8087

And my doubt is, how can i access de panel in web? 

In this tutorial (https://www.youtube.com/watch?v=54hGDTuDygk) he access from "tutorial.sahm.ga:8087"

I try to access from my ip address, but the page doesn't exist.

**Comment by BlueFreakLP** [comment]
Try 127.0.0.1:8087 or YOURSERVERIP:8087


0.0.0.0 means that the bot just listens to all available IPs..
