### ISSUE TITLE
Fehler mit Console

### ISSUE THREAD

**Issue by Jugendarzt** [flyth/ts3soundbot#418]
Hallo ich habe einen Fehler mit der Console also mit dem Programm.

Es startet sich für ca 2 sek und schließt sich direkt wieder . bitte um hilfe!

**Comment by BlueFreakLP** [comment]
Weitere Info wie Betriebssystem, Log usw. und bitte **englisch** , sonst in Forum.

**Comment by BlueFreakLP** [comment]
#397
