### ISSUE TITLE
Spotify support

### ISSUE THREAD

**Issue by JohnnyCrazy** [flyth/ts3soundbot#42]
Hey,

Spotify support would be nice.
It's also available for linux [here](https://www.spotify.com/de/download/previews/)

The only complicated part is controlling it.

**Comment by flyth** [comment]
There won't be a direct integration of things like spotify which require external libs; however, there's a (not yet documented) interface one can use to extend the sources of music by writing plugins. More on that later.

**Comment by BlueFreakLP** [comment]
I do not think that it will be implemented. There is no such thing in the interest of Spotify.

**Comment by Tmplt** [comment]
Would it not be possible to use mopidy? Or is Spotify precluded?
