### ISSUE TITLE
Only 2 Instances?

### ISSUE THREAD

**Issue by ZuckerZunge** [flyth/ts3soundbot#420]
Why can i only have 2 instances?
Am I stupid or is this normally so?
When it is normally so, why it is? :(

**Comment by DerEnderKeks** [comment]
Please look at https://forum.sinusbot.com/faq/can-i-have-more-than-2-instances.9/ ;)

**Comment by montawartek** [comment]
Right now you can’t - at least not directly. Having more than 2 instances is a feature that will be available in the premium version. However: there are events and give-aways where we are giving out licenses before the release of version 1.0.
