### ISSUE TITLE
Bot

### ISSUE THREAD

**Issue by Bogdan57002** [flyth/ts3soundbot#423]
Hello, i speak a little be english (i'm french).
I download the Sinus Bot, but i don't know my username and my password for the playlist (http://127.0.0.1:8087/play/files) 
How can we know your username and password?
Thank's !

**Comment by TxS-PRIME** [comment]
Normally:
admin
foobar

Change the password when done. (Done by going to Settings>User Accounts>Edit (Next to purple × by default)>Password,Repeat Password

This will log you out, simply login with admin and the new password.

Enjoy.
