### ISSUE TITLE
Web Playlist Bug

### ISSUE THREAD

**Issue by xNanochip** [flyth/ts3soundbot#426]
On the "Upload" page, whenever you "Download Files" from a URL, and you add that song to a playlist, it corrupts the page and this happens:

http://i.imgur.com/PhVOtGe.png

**Comment by BlueFreakLP** [comment]
@xNanochip Have you installed an Adblocker or a plugin like noscript, that can possibly block javascript?

**Comment by xNanochip** [comment]
just the generic adblock on google chrome, yes. but no script remover. the page seems to be fine now, no idea what the issue was or how to fix it.

**Comment by BlueFreakLP** [comment]
The Frotnend is written in Javascript, it´s always possible that some Plugins recongnize the script wrong.

**Comment by BlueFreakLP** [comment]
Seems like a bug, see #411
