### ISSUE TITLE
Better web interface

### ISSUE THREAD

**Issue by CookieMichal** [flyth/ts3soundbot#428]
Hello,
Basically I would like to propose a small change in web interface for `/help/scripting` - changing some `<p>` to `<pre>`. I think it would make some examples (mostly manifests and code) more readable.

Before:
![before2](https://vgy.me/M0HthT.png)
After:
![after2](https://vgy.me/9l4Qd6.png)

**Comment by flyth** [comment]
Should already look like that in the recent beta releases. :)

**Comment by CookieMichal** [comment]
You should make some kind of update notifications then :joy: Just updated to `0.9.11-ee30ef7` and it looks good :+1:
