### ISSUE TITLE
console

### ISSUE THREAD

**Issue by zoxovsky** [flyth/ts3soundbot#43]
1 question, where is debug console? :+1:

**Comment by flyth** [comment]
Got removed by default. You can enable it again by editing the config.ini to contain `EnableDebugConsole = true`, restarting and then manually calling http://yourip:8087/settings/debug in the latest version.

**Comment by zoxovsky** [comment]
doesnt work :(http://gyazo.com/ce2f451fc4d6a2705f0a0204529655fb

**Comment by flyth** [comment]
You're right, sorry. Will work like described in the next version.

**Comment by zoxovsky** [comment]
ok, thanks :)
