### ISSUE TITLE
Sinusbot doesn't execute and no error message.

### ISSUE THREAD

**Issue by relationlife** [flyth/ts3soundbot#430]
Hey there. i installed sinusbot but its not working at all.
when i type execute command on root and sinusbot user
both not working,
i just follow your instructions. but i have no idea why is not working.

i tried re-install my server OS, and fresh install bot.
but no lucks.
![image](https://cloud.githubusercontent.com/assets/18433311/14481471/2264570c-016e-11e6-8b4f-5d5fb6ea787a.png)
![image](https://cloud.githubusercontent.com/assets/18433311/14481549/16aa12ac-016f-11e6-8bcf-6ab97851759a.png)

**Comment by RalphPvp** [comment]
Having same problem i have it set to log level 10 but its not logging anything. It was running fine before i ran some update commands and restarted the server.

**Comment by Sygix** [comment]
I have the same problem, i under debian 8.

**Comment by LoloLaurentiu** [comment]
I have the same problem. I even installed the bot again, I made a linux server reboot but nothing

**Comment by flyth** [comment]
Please redownload the latest version and copy over the files. I forgot to remove the expiry time that was set for an internal version when making it an official beta.

**Comment by LoloLaurentiu** [comment]
the latest version is 0.9.11-ee30ef7 ?

**Comment by flyth** [comment]
Yes - that is actually a newer version, I just haven't found the time to announce properly and wanted to offer a quick fix for everyone.

**Comment by LoloLaurentiu** [comment]
ok thanks a lot for the answer

**Comment by LoloLaurentiu** [comment]
just an off topic question. can you tell me where the bot saves the mp3 that I upload via php website ?? 
Thanks

**Comment by relationlife** [comment]
@flyth Thanks a lot! It perfect works :D

![image](https://cloud.githubusercontent.com/assets/18433311/14537861/dc9c52fa-02b3-11e6-82b4-173694cdc150.png)
