### ISSUE TITLE
[TRNASLATE] Czech language

### ISSUE THREAD

**Issue by JandyCZ** [flyth/ts3soundbot#434]
Hello, I would like to translate SinusBot into Czech language, if it can be possible.

**Comment by BlueFreakLP** [comment]
@flyth

**Comment by flyth** [comment]
[How-To](https://forum.sinusbot.com/threads/how-to-localize-sinusbot.587/)
[Language Files](https://forum.sinusbot.com/resources/categories/language-files.10/)
