### ISSUE TITLE
[Feature Request] Poke for play !

### ISSUE THREAD

**Issue by JanDevDE** [flyth/ts3soundbot#44]
Hey,

one useful feature:

It would be nice if you could poke the bot with a YouTube link, so he plays it. (For users). If two people poke him, then the song is being played after the other song (playlist).

**Comment by Khailz** [comment]
But chat works best in case you reach the poke limit of 100 characters

**Comment by JanDevDE** [comment]
Yes, poke or write, I do not mind ...

**Comment by Khailz** [comment]
The text already works

**Comment by JanDevDE** [comment]
You mean with !yt LINK ?

I meant that users can write to the bot and their songs are in a playlist, and they are played.

**Comment by Khailz** [comment]
Ah I see I see, they dont get add to playlist but they do get added to the music database. 

I think !yt https://www.youtube.com/watch?v=5KJjBRm0ElA <playlistname> would be a good command

**Comment by JanDevDE** [comment]
... yes. Its useful for cummunity teamspeaks when users can give the bot music wishes. (So the wishes must be add in a playlist ;) )

**Comment by flyth** [comment]
Somehow connected to #28
