### ISSUE TITLE
Running headless

### ISSUE THREAD

**Issue by Chuckatron** [flyth/ts3soundbot#443]
Is there any way of running Sinusbot in a headless server environment. As far as I can see, the TS3 client needs a display to start. When I run the sinusbot executable, nothing appears to happen:
```
sinusbot@vps:~$ ./sinusbot 
sinusbot@vps:~$
```
Any thoughts?

**Comment by maxibanki** [comment]
Update to the latest version, then it should work perfectly.
https://www.sinusbot.com/pre/sinusbot-0.9.12.2-58b509d.tar.bz2

**Comment by Chuckatron** [comment]
Aha! Updated and it's working perfectly now. Thanks :)
