### ISSUE TITLE
Bot wont start

### ISSUE THREAD

**Issue by MPK1** [flyth/ts3soundbot#444]
Hi there,
my bot wont start after update to 0.9.11.
It simply does nothing if I type ./sinusbot.
I tried it with or without screen, as root, nothing works.

If I type:

"xinit /opt/ts3soundboard/TeamSpeak3-Client-linux_amd64/ts3client_linux_amd64 -- /usr/bin/Xvfb :1 -screen 0 800x600x16 -ac" 

I get:

xinit: XFree86_VT property unexpectedly has 0 items instead of 1
/opt/ts3soundboard/TeamSpeak3-Client-linux_amd64/ts3client_linux_amd64: error while loading shared libraries: libquazip.so: cannot open shared object file: No such file or directory
xinit: connection to X server lost

It is a Debian 8 vServer (64bit).

Can you help me pls?

**Comment by maxibanki** [comment]
Update to the newest version:
https://forum.sinusbot.com/resources/sinusbot-beta.3/
Or for a new installation use the installer script, which installs everything fine:
https://forum.sinusbot.com/resources/sinusbot-installer-script.58/

**Comment by MPK1** [comment]
Thank you, the Installer worked for me.
