### ISSUE TITLE
Bot is not joining server.

### ISSUE THREAD

**Issue by XDRosenheim** [flyth/ts3soundbot#445]
**What I do**
On `http://server:8087/settings/instances` I click the "power" button, which is red. It turns green for a second and then goes red again.

**TeamSpeak server settings**
Nothing unusual. No server password. No channel passwords.

**Bot settings and versions**
TS3 client: TeamSpeak3-Client-linux_amd64-3.0.19.3
Sinusbot version: sinusbot-0.9.8

**Instance log**
On startup

    2016-07-06T20:26:25+02:00 Loaded
    2016-07-06T20:26:25+02:00 Starting instance ts3server://192.168.1.2?port=9987&nickname=MusicBot&password=&channel=Lobby&channelpassword=
    2016-07-06T20:26:25+02:00 TSClient quit.
    2016-07-06T20:26:30+02:00 Could not request shutdown
    2016-07-06T20:29:45+02:00 Starting instance ts3server://192.168.1.2?port=9987&nickname=MusicBot&password=&channel=Lobby&channelpassword=
    2016-07-06T20:29:46+02:00 TSClient quit.

When trying to manually start the instance

    2016/07/06 21:04:48 bb7f9932 a54ecc4b INFO   Starting instance ts3server://192.168.1.2?port=9987&nickname=MusicBot&password=&channel=&channelpassword=
    2016/07/06 21:04:48 bb7f9932 a54ecc4b INFO   TSClient quit.
    2016/07/06 21:05:02 bb7f9932 a54ecc4b INFO   BOT-CONFIG [admin] HOST CHAN CHANPW ANNOUNCE ANNOUNCESTR DUCKING DUCKINGVOLUME STICKY TTSLOCALE CHATIGNSRV CHATIGNPRIV CHATIGNCHAN CC OK
    2016/07/06 21:05:05 bb7f9932 a54ecc4b INFO   Starting instance ts3server://127.0.0.1?port=9987&nickname=MusicBot&password=&channel=&channelpassword=
    2016/07/06 21:05:06 bb7f9932 a54ecc4b INFO   TSClient quit.

**Comment by Khailz** [comment]
That version of Sinusbot is outdated go [here ](https://forum.sinusbot.com/resources/sinusbot-beta.3/)for the latest version.

**Comment by XDRosenheim** [comment]
Well, in that case, maybe https://www.sinusbot.com/ should be updated then.  
Download links are for 0.9.8.  
Will try with 0.9.12.2-58b509d later and post results...

**Comment by XDRosenheim** [comment]
Yep, 0.9.12.2-58b509d works. Thank you. Closing.
