### ISSUE TITLE
Subchannels not listet correct

### ISSUE THREAD

**Issue by dmham187** [flyth/ts3soundbot#5]
When I have 
```
Channel 1
  Subchannel 1
  Subchannel 2
Channel 2
```
and I want the bot to be in Subchannel 2, it has to be "Channel 1/Subchannel 2", but when I select Subchannel 2 from the list, it doesn't add "Channel 1" in front of it, so the bot stays in the default channel.

**Comment by flyth** [comment]
Thanks. This has been fixed in the latest version.
