### ISSUE TITLE
[Bug] Download file from Youtube etc.

### ISSUE THREAD

**Issue by JanDevDE** [flyth/ts3soundbot#50]
Hello,

when i try to download a song from youtube and it comes a "fail" then i cant click on cancel or redownload it, because it gives me "duplicate" ... plese fix it

(sorry for the bad english by the way)

**Comment by flyth** [comment]
You're right, re-downloading a failed download won't work right now - however: if it displays "duplicate", it actually failed again. If it would have worked, it would've shown "success".

**Comment by JanDevDE** [comment]
Then is the question, why it failed. When i enter in the console "youtube-dl -x LINK" then it download normal. When i enter it in the webinterface then it fail...

Console:

root@JanHS:/home# youtube-dl -x https://www.youtube.com/watch?v=AmX6XX3lMy0
[youtube] AmX6XX3lMy0: Downloading webpage
[youtube] AmX6XX3lMy0: Extracting video information
[youtube] AmX6XX3lMy0: Downloading DASH manifest
[download] Destination: DJ Mehdi   Lucky Boy (Outlines Remix) (GTA V Soundtracks)-AmX6XX3lMy0.m4a
[download] 100% of 8.06MiB in 00:00
[ffmpeg] Correcting container in "DJ Mehdi   Lucky Boy (Outlines Remix) (GTA V Soundtracks)-AmX6XX3lMy0.m4a"
WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.
[youtube] Post-process file DJ Mehdi   Lucky Boy (Outlines Remix) (GTA V Soundtracks)-AmX6XX3lMy0.m4a exists, skipping

**Comment by JanDevDE** [comment]
And sometimes:

WARNING: [youtube] AmX6XX3lMy0: Skipping DASH manifest: ExtractorError(u'Cannot                                                                                         decrypt signature without player_url; please report this issue on https://yt-dl.                                                                                        org/bug . Make sure you are using the latest version; type  youtube-dl -U  to up                                                                                        date. Be sure to call youtube-dl with the --verbose flag and include its complet                                                                                        e output.',)

**Comment by Suspect** [comment]
@flyth I'm currently having a problem with downloading a file at all, I'm not sure if this is after the recent updates or after I ran an apt-get update / apt-get upgrade - if after the apt updates could it be a compatability issue with a updating an app?

**Comment by JanDevDE** [comment]
@Suspect Me too. The reason is the fix update for upload, i think ...

**Comment by JanDevDE** [comment]
@flyth @Suspect Update: Songs download now but when I try to download the failed songs it gives me "duplicate" and dont download it.

**Comment by flyth** [comment]
I'm sorry, that's because due to the bug the files are now out of sync :/ The next version will do more logging to let you fix the issue manually if necessary.
I'll try to add an auto-sync routine in a future update as well.

**Comment by JanDevDE** [comment]
@flyth Ok, thanks. Do the "Cancel" Button work now ?

**Comment by Suspect** [comment]
@flyth Thanks for the quick fix.

**Comment by flyth** [comment]
@JanDevDE it should, I haven't tested again.
@Suspect you're welcome ;)
