### ISSUE TITLE
Switching channels when the bot is online

### ISSUE THREAD

**Issue by MrJoki007** [flyth/ts3soundbot#51]
It would be cool, if you have a dropdown menu in the webinterface, to switch the channel of the bot after joining or a following mode, where the bot follows the admin account linked ts3 client

**Comment by Niggolo** [comment]
well it had Debug console but it is removed now :(

**Comment by flyth** [comment]
The debug console will be back again soon, just not enabled by default. The goal is that it isn't necessary at all to have that debug-thing active. So channel-switching will sooner or later find its way to the web-interface... ;)

**Comment by BlueFreakLP** [comment]
You can also let it connect once and then you can set in the settings the Channel to connect on next restart.

**Comment by MrJoki007** [comment]
but if im on a server without permissions and want to switch channels i dont want to restart the bot every time ...

**Comment by Niggolo** [comment]
if im not wrong you can just go to bot setting, select the channel and press "save" the bot should move to the selected channel without restart

**Comment by MrJoki007** [comment]
No that doesnt work

**Comment by Niggolo** [comment]
Oh ok

**Comment by BlueFreakLP** [comment]
For me its working well

**Comment by flyth** [comment]
Implemented.
