### ISSUE TITLE
[feature] Different login for each instance

### ISSUE THREAD

**Issue by Niggolo** [flyth/ts3soundbot#54]
i have 2 instance of ts with different staff but i would like to limit the access of staff to specific istance:

Instance 1 -  Admin1 / instance 2 - Admin2 --> from account panel you can add specific user to specific istance
mysite.com:8097 --> if you login with Admin1 you have access only to Instance1 same with Admin2
playlist permission  --> somewhere on the panel you can specific who can edit/remove/ect a playlist

i dont know if it is possible, but it is a good feature!

**Comment by zoxovsky** [comment]
MICHAEL FRIESE : 

There’s another feature to create whole new instances but that feature will be limited to commercial hosters, I think.

So, no. :)

**Comment by Niggolo** [comment]
What?

**Comment by zoxovsky** [comment]
This version will "maybe" sell to commercial hosters.

**Comment by Niggolo** [comment]
Hm bad bad!! :)

**Comment by flyth** [comment]
Yup, not completely sure what to do there.

**Comment by Niggolo** [comment]
Well if you can make some money yeah you should sell it ;)

**Comment by zoxovsky** [comment]
You could make this version but only for a fee, let's be serious, if it is free, the internet will be paid web hosts mass musicbot panel free from flytha

**Comment by Niggolo** [comment]
Ok so what I do with the issue? Can I close it?

**Comment by flyth** [comment]
Yes - at least for now ;) I'll think about it.

**Comment by Niggolo** [comment]
on changelog i found this: "feat: hosting-administration" 
it is about the thing you are talking above?

**Comment by flyth** [comment]
Yes

**Comment by mauzao9** [comment]
Yeah this is on my wishlist i would say :)
