### ISSUE TITLE
[Feature Request] Youtube Playlist

### ISSUE THREAD

**Issue by Junxx** [flyth/ts3soundbot#56]
add support for youtube-playlist ?
like !yt https://www.youtube.com/playlist?list=PLDicGQs0uy8jl8XuGDTTFIQnbi5oyqkpL
then you got "Now playing: majesticdubstep - Purity Ring - Belispeak (PatrickReza Remix) (1/22)"

if you type !ytgoto "Number" you can chose what a song next play like !ytgoto 7 after 7 was played he go automatic forwards.

**Comment by flyth** [comment]
I may sooner or later add support to import playlists, but !ytgoto or such special commands won't happen, sorry. That'd overcomplicate things for the user as well as for me.

**Comment by Junxx** [comment]
ah ok :D with !ytgoto i mean that you can jump to a song in the Playlist... but is ok when its not comming :D thx for your work man !

**Comment by flyth** [comment]
That's how I understood it; but if an import would be implemented, the result would be normal playlists, so no !ytgoto would be necessary.
