### ISSUE TITLE
Randomize a playlist

### ISSUE THREAD

**Issue by snikerfreak** [flyth/ts3soundbot#59]
Sorry, if i'm too blind to see it.
I want to have a link to randomize the content of a playlist.
Is it possible to be a feature?

And one more question:
In bulk mode, what really does the radio boxes left the tracks? (i cant delete multiple files or anything)

Thanks! :)

**Comment by flyth** [comment]
There's a shuffle-button at the bottom between next track and the volume slider to play in a random order (there's a ticket about the randomness that is far from perfect right now).
Bulk-mode should let you delete more than one file at a time and add multiple files to playlists at once (by using the dropdown or delete button of one of the tracks). I'm aware that this is not yet really user-friendly.
