### ISSUE TITLE
[Bug - Info] download problem

### ISSUE THREAD

**Issue by Niggolo** [flyth/ts3soundbot#60]
I was trying to download some music but this is what i got:
http://prntscr.com/69bijx

this is one of the error music, can someone else try to download it and tell me if it worked?:
https://www.youtube.com/watch?v=E_MfFKbgV80

this is what the console say:
CHAT [niggolo @ Niggolo] < !yt [URL]https://www.youtube.com/watch?v=E_MfFKbgV80[/URL] > / OK

**Comment by flyth** [comment]
You need to update your youtube-dl.

**Comment by Niggolo** [comment]
oh ok thank you :)
