### ISSUE TITLE
[enh] !yt link

### ISSUE THREAD

**Issue by Niggolo** [flyth/ts3soundbot#61]
I dont know if it already on different issue (i dont find it) btw
is possible to reproduce !yt link ever if it is already on list? 
examble:
!yt https://www.youtube.com/watch?v=bpwQGzvU-OU
on job list i get:
https://www.youtube.com/watch?v=bpwQGzvU-OU 	8.95MiB 	00:00 	1.47MiB 	duplicate

**Comment by flyth** [comment]
Duplicate just means that it won't save the file again to save space; it should add it to the list / play it though. If you've tried to download that earlier when there was a bug with the uploads/downloads, downloading that video won't work for now.

**Comment by Niggolo** [comment]
oh yeah now it work, it say duplicate but it play it
