### ISSUE TITLE
Karaoke Mode

### ISSUE THREAD

**Issue by am4nr** [flyth/ts3soundbot#64]
A Karaoke Mode would be so fcking awesome but i guess its pretty hard to do right?

**Comment by BlueFreakLP** [comment]
If you can describe it better.... Maybe possible

2015-02-27 22:36 GMT+01:00 am4nr <notifications@github.com>:

**Comment by flyth** [comment]
It's not hard to do, but getting the lyrics with timestamps is pretty hard and usually not legal - and I think there's not that much interest in this feature that it would justify spending the time :)

**Comment by am4nr** [comment]
either in a new tab in the webinterface where a window is for the lyrics or the bot posts the lyrics in the chat dunno

**Comment by BlueFreakLP** [comment]
I think its a feature, that has someuse for some people but isn´t important
at this time.

**Comment by Niggolo** [comment]
lol pretty useless for me

**Comment by am4nr** [comment]
well its a ts3musicbot its not pretty usefull^^ anyway i think the idea is pretty awesome

**Comment by mauzao9** [comment]
I mean it's possible i mean all you have to do is tell it to stream a karaoke version of the song and let people sing :o

**Comment by MrJoki007** [comment]
It would be very funny but i think not much people would use it

**Comment by am4nr** [comment]
i mean if you sit with your friends in the ts and they drunk a little too much it would be so funny.
if you put in like a text editor where you can start a song and make timestamps for each song yourself when which words should be posted

**Comment by flyth** [comment]
I agree that it could be funny, but I won't be spending time on such a thing, if only a couple of people use it. Please always remember that this is a spare-time project.
