### ISSUE TITLE
cant start multiple bots

### ISSUE THREAD

**Issue by Christopher-Lifoy** [flyth/ts3soundbot#65]
hallo cant start mutiple bots :(
have any idea to fix it ?

2015-02-27 17:41:22.088125|ERROR   |Query         |   | bind failed on 127.0.0.1:25639
2015-02-27 17:41:22.505050|INFO    |              |   | *** Time [MAINWINDOW]: 222
2015-02-27 17:41:22.505317|INFO    |              |   | *** Time [INIT]: 223
 i found on 1 log but i dont now its for the problem or not 

have a nice day

**Comment by flyth** [comment]
Remove the client query plugin. Is that the windows version?

**Comment by Christopher-Lifoy** [comment]
now i have found it i think i add the  i_client_max_clones_uid  to the gust group and it work

**Comment by flyth** [comment]
Ah, well... then generate new identities for the bots. Don't use the dummy ids that come with the bot.

**Comment by Christopher-Lifoy** [comment]
i have modifit it on the general config :) when its Identity 

thnaks for you help g


schönen tag noch :)
