### ISSUE TITLE
Show track details in the bot user description

### ISSUE THREAD

**Issue by stoni133** [flyth/ts3soundbot#68]
First, thank you for this awesome music bot!!!

We have three bots in one channel and they stream radio stations.
When someone wants to hear a specific radio station he unmutes it.
The announcement with chat messages is not very useful for us because of the spam that the three bots produce.

Could you implement an option to display the current song details in the teamspeak client description of the bot?
I don't know if this is accessible without a server query.
Sadly the user names are limited to 30 chars in teamspeak so they are no option for the song details.

This would be very useful if you want to know the current song without getting spammed by the bot!

**Comment by MrJoki007** [comment]
but why you dont make a channel for every musicbot?

**Comment by flyth** [comment]
I will look into this as an alternative to the chat-announcing :)

**Comment by flyth** [comment]
Implemented, coming soon.
