### ISSUE TITLE
Bot wont start

### ISSUE THREAD

**Issue by thetruestarr1337** [flyth/ts3soundbot#69]
Hello, nice TS3 Bot you have :)

Im running Ubuntu 64x 14.04 LTS Server

But i have one issue. I installed everything nessecery and i got this error (loglevel 10)

  _____ ___ _______                   _ _                      _
 |_   _/ __|__ / __| ___ _  _ _ _  __| | |__  ___  __ _ _ _ __| |
   | | \__ \|_ \__ \/ _ \ || | ' \/ _` | '_ \/ _ \/ _` | '_/ _` |
   |_| |___/___/___/\___/\_,_|_||_\__,_|_.__/\___/\__,_|_| \__,_|

               (C) 2013-2015 Michael Friese. All rights reserved.

2015/03/04 05:57:52 df198784 INFO   Initializing bot://df198784-8a66-4bbc-92f1-8                                 15a7497008a
panic: attempt to write a readonly database

goroutine 10 [running]:
github.com/jmoiron/sqlx.MustExec(0x7fe8c503e5f8, 0xc2080da750, 0x9e5110, 0x17, 0                                 x0, 0x0, 0x0, 0x0, 0x0)
        /opt/go/src/github.com/jmoiron/sqlx/sqlx.go:669 +0xde
github.com/jmoiron/sqlx.(*DB).MustExec(0xc2080da750, 0x9e5110, 0x17, 0x0, 0x0, 0                                 x0, 0x0, 0x0)
        /opt/go/src/github.com/jmoiron/sqlx/sqlx.go:341 +0xa2
main.(*DB).Init(0xc208033450, 0x9a9c60, 0x7, 0xc2080f2070, 0x61)
        /opt/go/src/frie.se/ts3bot/db.go:114 +0xc93
main.(*Bot).Init(0xc208033450, 0x0, 0x7fe8c503e3a0)
        /opt/go/src/frie.se/ts3bot/bot.go:125 +0x2dc
main.func·016()
        /opt/go/src/frie.se/ts3bot/main.go:498 +0x10cf
created by time.goFunc
        /usr/local/go/src/time/sleep.go:129 +0x4b

goroutine 1 [select (no cases)]:
main.main()
        /opt/go/src/frie.se/ts3bot/main.go:552 +0x269b

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [chan receive]:
database/sql.(*DB).connectionOpener(0xc20803dea0)
        /usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
        /usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 11 [chan receive]:
database/sql.(*DB).connectionOpener(0xc20803c0a0)
        /usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
        /usr/local/go/src/database/sql/sql.go:452 +0x31c

**Comment by flyth** [comment]
> panic: attempt to write a readonly database

Make sure the user you start the bot with owns the ./data - dir and each and everything in there.

`chown -R <username> ./data`

**Comment by thetruestarr1337** [comment]
Thanks, silly me :D 
Everything started http://gyazo.com/f61b3ad6ee0e6f98deac74710e0d5174
I guess?

but i cant connect to the Interface http://myip/8087 ?

**Comment by flyth** [comment]
It's `http://myip:8087`. Make sure ListenHost is set to `0.0.0.0` in the config.ini, though.

**Comment by thetruestarr1337** [comment]
hmm i did everything :) Locally on Server it works now, but no access from my home pc.. its working.. kind of.. danke :)
