### ISSUE TITLE
Custom Radio URLs?

### ISSUE THREAD

**Issue by capsload** [flyth/ts3soundbot#70]
Hey, how to add custom Radio URLS? ;P

**Comment by MrJoki007** [comment]
here you can add radio urls http://puu.sh/gmemu.png

**Comment by capsload** [comment]
Not Working for me.

**Comment by zoxovsky** [comment]
u must put here, addressurl:port from radio, better open radiostation in Winamp player and click here on file : view file information

and u saw this : http://gyazo.com/abb6eac8c51f2b4ddf46954603faa1a8

sorry i have PL version Winamp cuz im polish :P But this URL u can put on Add URL. Cheers

**Comment by flyth** [comment]
Closing this now as there are enough posts on this already.
