### ISSUE TITLE
Bind privileges to server groups

### ISSUE THREAD

**Issue by thetruestarr1337** [flyth/ts3soundbot#71]
(translated by @flyth)
Would it be possible to bind the users to server groups instead of user ids. I've got quite a few users and adding an account for everyone is a bit annoying.

...

--- original text:

Guten Tag :)
Wie gesagt toller Bot. Jetzt einmal auf Deutsch ( Kann es sonst nicht formulieren :D )

Gibt es die Möglichkeit, einer TS3 Servergruppe Rechte für den Bot zugeben, anstelle einer User ID ?
Ich habe ein paar User, und für jeden einen Account anlegen ist ein bissl blöd.

Ich hoffe du verstehst, was ich meine :p 

Gute Arbeit Weiter so :+1:  geht alles sonst

**Comment by flyth** [comment]
This is already on the todo-list - so yes, it's planned.

Danke :)

**Comment by thetruestarr1337** [comment]
ups sorry :) havent seen that

**Comment by flyth** [comment]
Implemented.
