### ISSUE TITLE
Can i get updates ?

### ISSUE THREAD

**Issue by JanDevDE** [flyth/ts3soundbot#74]
Hello,

I have searched in the past few days for updates, but found nothing. Have you in the last 7 days brought out an update ?

(Checked with ./ts3bot --update and only the logo came)

**Comment by flyth** [comment]
Nope :) I have a fulltime-job during the week and a family that demands some time as well.
However, in the little spare time I had, I've made much progress in securing / hardening the bot, which is crucial when using it publicly on the internet.

Please refrain from opening tickets **issues** to ask for ETA on updates in the future - this is an issue tracker :)

**Comment by BlueFreakLP** [comment]
And please note that this is a free Project and you are not paying for this.
