### ISSUE TITLE
Autoswitch back

### ISSUE THREAD

**Issue by capsload** [flyth/ts3soundbot#78]
Hello,

some users are moving the music bots around the server. 

could you do a feature, that the musicbots switch back to their set channels?

I know, i could set a permissions, but i want that the users are able to move other players, but not the musicbots!

**Comment by flyth** [comment]
Yup, there'll be a sticky-function in the next version for that.

**Comment by GavoTrav** [comment]
Its also possible to give the music bot a group with a higher client move power (i_client_needed_move_power) higher than 75 and a default server admin group cant even move it.

**Comment by flyth** [comment]
Implemented. Thanks for the alternative solution @GavoTrav !
