### ISSUE TITLE
Names for instances

### ISSUE THREAD

**Issue by Newcomer1989** [flyth/ts3soundbot#81]
Perhaps it's possible to name the instances free (instead of using the nickname of the bot).
Cause, there could be the same nickname at different servers and then you can can't distinguish the instances in the instance list.

**Comment by flyth** [comment]
Sorry that I didn't answer before: good idea, will come sooner or later :)

**Comment by flyth** [comment]
Implemented that a few months ago - available in the 0.9.9 betas right now.
