### ISSUE TITLE
Mute function

### ISSUE THREAD

**Issue by MrJoki007** [flyth/ts3soundbot#82]
A button in the webinterface where you can mute the bot and if you press the button again it turns up the volume as it was before the mute (ts3 command !mute)

**Comment by flyth** [comment]
Why not just use !stop? I could understand !pause, maybe. But !mute... do you really need that? I think it would confuse people only more, since they need to figure out that the bot is muted if they cannot hear anything (same applies partly to !pause).

**Comment by MrJoki007** [comment]
Because you can use the mute command if you listen to radio but you cant use the pause command there

**Comment by Khailz** [comment]
Teamspeak already has a built in mute button though.

**Comment by MrJoki007** [comment]
Yes but i want to mute the bot for all users and not only for me ...

**Comment by GavoTrav** [comment]
!volume 0 ?

**Comment by flyth** [comment]
I'd rather implement !play to resume playing a track/radio that has previously been stopped. I hope it's okay if I close this in favor of that.
