### ISSUE TITLE
[Bug] 2 Instances, 1 Identity

### ISSUE THREAD

**Issue by JanDevDE** [flyth/ts3soundbot#83]
Hello,

the first bot [Bot 1] was created. The second bot [Bot 2] was created.
The first bot is connected. The second want to connect. Error.

---> Bot 2 has the same identity as Bot 1.

(Sorry for my very badd english.)

**Comment by flyth** [comment]
Solution: Change the identity manually. The bot only has a few identities built in that _should_ be changed for security reasons.
