### ISSUE TITLE
[Bug] Updater

### ISSUE THREAD

**Issue by MrJoki007** [flyth/ts3soundbot#84]
Since yesterday evening the bot writes an message in the console UPDATER Could not determine own version.
When i try to update the bot manually it shows the same message

**Comment by zoxovsky** [comment]
./ts3bot -update

**Comment by MrJoki007** [comment]
http://puu.sh/grsfo.png Doesnt work

**Comment by zoxovsky** [comment]
Download it becouse its manually installation, http://frie.se/ts3bot/ts3soundboardbot-0.9.5.tar.bz2 (delete old ts3bot)

**Comment by MrJoki007** [comment]
Ok thanks worked

**Comment by flyth** [comment]
Please make sure to update the plugin as well.
