### ISSUE TITLE
Some problems + wish list

### ISSUE THREAD

**Issue by zoxovsky** [flyth/ts3soundbot#85]
Hiho, here is version 0.9.5 (new 7march)

Debug console still doesnt work :/

a good idea would be to add users to a given instance, an easy way to be able to control the bots from different channels or on other servers, eg. A friend.

in my mean that will be super greeeat,

+add your own style can upload (style.css etc) 
+add autostart music after join to channel/restart bot
+add menu translate our language :P

Will be really, really goood. Cheers

(When it comes to the issue of money to make your users in different instances of how much it will cost and when you can expect this version?)

**Comment by flyth** [comment]
See #73 #36 #54. I thought the debug console would work again, will take a look soon.

Localization is on todo, not sure when I'll find time to implement that, though.

I haven't yet decided on the multiple users/instances. How many separate instances do you plan? Please contact me by mail.

**Comment by flyth** [comment]
I will close this one and create separate issues.
