### ISSUE TITLE
Error: Index-File could not be served.

### ISSUE THREAD

**Issue by am4nr** [flyth/ts3soundbot#86]
When i try to start the bot this error message appears
![ss 2015-03-08 at 01 32 40](https://cloud.githubusercontent.com/assets/11098327/6545770/dd5049cc-c597-11e4-8b92-83e316342426.png)
and my webinterface doesnt show its just a blank space 
![ss 2015-03-08 at 10 59 30](https://cloud.githubusercontent.com/assets/11098327/6545769/d4db7b18-c597-11e4-944c-02898c08569d.png)

**Comment by flyth** [comment]
Could you please paste your config.ini?

**Comment by am4nr** [comment]
TS3Path = "/opt/ts3soundboard/TeamSpeak3-Client-linux_amd64/ts3client_linux_amd64"
ListenHost = "0.0.0.0"
DataDir = ""
ListenPort = 11501
LocalPlayback = false
SecretKey = [12, 206, 224, 121, 84, 84, 180, 189, 102, 203, 125, 214, 174, 13, 184, 38, 133, 50, 215, 233, 185, 225, 37, 228, 86, 5, 29, 231, 192, 223, 250, 38]
Debug = true
LogLevel = 10
EnableProfiler = false
YoutubeDLPath = "/usr/local/bin/youtube-dl"
EnableDebugConsole = true
UploadLimit = 0
RunAsUser = 0
RunAsGroup = 0
InstanceActionLimit = 6

**Comment by flyth** [comment]
Set `Debug = false` :) Don't use that setting.

**Comment by am4nr** [comment]
Thanks mate :)

**Comment by am4nr** [comment]
but there's something else
if i want to download something from youtube it show everytime error

**Comment by flyth** [comment]
Set `LogLevel = 10` and check the output. You may need to update your youtube-dl (or install, if you haven't before). See the documentation for that.
