### ISSUE TITLE
Text2Speech

### ISSUE THREAD

**Issue by BlueFreakLP** [flyth/ts3soundbot#89]
(Via Google Translator?)

Its a Fun feature, so its not important ^^

**Comment by Khailz** [comment]
I don't understand.

**Comment by MrJoki007** [comment]
its very funny if you want to troll people :D

**Comment by BlueFreakLP** [comment]
You type text in it and the bot say it like Google Translator

**Comment by Khailz** [comment]
Ah I though you meant something along the lines of reading details and stuff from songs. Silly me.

**Comment by flyth** [comment]
I'm sorry, but the terms of Google don't allow that :/

**Comment by flyth** [comment]
Maybe there are alternatives, but I don't know of anything that sounds good and is free to use.

**Comment by mauzao9** [comment]
I know one ts3musicbot.net around have one actually pretty good text to speech implementation, now if free or not, but would be interesting indeed. :dancers:
