### ISSUE TITLE
[bug] instances doesnt work

### ISSUE THREAD

**Issue by zoxovsky** [flyth/ts3soundbot#9]
Hello,

please fix it :/

http://i.gyazo.com/8f90c8c2a9e525254460ab33b568f4d2.png

**Comment by Khailz** [comment]
Refresh the page to make sure your on the selected instance, instances when switched dont update till you refresh. At least from what I tried

**Comment by flyth** [comment]
This was a bug, I hope it's fixed now.

@Khailz it shouldn't be necessary anymore to reload the page after changing the identity. If it still is, please tell me when and for what.

Thanks ;)
