### ISSUE TITLE
Autostart & und andere Probleme

### ISSUE THREAD

**Issue by P4InKiLL3R** [flyth/ts3soundbot#90]
Hallo Michael,

erstmal ein dickes Riesen Lob an Deine arbeit ;)

Ich verfolge Deinen Bot schon eine weile und habe ihn gestern 
nun das erste mal auf meinen Linus Server Installiert!

Dabei ist bei mir gleich folgendes Problem aufgetreten:

Sobald man die Console schließt beendet sich der Bot,is sicher
nicht so gewollt oder hab ich beim Installieren was falsch gemacht?

Habe ein paar Verbesserungsvorschläge für Dich:

1.)
die Musik die im Haupt Ordner liegt sollte nach dem abspielen des ersten Titels oder welchen man auch immer auswählt weiterspielen,so das man nicht gezwungen ist ein Playlist zu erstellen!
Shuffle & Repeat sollte sich auch auf den Kpl. Ordner auswirken!

2.)
es sollte Möglich sein im Haupt Musik Ordner auch Ordner selber zu erstellen!
Zwecks Sortierung nach Alben und Genre,im Moment wird ja alles zusammen in einen Haupt Ordner geschmissen wo man nach ca 10Cd´s leider den Überblick verliert was mich dann gleich zum nächsten Punkt bringt

3.)
Jeder Nutzer sollte seinen eigenen Musik Folder bekommen so das nicht 
alle anderen Zugriff auf mein Verzeichnis haben und evtl. sehen was ich 
denn gerne höre oder evtl. noch meine Musik löschen und es sollte Möglich sein ein Upload Limit für jeden Nutzer zu erstellen so das nicht irgendwann die Platte voll is :D

4.)
Pause - Start Funktion fehlt noch,atm geht nur Stop und dann muss 
man den Titel wieder von vorne Starten

5.)
Laufzeitangabe + Restzeit des Titel der grad läuft inkl.dem kpl. Album oder der gesamten erstellten Playlist

6.)
wo kann man seine eigenen Radiosender selber editieren btw. einfügen und die jetzigen löschen?

So das solls erstmal gewesen sein,Grüß nach Berlin ;)

MfG Nico

**Comment by flyth** [comment]
Thanks for your massive feedback! I will however close this issue soon and recreate a few english ones for each topic you mentioned so that everyone can participate in discussing them.

--

Vielen Dank für dein Feedback! :) Ich werde mal separate Issues aus den einzelnen Punkten, damit sich das dann besser abarbeiten lässt.

Zu deinem Problem, dass sich der Bot schließt: benutze bitte momentan `screen`, sonst beendet sich der Bot beim schließen des Fensters. Ein Init-Script folgt mit der nächsten Version.

Viele Grüße zurück!

**Comment by P4InKiLL3R** [comment]
Ich nutze Dein Startscript das so aussieht wo der Befehl screen schon drin is,oder wie muss der aussehen:

xinit /opt/ts3soundboard/ts3bot -- /usr/bin/Xvfb :1 -screen 0 800x600x16 -ac

**Comment by flyth** [comment]
Ich hab's gerade noch unten an den [Wiki-Eintrag](https://github.com/flyth/ts3soundbot/wiki/Installation---Debian-&-Ubuntu) gehängt. Abschnitt `Starting in a screen`.

**Comment by P4InKiLL3R** [comment]
Kann Dir grad nicht folgen :D

Wenn ich Dein startscript ausführe kann ich keinen Befehl mehr in der Console eingeben,
da is dann Schluss oder muss Dein Befehl angepasst werden,und wenn ja wie sieht der aus?

**Comment by flyth** [comment]
Du musst `screen` starten **bevor** du den Bot startest.

**Comment by P4InKiLL3R** [comment]
Hab so gestartet und da kommt ne Fehlermeldung:
screen -r xinit /opt/ts3soundboard/ts3bot -- /usr/bin/Xvfb :1 -screen 0 800x600x16 -ac

Meldung:
There is no screen to be resumed matching xinit.

**Comment by MrJoki007** [comment]
Du musst zuerst „screen“ eingeben und dann in dem screen den Befehl

 

Von: P@InKiLLeR [mailto:notifications@github.com] 
Gesendet: Montag, 9. März 2015 19:43
An: flyth/ts3soundbot
Betreff: Re: [ts3soundbot] Autostart & und andere Probleme (#90)

 

Hab so gestartet und da kommt ne Fehlermeldung:
screen -r xinit /opt/ts3soundboard/ts3bot -- /usr/bin/Xvfb :1 -screen 0 800x600x16 -ac

Meldung:
There is no screen to be resumed matching xinit.

**Comment by P4InKiLL3R** [comment]
Wenn ich nur screen eingebe kommt bei mir das:

There is a screen on:
        3074.pts-0.86i1oar      (03/09/15 14:39:52)     (Attached)
There is no screen to be resumed.

**Comment by flyth** [comment]
http://www.blazilla.de/index.php?/archives/190-screen-Mini-Anleitung.html

**Comment by JanDevDE** [comment]
Easy.

screen -S name <--- Create screen and attach them
STRG + A + D <--- Go out of the screen
screen -r name <--- Go in the screen
screen -r name -X quit <--- Quit the screen

Fertig :3

**Comment by MrJoki007** [comment]
wenn du screen -rx eingibst dann kommst du rein

**Comment by JanDevDE** [comment]
+MrJoki007, war meine Erklärung nicht genug ? ^^

**Comment by P4InKiLL3R** [comment]
Ich verstehe nur Bahnhof :D 

Welche Datei soll ich denn mit screen öffnen,wo soll denn der Befehl rein screen -r ?

**Comment by P4InKiLL3R** [comment]
So jetzt gehts,danke nochmal ;)
