### ISSUE TITLE
Privilege "Edit bot" only available for bot-admin

### ISSUE THREAD

**Issue by CrAazZyMaN21** [flyth/ts3soundbot#92]
When I create a account with all rights, the user can't open general settings only the admin user can open it (forbidden). What you can improve is that you split music and radio in another register card and save radio files. Hope I can help you with my report.

**Comment by flyth** [comment]
Thanks for report! Will be fixed in the next version.

About files/radio: I hope to improve that in one of the next versions, but it'll take some time :)
