### ISSUE TITLE
Folders

### ISSUE THREAD

**Issue by flyth** [flyth/ts3soundbot#93]
Let users create folders to sort their music.

**Comment by flyth** [comment]
![folders](https://cloud.githubusercontent.com/assets/1550037/6580795/27b08330-c753-11e4-9a55-9e08e48ac311.png)

**Comment by flyth** [comment]
Here's a [testbuild](http://frie.se/ts3bot/ts3bot-bin-0.9.101.tar.bz2) for this and several other new features that I don't want to push to everybody, yet - due to the many changes under the hood. The download only contains the binary, so just replace it. Be sure you're ready to face a few bugs, though!
I'd love to hear what you think about it (check the changelog as well, to see what else is new).

**Comment by mauzao9** [comment]
Hey, if we update will it auto-update later once it's pushed to everybody?

**Comment by mauzao9** [comment]
Ah wait i get this on the main version
"2015/03/12 15:20:28 UPDATER Could not determine own version.", will update to this build anyway

**Comment by flyth** [comment]
Yes, but until I do it will show that it can't determine the own version.

**Comment by flyth** [comment]
Oh wait, then you didn't update to 0.9.5 before. You should do that first, then. The plugin needs an update as well which you won't find in the binary-only zip^^

**Comment by mauzao9** [comment]
I did the start up the update part and tells me the could not determine own version again. I only put the binary it's kinda with the new features not sure if it's broken.

**Comment by flyth** [comment]
Did you update the plugin from the 0.9.5 release? Then everything should work fine.

**Comment by mauzao9** [comment]
I know there is some odd issues with bulk managing the music files, like drag and drop multiple files to a folder / playlist only places the one you selected first.

If i'm not mistaken the version i just updated this binary from had the last log entries on changelog:
enh: speed up loading of playlist when there have been no changes
fix: make instances work directly after creation (without reload)
feat: hosting-administration

**Comment by mauzao9** [comment]
Okay the bot had crash, can i find logs about it?

**Comment by flyth** [comment]
I've tried to address some of the issues with bulk management, but some are still in there. With the new folder-system you can use ctrl+c / ctrl+v to copy bulkselected files - which should save a lot of time. You can select files with space or shift+down/up.

**Comment by flyth** [comment]
If it crashed, it will log things in your screen-session.

**Comment by mauzao9** [comment]
Yeah i had a screen it just terminated it didn't got to saw.

Yeah i can't get bulkie things to work nicely when it comes to add multiple selected files at once to one playlist or folder, always move the first one i clicked to drag them. hm

**Comment by flyth** [comment]
So then it wasn't a crash^^ :)
Drag&drop is still in the works, sorry.

**Comment by mauzao9** [comment]
Okay or just add a top menu when active the bulk mode, "With Selected - Add to PlayList - Move to Folder - Tag Editor - Delete".
That would have a more direct control of the files for now ^^

**Comment by flyth** [comment]
Nah, drag&drop should work as well. :)

**Comment by flyth** [comment]
Implemented.
