### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by flyth** [flyth/ts3soundbot#95]
Add support for multiple languages. Provide English/German by default.

**Comment by flyth** [comment]
Here's the [German Locale-File](http://pastebin.com/iATY8Hna) as an example for those who want to prepare the interface in their own language. Localization-Support will come with the next version.

**Comment by flyth** [comment]
Implemented.

**Comment by Niggolo** [comment]
this is done by you directly on the code or there is a file we can edit?
